# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startnewprojectdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjectSetupDialog(object):
    def setupUi(self, ProjectSetupDialog):
        ProjectSetupDialog.setObjectName("ProjectSetupDialog")
        ProjectSetupDialog.resize(485, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectSetupDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(ProjectSetupDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/new-file-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.setup_tabs = QtWidgets.QTabWidget(ProjectSetupDialog)
        self.setup_tabs.setObjectName("setup_tabs")
        self.projectinfo_tab = QtWidgets.QWidget()
        self.projectinfo_tab.setObjectName("projectinfo_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.projectinfo_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.general_scrollArea = QtWidgets.QScrollArea(self.projectinfo_tab)
        self.general_scrollArea.setEnabled(True)
        self.general_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.general_scrollArea.setWidgetResizable(True)
        self.general_scrollArea.setObjectName("general_scrollArea")
        self.general_scrollAreaContents = QtWidgets.QWidget()
        self.general_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 424, 813))
        self.general_scrollAreaContents.setObjectName("general_scrollAreaContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.general_scrollAreaContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aboutproject_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.aboutproject_lbl.setObjectName("aboutproject_lbl")
        self.verticalLayout_2.addWidget(self.aboutproject_lbl)
        self.aboutproject_widget1 = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.aboutproject_widget1.setEnabled(True)
        self.aboutproject_widget1.setObjectName("aboutproject_widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.aboutproject_widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.projname_lbl = QtWidgets.QLabel(self.aboutproject_widget1)
        self.projname_lbl.setObjectName("projname_lbl")
        self.gridLayout_2.addWidget(self.projname_lbl, 0, 0, 1, 1)
        self.projname_line = QtWidgets.QLineEdit(self.aboutproject_widget1)
        self.projname_line.setObjectName("projname_line")
        self.gridLayout_2.addWidget(self.projname_line, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.aboutproject_widget1)
        self.aboutproject_widget2 = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.aboutproject_widget2.setObjectName("aboutproject_widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.aboutproject_widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_lbl = QtWidgets.QLabel(self.aboutproject_widget2)
        self.date_lbl.setObjectName("date_lbl")
        self.gridLayout.addWidget(self.date_lbl, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.location_combo = QtWidgets.QComboBox(self.aboutproject_widget2)
        self.location_combo.setObjectName("location_combo")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.location_combo.addItem("")
        self.gridLayout.addWidget(self.location_combo, 3, 1, 1, 1)
        self.region_lbl = QtWidgets.QLabel(self.aboutproject_widget2)
        self.region_lbl.setObjectName("region_lbl")
        self.gridLayout.addWidget(self.region_lbl, 2, 0, 1, 1)
        self.date_spin = QtWidgets.QDateEdit(self.aboutproject_widget2)
        self.date_spin.setDate(QtCore.QDate(2014, 2, 21))
        self.date_spin.setCalendarPopup(True)
        self.date_spin.setObjectName("date_spin")
        self.gridLayout.addWidget(self.date_spin, 0, 1, 1, 1)
        self.region_line = QtWidgets.QLineEdit(self.aboutproject_widget2)
        self.region_line.setObjectName("region_line")
        self.gridLayout.addWidget(self.region_line, 2, 1, 1, 1)
        self.location_lbl = QtWidgets.QLabel(self.aboutproject_widget2)
        self.location_lbl.setObjectName("location_lbl")
        self.gridLayout.addWidget(self.location_lbl, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.aboutproject_widget2)
        self.aboutuser_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.aboutuser_lbl.setObjectName("aboutuser_lbl")
        self.verticalLayout_2.addWidget(self.aboutuser_lbl)
        self.aboutuser_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.aboutuser_widget.setObjectName("aboutuser_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.aboutuser_widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.otherpersons_lbl = QtWidgets.QLabel(self.aboutuser_widget)
        self.otherpersons_lbl.setObjectName("otherpersons_lbl")
        self.gridLayout_7.addWidget(self.otherpersons_lbl, 3, 0, 1, 1)
        self.affiliation_lbl = QtWidgets.QLabel(self.aboutuser_widget)
        self.affiliation_lbl.setObjectName("affiliation_lbl")
        self.gridLayout_7.addWidget(self.affiliation_lbl, 2, 0, 1, 1)
        self.modellername_lbl = QtWidgets.QLabel(self.aboutuser_widget)
        self.modellername_lbl.setObjectName("modellername_lbl")
        self.gridLayout_7.addWidget(self.modellername_lbl, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 2, 1, 1)
        self.otherpersons_box = QtWidgets.QPlainTextEdit(self.aboutuser_widget)
        self.otherpersons_box.setMinimumSize(QtCore.QSize(0, 100))
        self.otherpersons_box.setDocumentTitle("")
        self.otherpersons_box.setObjectName("otherpersons_box")
        self.gridLayout_7.addWidget(self.otherpersons_box, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 2, 1, 1)
        self.affiliation_box = QtWidgets.QLineEdit(self.aboutuser_widget)
        self.affiliation_box.setObjectName("affiliation_box")
        self.gridLayout_7.addWidget(self.affiliation_box, 2, 1, 1, 1)
        self.modellername_box = QtWidgets.QLineEdit(self.aboutuser_widget)
        self.modellername_box.setObjectName("modellername_box")
        self.gridLayout_7.addWidget(self.modellername_box, 1, 1, 1, 1)
        self.otherpersons_lbl2 = QtWidgets.QLabel(self.aboutuser_widget)
        self.otherpersons_lbl2.setObjectName("otherpersons_lbl2")
        self.gridLayout_7.addWidget(self.otherpersons_lbl2, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.aboutuser_widget)
        self.synopsis_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.synopsis_lbl.setObjectName("synopsis_lbl")
        self.verticalLayout_2.addWidget(self.synopsis_lbl)
        self.synopsis_descr_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.synopsis_descr_lbl.setObjectName("synopsis_descr_lbl")
        self.verticalLayout_2.addWidget(self.synopsis_descr_lbl)
        self.synopsis_box = QtWidgets.QPlainTextEdit(self.general_scrollAreaContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synopsis_box.sizePolicy().hasHeightForWidth())
        self.synopsis_box.setSizePolicy(sizePolicy)
        self.synopsis_box.setMinimumSize(QtCore.QSize(0, 100))
        self.synopsis_box.setObjectName("synopsis_box")
        self.verticalLayout_2.addWidget(self.synopsis_box)
        self.projectboundary_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.projectboundary_lbl.setObjectName("projectboundary_lbl")
        self.verticalLayout_2.addWidget(self.projectboundary_lbl)
        self.synopsis_descr_lbl_2 = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.synopsis_descr_lbl_2.setObjectName("synopsis_descr_lbl_2")
        self.verticalLayout_2.addWidget(self.synopsis_descr_lbl_2)
        self.boundary_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.boundary_widget.setObjectName("boundary_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.boundary_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.projectboundary_lbl2 = QtWidgets.QLabel(self.boundary_widget)
        self.projectboundary_lbl2.setObjectName("projectboundary_lbl2")
        self.gridLayout_4.addWidget(self.projectboundary_lbl2, 1, 0, 1, 1)
        self.projectboundary_browse = QtWidgets.QPushButton(self.boundary_widget)
        self.projectboundary_browse.setObjectName("projectboundary_browse")
        self.gridLayout_4.addWidget(self.projectboundary_browse, 1, 2, 1, 1)
        self.projectboundary_line = QtWidgets.QLineEdit(self.boundary_widget)
        self.projectboundary_line.setReadOnly(True)
        self.projectboundary_line.setObjectName("projectboundary_line")
        self.gridLayout_4.addWidget(self.projectboundary_line, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.boundary_widget)
        self.projectlog_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.projectlog_lbl.setObjectName("projectlog_lbl")
        self.verticalLayout_2.addWidget(self.projectlog_lbl)
        self.projectlog_lbl2 = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.projectlog_lbl2.setObjectName("projectlog_lbl2")
        self.verticalLayout_2.addWidget(self.projectlog_lbl2)
        self.projectlog_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.projectlog_widget.setObjectName("projectlog_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.projectlog_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.projectlog_simple = QtWidgets.QRadioButton(self.projectlog_widget)
        self.projectlog_simple.setObjectName("projectlog_simple")
        self.horizontalLayout.addWidget(self.projectlog_simple)
        self.projectlog_compreh = QtWidgets.QRadioButton(self.projectlog_widget)
        self.projectlog_compreh.setObjectName("projectlog_compreh")
        self.horizontalLayout.addWidget(self.projectlog_compreh)
        self.verticalLayout_2.addWidget(self.projectlog_widget)
        self.path = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.path.setObjectName("path")
        self.verticalLayout_2.addWidget(self.path)
        self.projectpath_lbl = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.projectpath_lbl.setObjectName("projectpath_lbl")
        self.verticalLayout_2.addWidget(self.projectpath_lbl)
        self.path_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.path_widget.setObjectName("path_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.path_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projpath_lbl = QtWidgets.QLabel(self.path_widget)
        self.projpath_lbl.setObjectName("projpath_lbl")
        self.gridLayout_3.addWidget(self.projpath_lbl, 1, 0, 1, 1)
        self.projpath_button = QtWidgets.QPushButton(self.path_widget)
        self.projpath_button.setObjectName("projpath_button")
        self.gridLayout_3.addWidget(self.projpath_button, 1, 2, 1, 1)
        self.projpath_line = QtWidgets.QLineEdit(self.path_widget)
        self.projpath_line.setReadOnly(True)
        self.projpath_line.setObjectName("projpath_line")
        self.gridLayout_3.addWidget(self.projpath_line, 1, 1, 1, 1)
        self.keepcopy_check = QtWidgets.QCheckBox(self.path_widget)
        self.keepcopy_check.setObjectName("keepcopy_check")
        self.gridLayout_3.addWidget(self.keepcopy_check, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.path_widget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.general_scrollArea.setWidget(self.general_scrollAreaContents)
        self.verticalLayout_3.addWidget(self.general_scrollArea)
        self.setup_tabs.addTab(self.projectinfo_tab, "")
        self.verticalLayout.addWidget(self.setup_tabs)
        self.footer = QtWidgets.QWidget(ProjectSetupDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.footer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(ProjectSetupDialog)
        self.setup_tabs.setCurrentIndex(0)
        self.location_combo.setCurrentIndex(3)
        self.buttonBox.accepted.connect(ProjectSetupDialog.accept)
        self.buttonBox.rejected.connect(ProjectSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProjectSetupDialog)
        ProjectSetupDialog.setTabOrder(self.setup_tabs, self.general_scrollArea)
        ProjectSetupDialog.setTabOrder(self.general_scrollArea, self.projname_line)
        ProjectSetupDialog.setTabOrder(self.projname_line, self.date_spin)
        ProjectSetupDialog.setTabOrder(self.date_spin, self.region_line)
        ProjectSetupDialog.setTabOrder(self.region_line, self.location_combo)
        ProjectSetupDialog.setTabOrder(self.location_combo, self.modellername_box)
        ProjectSetupDialog.setTabOrder(self.modellername_box, self.affiliation_box)
        ProjectSetupDialog.setTabOrder(self.affiliation_box, self.otherpersons_box)
        ProjectSetupDialog.setTabOrder(self.otherpersons_box, self.synopsis_box)
        ProjectSetupDialog.setTabOrder(self.synopsis_box, self.projectboundary_line)
        ProjectSetupDialog.setTabOrder(self.projectboundary_line, self.projectboundary_browse)
        ProjectSetupDialog.setTabOrder(self.projectboundary_browse, self.projectlog_simple)
        ProjectSetupDialog.setTabOrder(self.projectlog_simple, self.projectlog_compreh)
        ProjectSetupDialog.setTabOrder(self.projectlog_compreh, self.projpath_line)
        ProjectSetupDialog.setTabOrder(self.projpath_line, self.projpath_button)
        ProjectSetupDialog.setTabOrder(self.projpath_button, self.keepcopy_check)
        ProjectSetupDialog.setTabOrder(self.keepcopy_check, self.buttonBox)

    def retranslateUi(self, ProjectSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectSetupDialog.setWindowTitle(_translate("ProjectSetupDialog", "Setup New Project"))
        self.subtitle.setText(_translate("ProjectSetupDialog", "Project Information, Simulation Path and Data Management Settings"))
        self.title.setText(_translate("ProjectSetupDialog", "Setup New Project"))
        self.aboutproject_lbl.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">About the Project</span></p></body></html>"))
        self.projname_lbl.setText(_translate("ProjectSetupDialog", "Project Name"))
        self.date_lbl.setText(_translate("ProjectSetupDialog", "Project Start Date:"))
        self.location_combo.setItemText(0, _translate("ProjectSetupDialog", "Adelaide, Australia"))
        self.location_combo.setItemText(1, _translate("ProjectSetupDialog", "Brisbane, Australia"))
        self.location_combo.setItemText(2, _translate("ProjectSetupDialog", "Innsbruck, Austria"))
        self.location_combo.setItemText(3, _translate("ProjectSetupDialog", "Melbourne, Australia"))
        self.location_combo.setItemText(4, _translate("ProjectSetupDialog", "Nanjing, China"))
        self.location_combo.setItemText(5, _translate("ProjectSetupDialog", "Perth, Australia"))
        self.location_combo.setItemText(6, _translate("ProjectSetupDialog", "San Francisco, USA"))
        self.location_combo.setItemText(7, _translate("ProjectSetupDialog", "Sydney, Australia"))
        self.location_combo.setItemText(8, _translate("ProjectSetupDialog", "Zurich, Switzerland"))
        self.location_combo.setItemText(9, _translate("ProjectSetupDialog", "Other..."))
        self.region_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.region_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Region</p></body></html>"))
        self.date_spin.setDisplayFormat(_translate("ProjectSetupDialog", "dd/MM/yyyy"))
        self.location_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.location_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">City</p></body></html>"))
        self.aboutuser_lbl.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">About the Modellers</span></p></body></html>"))
        self.otherpersons_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.otherpersons_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Other Persons:</p></body></html>"))
        self.affiliation_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.affiliation_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Affiliation</span></p></body></html>"))
        self.modellername_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.modellername_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lead Modeller</p></body></html>"))
        self.otherpersons_box.setPlainText(_translate("ProjectSetupDialog", "<none>"))
        self.otherpersons_lbl2.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.otherpersons_lbl2.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">(separate names with commas)</span></p></body></html>"))
        self.synopsis_lbl.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Project Synopsis</span></p></body></html>"))
        self.synopsis_descr_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.synopsis_descr_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Provide a description of the key aspects of this project.</span></p></body></html>"))
        self.synopsis_box.setPlainText(_translate("ProjectSetupDialog", "none"))
        self.projectboundary_lbl.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Project Boundary</span></p></body></html>"))
        self.synopsis_descr_lbl_2.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.synopsis_descr_lbl_2.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please specify the shapefile showing the project boundary</p></body></html>"))
        self.projectboundary_lbl2.setText(_translate("ProjectSetupDialog", "Boundary (.shp)"))
        self.projectboundary_browse.setText(_translate("ProjectSetupDialog", "Browse..."))
        self.projectboundary_line.setText(_translate("ProjectSetupDialog", "<none>"))
        self.projectlog_lbl.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Project Logging</span></p></body></html>"))
        self.projectlog_lbl2.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.projectlog_lbl2.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select how you would like the work to be logged.</p></body></html>"))
        self.projectlog_simple.setText(_translate("ProjectSetupDialog", "Simplified Log"))
        self.projectlog_compreh.setText(_translate("ProjectSetupDialog", "Comprehensive"))
        self.path.setText(_translate("ProjectSetupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Path Settings</span></p></body></html>"))
        self.projectpath_lbl.setWhatsThis(_translate("ProjectSetupDialog", "Width of the square cell in the city grid in metres"))
        self.projectpath_lbl.setText(_translate("ProjectSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Path where UrbanBEATS will create the project folder.</p></body></html>"))
        self.projpath_lbl.setText(_translate("ProjectSetupDialog", "Project Path:"))
        self.projpath_button.setText(_translate("ProjectSetupDialog", "Browse..."))
        self.projpath_line.setText(_translate("ProjectSetupDialog", "<none>"))
        self.keepcopy_check.setText(_translate("ProjectSetupDialog", "Keep a copy of data sets wtihin project path"))
        self.setup_tabs.setTabText(self.setup_tabs.indexOf(self.projectinfo_tab), _translate("ProjectSetupDialog", "Project Information"))

import ubeats_rc
