# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addboundarydialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBoundaryDialog(object):
    def setupUi(self, AddBoundaryDialog):
        AddBoundaryDialog.setObjectName("AddBoundaryDialog")
        AddBoundaryDialog.resize(502, 307)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddBoundaryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(AddBoundaryDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/icons8-polygon-96.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.boundaryWizard = QtWidgets.QStackedWidget(AddBoundaryDialog)
        self.boundaryWizard.setObjectName("boundaryWizard")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.step1scrollArea = QtWidgets.QScrollArea(self.page)
        self.step1scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step1scrollArea.setWidgetResizable(True)
        self.step1scrollArea.setObjectName("step1scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 447, 158))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.step1title = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.step1title.setObjectName("step1title")
        self.verticalLayout_2.addWidget(self.step1title)
        self.step1descr = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.step1descr.setObjectName("step1descr")
        self.verticalLayout_2.addWidget(self.step1descr)
        self.step1widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.step1widget.setObjectName("step1widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.step1widget)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.step1_lbl = QtWidgets.QLabel(self.step1widget)
        self.step1_lbl.setObjectName("step1_lbl")
        self.gridLayout_4.addWidget(self.step1_lbl, 1, 0, 1, 1)
        self.projectboundary_browse = QtWidgets.QPushButton(self.step1widget)
        self.projectboundary_browse.setObjectName("projectboundary_browse")
        self.gridLayout_4.addWidget(self.projectboundary_browse, 1, 2, 1, 1)
        self.projectboundary_line = QtWidgets.QLineEdit(self.step1widget)
        self.projectboundary_line.setReadOnly(True)
        self.projectboundary_line.setObjectName("projectboundary_line")
        self.gridLayout_4.addWidget(self.projectboundary_line, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.step1widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.step1scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.step1scrollArea)
        self.footer = QtWidgets.QWidget(self.page)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.step1next = QtWidgets.QPushButton(self.footer)
        self.step1next.setObjectName("step1next")
        self.horizontalLayout_2.addWidget(self.step1next)
        self.verticalLayout_3.addWidget(self.footer)
        self.boundaryWizard.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.step2scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.step2scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step2scrollArea.setWidgetResizable(True)
        self.step2scrollArea.setObjectName("step2scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 447, 158))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.step2title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.step2title.setObjectName("step2title")
        self.verticalLayout_4.addWidget(self.step2title)
        self.step2descr = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.step2descr.setObjectName("step2descr")
        self.verticalLayout_4.addWidget(self.step2descr)
        self.step2widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.step2widget.setObjectName("step2widget")
        self.gridLayout = QtWidgets.QGridLayout(self.step2widget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.boundary_thresh_spin = QtWidgets.QSpinBox(self.step2widget)
        self.boundary_thresh_spin.setMinimum(1)
        self.boundary_thresh_spin.setMaximum(3000)
        self.boundary_thresh_spin.setProperty("value", 3000)
        self.boundary_thresh_spin.setObjectName("boundary_thresh_spin")
        self.gridLayout.addWidget(self.boundary_thresh_spin, 2, 1, 1, 1)
        self.include_thresh_radio = QtWidgets.QRadioButton(self.step2widget)
        self.include_thresh_radio.setObjectName("include_thresh_radio")
        self.gridLayout.addWidget(self.include_thresh_radio, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.include_all_radio = QtWidgets.QRadioButton(self.step2widget)
        self.include_all_radio.setObjectName("include_all_radio")
        self.gridLayout.addWidget(self.include_all_radio, 0, 0, 1, 1)
        self.include_largest_radio = QtWidgets.QRadioButton(self.step2widget)
        self.include_largest_radio.setObjectName("include_largest_radio")
        self.gridLayout.addWidget(self.include_largest_radio, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.step2widget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.step2scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.step2scrollArea)
        self.footer_2 = QtWidgets.QWidget(self.page_3)
        self.footer_2.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_2.setObjectName("footer_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.step2back = QtWidgets.QPushButton(self.footer_2)
        self.step2back.setObjectName("step2back")
        self.horizontalLayout_3.addWidget(self.step2back)
        self.step2next = QtWidgets.QPushButton(self.footer_2)
        self.step2next.setObjectName("step2next")
        self.horizontalLayout_3.addWidget(self.step2next)
        self.verticalLayout_5.addWidget(self.footer_2)
        self.boundaryWizard.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.step3scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.step3scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step3scrollArea.setWidgetResizable(True)
        self.step3scrollArea.setObjectName("step3scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 447, 198))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.step3title = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.step3title.setObjectName("step3title")
        self.verticalLayout_6.addWidget(self.step3title)
        self.step3descr = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.step3descr.setWordWrap(True)
        self.step3descr.setObjectName("step3descr")
        self.verticalLayout_6.addWidget(self.step3descr)
        self.step3widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.step3widget.setObjectName("step3widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.step3widget)
        self.gridLayout_11.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.epsg_line = QtWidgets.QLineEdit(self.step3widget)
        self.epsg_line.setObjectName("epsg_line")
        self.gridLayout_11.addWidget(self.epsg_line, 2, 1, 1, 1)
        self.coords_lbl = QtWidgets.QLabel(self.step3widget)
        self.coords_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.coords_lbl.setObjectName("coords_lbl")
        self.gridLayout_11.addWidget(self.coords_lbl, 1, 0, 1, 1)
        self.epsg_lbl = QtWidgets.QLabel(self.step3widget)
        self.epsg_lbl.setObjectName("epsg_lbl")
        self.gridLayout_11.addWidget(self.epsg_lbl, 2, 0, 1, 1)
        self.coords_combo = QtWidgets.QComboBox(self.step3widget)
        self.coords_combo.setEditable(True)
        self.coords_combo.setObjectName("coords_combo")
        self.coords_combo.addItem("")
        self.gridLayout_11.addWidget(self.coords_combo, 1, 1, 1, 1)
        self.extent_x = QtWidgets.QLabel(self.step3widget)
        self.extent_x.setObjectName("extent_x")
        self.gridLayout_11.addWidget(self.extent_x, 4, 1, 1, 1)
        self.map_extent_lbl = QtWidgets.QLabel(self.step3widget)
        self.map_extent_lbl.setObjectName("map_extent_lbl")
        self.gridLayout_11.addWidget(self.map_extent_lbl, 4, 0, 1, 1)
        self.extent_y = QtWidgets.QLabel(self.step3widget)
        self.extent_y.setObjectName("extent_y")
        self.gridLayout_11.addWidget(self.extent_y, 5, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.step3widget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.step3scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.step3scrollArea)
        self.footer_3 = QtWidgets.QWidget(self.page_2)
        self.footer_3.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_3.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_3.setObjectName("footer_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.footer_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.step3back = QtWidgets.QPushButton(self.footer_3)
        self.step3back.setObjectName("step3back")
        self.horizontalLayout_4.addWidget(self.step3back)
        self.step3next = QtWidgets.QPushButton(self.footer_3)
        self.step3next.setObjectName("step3next")
        self.horizontalLayout_4.addWidget(self.step3next)
        self.verticalLayout_7.addWidget(self.footer_3)
        self.boundaryWizard.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.step4scrollArea = QtWidgets.QScrollArea(self.page_4)
        self.step4scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step4scrollArea.setWidgetResizable(True)
        self.step4scrollArea.setObjectName("step4scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 447, 158))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.step4title = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.step4title.setObjectName("step4title")
        self.verticalLayout_8.addWidget(self.step4title)
        self.step4descr = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.step4descr.setObjectName("step4descr")
        self.verticalLayout_8.addWidget(self.step4descr)
        self.step4widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.step4widget.setObjectName("step4widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.step4widget)
        self.gridLayout_8.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.name_featureattr_combo = QtWidgets.QComboBox(self.step4widget)
        self.name_featureattr_combo.setObjectName("name_featureattr_combo")
        self.name_featureattr_combo.addItem("")
        self.gridLayout_8.addWidget(self.name_featureattr_combo, 2, 1, 1, 1)
        self.name_userdefined_radio = QtWidgets.QRadioButton(self.step4widget)
        self.name_userdefined_radio.setObjectName("name_userdefined_radio")
        self.gridLayout_8.addWidget(self.name_userdefined_radio, 1, 0, 1, 1)
        self.name_userdefined_line = QtWidgets.QLineEdit(self.step4widget)
        self.name_userdefined_line.setReadOnly(False)
        self.name_userdefined_line.setObjectName("name_userdefined_line")
        self.gridLayout_8.addWidget(self.name_userdefined_line, 1, 1, 1, 1)
        self.name_featureattr_radio = QtWidgets.QRadioButton(self.step4widget)
        self.name_featureattr_radio.setObjectName("name_featureattr_radio")
        self.gridLayout_8.addWidget(self.name_featureattr_radio, 2, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.step4widget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.step4scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_9.addWidget(self.step4scrollArea)
        self.footer_4 = QtWidgets.QWidget(self.page_4)
        self.footer_4.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_4.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_4.setObjectName("footer_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.step4back = QtWidgets.QPushButton(self.footer_4)
        self.step4back.setObjectName("step4back")
        self.horizontalLayout_5.addWidget(self.step4back)
        self.step4finish = QtWidgets.QPushButton(self.footer_4)
        self.step4finish.setObjectName("step4finish")
        self.horizontalLayout_5.addWidget(self.step4finish)
        self.verticalLayout_9.addWidget(self.footer_4)
        self.boundaryWizard.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.boundaryWizard)

        self.retranslateUi(AddBoundaryDialog)
        self.boundaryWizard.setCurrentIndex(0)
        self.coords_combo.setCurrentIndex(0)
        self.step4finish.clicked.connect(AddBoundaryDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(AddBoundaryDialog)

    def retranslateUi(self, AddBoundaryDialog):
        _translate = QtCore.QCoreApplication.translate
        AddBoundaryDialog.setWindowTitle(_translate("AddBoundaryDialog", "Setup New Project"))
        self.subtitle.setText(_translate("AddBoundaryDialog", "Add simulation boundaries to the project"))
        self.title.setText(_translate("AddBoundaryDialog", "Add Simulation Boundary"))
        self.step1title.setText(_translate("AddBoundaryDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 1 - Select Boundary File</span></p></body></html>"))
        self.step1descr.setWhatsThis(_translate("AddBoundaryDialog", "Width of the square cell in the city grid in metres"))
        self.step1descr.setText(_translate("AddBoundaryDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please specify the shapefile containing simulation boundary polygon</p></body></html>"))
        self.step1_lbl.setText(_translate("AddBoundaryDialog", "Boundary (.shp)"))
        self.projectboundary_browse.setText(_translate("AddBoundaryDialog", "Browse..."))
        self.projectboundary_line.setText(_translate("AddBoundaryDialog", "(none)"))
        self.step1next.setText(_translate("AddBoundaryDialog", "Next >"))
        self.step2title.setText(_translate("AddBoundaryDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 2 - Multiple Features</span></p></body></html>"))
        self.step2descr.setWhatsThis(_translate("AddBoundaryDialog", "Width of the square cell in the city grid in metres"))
        self.step2descr.setText(_translate("AddBoundaryDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If the map has multiple features, you will need to determine which features to include</p></body></html>"))
        self.boundary_thresh_spin.setSuffix(_translate("AddBoundaryDialog", " sq.km"))
        self.include_thresh_radio.setText(_translate("AddBoundaryDialog", "Include only features above threshold area"))
        self.include_all_radio.setText(_translate("AddBoundaryDialog", "Include all features"))
        self.include_largest_radio.setText(_translate("AddBoundaryDialog", "Include only the largest feature (by area)"))
        self.step2back.setText(_translate("AddBoundaryDialog", "< Back"))
        self.step2next.setText(_translate("AddBoundaryDialog", "Next >"))
        self.step3title.setText(_translate("AddBoundaryDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 3 - Define Boundary Coordinate System</span></p></body></html>"))
        self.step3descr.setWhatsThis(_translate("AddBoundaryDialog", "Width of the square cell in the city grid in metres"))
        self.step3descr.setText(_translate("AddBoundaryDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Define the coordinate system for the selected file.</p></body></html>"))
        self.coords_lbl.setText(_translate("AddBoundaryDialog", "Default Coordinate System:"))
        self.epsg_lbl.setText(_translate("AddBoundaryDialog", "EPSG Code:"))
        self.coords_combo.setItemText(0, _translate("AddBoundaryDialog", "(select coordinate system)"))
        self.extent_x.setText(_translate("AddBoundaryDialog", "Left:   | Right:   "))
        self.map_extent_lbl.setText(_translate("AddBoundaryDialog", "Current Map Extent:"))
        self.extent_y.setText(_translate("AddBoundaryDialog", "Top:   | Bottom:   "))
        self.step3back.setText(_translate("AddBoundaryDialog", "< Back"))
        self.step3next.setText(_translate("AddBoundaryDialog", "Next >"))
        self.step4title.setText(_translate("AddBoundaryDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 4 - Set Boundary Name(s)</span></p></body></html>"))
        self.step4descr.setWhatsThis(_translate("AddBoundaryDialog", "Width of the square cell in the city grid in metres"))
        self.step4descr.setText(_translate("AddBoundaryDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Setup a \'naming convention\' or define name based on feature attributes</p></body></html>"))
        self.name_featureattr_combo.setItemText(0, _translate("AddBoundaryDialog", "(select attribute)"))
        self.name_userdefined_radio.setText(_translate("AddBoundaryDialog", "User-defined"))
        self.name_userdefined_line.setText(_translate("AddBoundaryDialog", "(none)"))
        self.name_featureattr_radio.setText(_translate("AddBoundaryDialog", "Based on feature attributes"))
        self.step4back.setText(_translate("AddBoundaryDialog", "< Back"))
        self.step4finish.setText(_translate("AddBoundaryDialog", "Finish"))
from . import ubeats_rc
