# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddatadialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDataDialog(object):
    def setupUi(self, AddDataDialog):
        AddDataDialog.setObjectName("AddDataDialog")
        AddDataDialog.resize(409, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddDataDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(AddDataDialog)
        self.title_widget.setObjectName("title_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.title_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_logo = QtWidgets.QLabel(self.title_widget)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/add-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_3.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_3.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.title_widget)
        self.datatype_widget = QtWidgets.QWidget(AddDataDialog)
        self.datatype_widget.setObjectName("datatype_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.datatype_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.datatype_lbl = QtWidgets.QLabel(self.datatype_widget)
        self.datatype_lbl.setObjectName("datatype_lbl")
        self.horizontalLayout_3.addWidget(self.datatype_lbl)
        self.spatial_radio = QtWidgets.QRadioButton(self.datatype_widget)
        self.spatial_radio.setObjectName("spatial_radio")
        self.horizontalLayout_3.addWidget(self.spatial_radio)
        self.temporal_radio = QtWidgets.QRadioButton(self.datatype_widget)
        self.temporal_radio.setObjectName("temporal_radio")
        self.horizontalLayout_3.addWidget(self.temporal_radio)
        self.qualitative_radio = QtWidgets.QRadioButton(self.datatype_widget)
        self.qualitative_radio.setObjectName("qualitative_radio")
        self.horizontalLayout_3.addWidget(self.qualitative_radio)
        self.verticalLayout.addWidget(self.datatype_widget)
        self.adddatafile_widget = QtWidgets.QWidget(AddDataDialog)
        self.adddatafile_widget.setObjectName("adddatafile_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.adddatafile_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datafile_lbl = QtWidgets.QLabel(self.adddatafile_widget)
        self.datafile_lbl.setObjectName("datafile_lbl")
        self.horizontalLayout.addWidget(self.datafile_lbl)
        self.databox = QtWidgets.QLineEdit(self.adddatafile_widget)
        self.databox.setEnabled(True)
        self.databox.setReadOnly(True)
        self.databox.setObjectName("databox")
        self.horizontalLayout.addWidget(self.databox)
        self.adddatabrowse = QtWidgets.QToolButton(self.adddatafile_widget)
        self.adddatabrowse.setObjectName("adddatabrowse")
        self.horizontalLayout.addWidget(self.adddatabrowse)
        self.verticalLayout.addWidget(self.adddatafile_widget)
        self.data_classification_lbl = QtWidgets.QLabel(AddDataDialog)
        self.data_classification_lbl.setObjectName("data_classification_lbl")
        self.verticalLayout.addWidget(self.data_classification_lbl)
        self.datacat_widget = QtWidgets.QWidget(AddDataDialog)
        self.datacat_widget.setObjectName("datacat_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.datacat_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.datacat_lbl = QtWidgets.QLabel(self.datacat_widget)
        self.datacat_lbl.setMinimumSize(QtCore.QSize(200, 0))
        self.datacat_lbl.setObjectName("datacat_lbl")
        self.gridLayout_2.addWidget(self.datacat_lbl, 0, 0, 1, 1)
        self.datacatsub_combo = QtWidgets.QComboBox(self.datacat_widget)
        self.datacatsub_combo.setEnabled(False)
        self.datacatsub_combo.setObjectName("datacatsub_combo")
        self.datacatsub_combo.addItem("")
        self.gridLayout_2.addWidget(self.datacatsub_combo, 1, 2, 1, 1)
        self.datacat_combo = QtWidgets.QComboBox(self.datacat_widget)
        self.datacat_combo.setObjectName("datacat_combo")
        self.datacat_combo.addItem("")
        self.gridLayout_2.addWidget(self.datacat_combo, 0, 2, 1, 1)
        self.datacatsub_lbl = QtWidgets.QLabel(self.datacat_widget)
        self.datacatsub_lbl.setMinimumSize(QtCore.QSize(200, 0))
        self.datacatsub_lbl.setObjectName("datacatsub_lbl")
        self.gridLayout_2.addWidget(self.datacatsub_lbl, 1, 0, 1, 1)
        self.spatial_units = QtWidgets.QLabel(self.datacat_widget)
        self.spatial_units.setMinimumSize(QtCore.QSize(200, 0))
        self.spatial_units.setObjectName("spatial_units")
        self.gridLayout_2.addWidget(self.spatial_units, 2, 0, 1, 1)
        self.spatial_units_combo = QtWidgets.QComboBox(self.datacat_widget)
        self.spatial_units_combo.setEnabled(False)
        self.spatial_units_combo.setObjectName("spatial_units_combo")
        self.spatial_units_combo.addItem("")
        self.gridLayout_2.addWidget(self.spatial_units_combo, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.datacat_widget)
        self.notes_title = QtWidgets.QLabel(AddDataDialog)
        self.notes_title.setObjectName("notes_title")
        self.verticalLayout.addWidget(self.notes_title)
        self.notes_box = QtWidgets.QPlainTextEdit(AddDataDialog)
        self.notes_box.setMinimumSize(QtCore.QSize(0, 100))
        self.notes_box.setDocumentTitle("")
        self.notes_box.setObjectName("notes_box")
        self.verticalLayout.addWidget(self.notes_box)
        self.footer = QtWidgets.QWidget(AddDataDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.adddata_button = QtWidgets.QToolButton(self.footer)
        self.adddata_button.setMinimumSize(QtCore.QSize(75, 20))
        self.adddata_button.setObjectName("adddata_button")
        self.horizontalLayout_2.addWidget(self.adddata_button)
        self.cleardata_button = QtWidgets.QToolButton(self.footer)
        self.cleardata_button.setMinimumSize(QtCore.QSize(75, 0))
        self.cleardata_button.setObjectName("cleardata_button")
        self.horizontalLayout_2.addWidget(self.cleardata_button)
        self.done_button = QtWidgets.QPushButton(self.footer)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(AddDataDialog)
        self.datacatsub_combo.setCurrentIndex(0)
        self.datacat_combo.setCurrentIndex(0)
        self.spatial_units_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddDataDialog)
        AddDataDialog.setTabOrder(self.databox, self.adddatabrowse)
        AddDataDialog.setTabOrder(self.adddatabrowse, self.spatial_radio)
        AddDataDialog.setTabOrder(self.spatial_radio, self.temporal_radio)
        AddDataDialog.setTabOrder(self.temporal_radio, self.qualitative_radio)
        AddDataDialog.setTabOrder(self.qualitative_radio, self.datacat_combo)
        AddDataDialog.setTabOrder(self.datacat_combo, self.datacatsub_combo)
        AddDataDialog.setTabOrder(self.datacatsub_combo, self.notes_box)
        AddDataDialog.setTabOrder(self.notes_box, self.adddata_button)
        AddDataDialog.setTabOrder(self.adddata_button, self.cleardata_button)
        AddDataDialog.setTabOrder(self.cleardata_button, self.done_button)

    def retranslateUi(self, AddDataDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDataDialog.setWindowTitle(_translate("AddDataDialog", "Add Data..."))
        self.title.setText(_translate("AddDataDialog", "Add Data"))
        self.subtitle.setText(_translate("AddDataDialog", "Add GIS or Climate Data to the Project"))
        self.datatype_lbl.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.datatype_lbl.setText(_translate("AddDataDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Data Type:   </span></p></body></html>"))
        self.spatial_radio.setText(_translate("AddDataDialog", "Spatial"))
        self.temporal_radio.setText(_translate("AddDataDialog", "Temporal"))
        self.qualitative_radio.setText(_translate("AddDataDialog", "Qualitative"))
        self.datafile_lbl.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.datafile_lbl.setText(_translate("AddDataDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Data File</span></p></body></html>"))
        self.databox.setText(_translate("AddDataDialog", "(none)"))
        self.adddatabrowse.setText(_translate("AddDataDialog", "Browse..."))
        self.data_classification_lbl.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.data_classification_lbl.setText(_translate("AddDataDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Classification</span></p></body></html>"))
        self.datacat_lbl.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.datacat_lbl.setText(_translate("AddDataDialog", "Data Category:"))
        self.datacatsub_combo.setItemText(0, _translate("AddDataDialog", "(undefined)"))
        self.datacat_combo.setItemText(0, _translate("AddDataDialog", "(undefined)"))
        self.datacatsub_lbl.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.datacatsub_lbl.setText(_translate("AddDataDialog", "Data Sub-Type:"))
        self.spatial_units.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.spatial_units.setText(_translate("AddDataDialog", "<html><head/><body><p>Spatial Units (<span style=\" font-style:italic;\">maps only</span>):</p></body></html>"))
        self.spatial_units_combo.setItemText(0, _translate("AddDataDialog", "metres"))
        self.notes_title.setWhatsThis(_translate("AddDataDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.notes_title.setText(_translate("AddDataDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Notes</span></p></body></html>"))
        self.notes_box.setPlainText(_translate("AddDataDialog", "none"))
        self.adddata_button.setText(_translate("AddDataDialog", "Add Data"))
        self.cleardata_button.setText(_translate("AddDataDialog", "Clear"))
        self.done_button.setText(_translate("AddDataDialog", "Done"))
import ubeats_rc
