# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addlocationdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddLocationDialog(object):
    def setupUi(self, AddLocationDialog):
        AddLocationDialog.setObjectName("AddLocationDialog")
        AddLocationDialog.resize(406, 307)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddLocationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(AddLocationDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/location.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.step1scrollArea = QtWidgets.QScrollArea(AddLocationDialog)
        self.step1scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step1scrollArea.setWidgetResizable(True)
        self.step1scrollArea.setObjectName("step1scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 369, 176))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.step1widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.step1widget.setObjectName("step1widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.step1widget)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loclong_line = QtWidgets.QLineEdit(self.step1widget)
        self.loclong_line.setReadOnly(False)
        self.loclong_line.setObjectName("loclong_line")
        self.gridLayout_4.addWidget(self.loclong_line, 1, 3, 1, 1)
        self.locname_line = QtWidgets.QLineEdit(self.step1widget)
        self.locname_line.setReadOnly(False)
        self.locname_line.setObjectName("locname_line")
        self.gridLayout_4.addWidget(self.locname_line, 0, 1, 1, 3)
        self.locname_lbl = QtWidgets.QLabel(self.step1widget)
        self.locname_lbl.setObjectName("locname_lbl")
        self.gridLayout_4.addWidget(self.locname_lbl, 0, 0, 1, 1)
        self.loclat_lbl = QtWidgets.QLabel(self.step1widget)
        self.loclat_lbl.setObjectName("loclat_lbl")
        self.gridLayout_4.addWidget(self.loclat_lbl, 1, 0, 1, 1)
        self.loclat_line = QtWidgets.QLineEdit(self.step1widget)
        self.loclat_line.setReadOnly(False)
        self.loclat_line.setObjectName("loclat_line")
        self.gridLayout_4.addWidget(self.loclat_line, 1, 1, 1, 1)
        self.loclong_lbl = QtWidgets.QLabel(self.step1widget)
        self.loclong_lbl.setObjectName("loclong_lbl")
        self.gridLayout_4.addWidget(self.loclong_lbl, 1, 2, 1, 1)
        self.locdescr_lbl = QtWidgets.QLabel(self.step1widget)
        self.locdescr_lbl.setObjectName("locdescr_lbl")
        self.gridLayout_4.addWidget(self.locdescr_lbl, 2, 0, 1, 1)
        self.locdescr_textedit = QtWidgets.QTextEdit(self.step1widget)
        self.locdescr_textedit.setObjectName("locdescr_textedit")
        self.gridLayout_4.addWidget(self.locdescr_textedit, 2, 1, 1, 3)
        self.verticalLayout_2.addWidget(self.step1widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.step1scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.step1scrollArea)
        self.footer = QtWidgets.QWidget(AddLocationDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.add_button = QtWidgets.QPushButton(self.footer)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_5.addWidget(self.add_button)
        self.cancel_button = QtWidgets.QPushButton(self.footer)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_5.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(AddLocationDialog)
        self.add_button.clicked.connect(AddLocationDialog.accept)
        self.cancel_button.clicked.connect(AddLocationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddLocationDialog)
        AddLocationDialog.setTabOrder(self.step1scrollArea, self.locname_line)
        AddLocationDialog.setTabOrder(self.locname_line, self.loclat_line)
        AddLocationDialog.setTabOrder(self.loclat_line, self.loclong_line)
        AddLocationDialog.setTabOrder(self.loclong_line, self.locdescr_textedit)
        AddLocationDialog.setTabOrder(self.locdescr_textedit, self.add_button)
        AddLocationDialog.setTabOrder(self.add_button, self.cancel_button)

    def retranslateUi(self, AddLocationDialog):
        _translate = QtCore.QCoreApplication.translate
        AddLocationDialog.setWindowTitle(_translate("AddLocationDialog", "Setup New Project"))
        self.subtitle.setText(_translate("AddLocationDialog", "Use this location to define spatial relationships or custom boundaries"))
        self.title.setText(_translate("AddLocationDialog", "Add a Key Location to the Project"))
        self.loclong_line.setText(_translate("AddLocationDialog", "(none)"))
        self.locname_line.setText(_translate("AddLocationDialog", "(none)"))
        self.locname_lbl.setText(_translate("AddLocationDialog", "Name:"))
        self.loclat_lbl.setText(_translate("AddLocationDialog", "Latitude:"))
        self.loclat_line.setText(_translate("AddLocationDialog", "(none)"))
        self.loclong_lbl.setText(_translate("AddLocationDialog", "Longitude:"))
        self.locdescr_lbl.setText(_translate("AddLocationDialog", "Description:"))
        self.add_button.setText(_translate("AddLocationDialog", "Add"))
        self.cancel_button.setText(_translate("AddLocationDialog", "Cancel"))
from . import ubeats_rc
