# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addshapedialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddShapeDialog(object):
    def setupUi(self, AddShapeDialog):
        AddShapeDialog.setObjectName("AddShapeDialog")
        AddShapeDialog.resize(502, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddShapeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(AddShapeDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/custom_shape.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.shape_stack = QtWidgets.QStackedWidget(AddShapeDialog)
        self.shape_stack.setObjectName("shape_stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.step1scrollArea = QtWidgets.QScrollArea(self.page)
        self.step1scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step1scrollArea.setWidgetResizable(True)
        self.step1scrollArea.setObjectName("step1scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 447, 234))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.step1title = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.step1title.setObjectName("step1title")
        self.verticalLayout_2.addWidget(self.step1title)
        self.step1descr = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.step1descr.setWordWrap(True)
        self.step1descr.setObjectName("step1descr")
        self.verticalLayout_2.addWidget(self.step1descr)
        self.step1widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.step1widget.setObjectName("step1widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.step1widget)
        self.gridLayout_11.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.loc_name_combo = QtWidgets.QComboBox(self.step1widget)
        self.loc_name_combo.setObjectName("loc_name_combo")
        self.loc_name_combo.addItem("")
        self.gridLayout_11.addWidget(self.loc_name_combo, 0, 1, 1, 2)
        self.shape_name_line = QtWidgets.QLineEdit(self.step1widget)
        self.shape_name_line.setObjectName("shape_name_line")
        self.gridLayout_11.addWidget(self.shape_name_line, 1, 1, 1, 1)
        self.epsg_lbl = QtWidgets.QLabel(self.step1widget)
        self.epsg_lbl.setObjectName("epsg_lbl")
        self.gridLayout_11.addWidget(self.epsg_lbl, 4, 0, 1, 1)
        self.shape_name_lbl = QtWidgets.QLabel(self.step1widget)
        self.shape_name_lbl.setObjectName("shape_name_lbl")
        self.gridLayout_11.addWidget(self.shape_name_lbl, 1, 0, 1, 1)
        self.coords_combo = QtWidgets.QComboBox(self.step1widget)
        self.coords_combo.setEditable(True)
        self.coords_combo.setObjectName("coords_combo")
        self.coords_combo.addItem("")
        self.gridLayout_11.addWidget(self.coords_combo, 3, 1, 1, 2)
        self.epsg_line = QtWidgets.QLineEdit(self.step1widget)
        self.epsg_line.setObjectName("epsg_line")
        self.gridLayout_11.addWidget(self.epsg_line, 4, 1, 1, 2)
        self.loc_name_lbl = QtWidgets.QLabel(self.step1widget)
        self.loc_name_lbl.setObjectName("loc_name_lbl")
        self.gridLayout_11.addWidget(self.loc_name_lbl, 0, 0, 1, 1)
        self.coords_lbl = QtWidgets.QLabel(self.step1widget)
        self.coords_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.coords_lbl.setObjectName("coords_lbl")
        self.gridLayout_11.addWidget(self.coords_lbl, 3, 0, 1, 1)
        self.name_loc_same_check = QtWidgets.QCheckBox(self.step1widget)
        self.name_loc_same_check.setObjectName("name_loc_same_check")
        self.gridLayout_11.addWidget(self.name_loc_same_check, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.step1widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_11.addWidget(self.line, 2, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.step1widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.step1scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.step1scrollArea)
        self.footer = QtWidgets.QWidget(self.page)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.next_button = QtWidgets.QPushButton(self.footer)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        self.verticalLayout_3.addWidget(self.footer)
        self.shape_stack.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.step2scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.step2scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.step2scrollArea.setWidgetResizable(True)
        self.step2scrollArea.setObjectName("step2scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 447, 220))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.step2title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.step2title.setObjectName("step2title")
        self.verticalLayout_4.addWidget(self.step2title)
        self.step2descr = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.step2descr.setObjectName("step2descr")
        self.verticalLayout_4.addWidget(self.step2descr)
        self.step2widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.step2widget.setObjectName("step2widget")
        self.gridLayout = QtWidgets.QGridLayout(self.step2widget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.rectangle_img = QtWidgets.QLabel(self.step2widget)
        self.rectangle_img.setMinimumSize(QtCore.QSize(0, 30))
        self.rectangle_img.setMaximumSize(QtCore.QSize(30, 30))
        self.rectangle_img.setText("")
        self.rectangle_img.setPixmap(QtGui.QPixmap(":/icons/rectangle.png"))
        self.rectangle_img.setScaledContents(True)
        self.rectangle_img.setObjectName("rectangle_img")
        self.gridLayout.addWidget(self.rectangle_img, 2, 0, 1, 1)
        self.rect_h_lbl = QtWidgets.QLabel(self.step2widget)
        self.rect_h_lbl.setObjectName("rect_h_lbl")
        self.gridLayout.addWidget(self.rect_h_lbl, 5, 0, 1, 1)
        self.hex_img = QtWidgets.QLabel(self.step2widget)
        self.hex_img.setMinimumSize(QtCore.QSize(30, 30))
        self.hex_img.setMaximumSize(QtCore.QSize(30, 30))
        self.hex_img.setText("")
        self.hex_img.setPixmap(QtGui.QPixmap(":/icons/hexagon.png"))
        self.hex_img.setScaledContents(True)
        self.hex_img.setObjectName("hex_img")
        self.gridLayout.addWidget(self.hex_img, 2, 4, 1, 1)
        self.hex_edge_lbl = QtWidgets.QLabel(self.step2widget)
        self.hex_edge_lbl.setObjectName("hex_edge_lbl")
        self.gridLayout.addWidget(self.hex_edge_lbl, 5, 4, 1, 1)
        self.circle_img = QtWidgets.QLabel(self.step2widget)
        self.circle_img.setMinimumSize(QtCore.QSize(30, 30))
        self.circle_img.setMaximumSize(QtCore.QSize(30, 30))
        self.circle_img.setText("")
        self.circle_img.setPixmap(QtGui.QPixmap(":/icons/circle.png"))
        self.circle_img.setScaledContents(True)
        self.circle_img.setObjectName("circle_img")
        self.gridLayout.addWidget(self.circle_img, 2, 2, 1, 1)
        self.hex_orient_lbl = QtWidgets.QLabel(self.step2widget)
        self.hex_orient_lbl.setObjectName("hex_orient_lbl")
        self.gridLayout.addWidget(self.hex_orient_lbl, 4, 4, 1, 1)
        self.circ_radius_lbl = QtWidgets.QLabel(self.step2widget)
        self.circ_radius_lbl.setObjectName("circ_radius_lbl")
        self.gridLayout.addWidget(self.circ_radius_lbl, 4, 2, 1, 1)
        self.hex_orient_combo = QtWidgets.QComboBox(self.step2widget)
        self.hex_orient_combo.setObjectName("hex_orient_combo")
        self.hex_orient_combo.addItem("")
        self.hex_orient_combo.addItem("")
        self.gridLayout.addWidget(self.hex_orient_combo, 4, 5, 1, 1)
        self.rectangle_radio = QtWidgets.QRadioButton(self.step2widget)
        self.rectangle_radio.setObjectName("rectangle_radio")
        self.gridLayout.addWidget(self.rectangle_radio, 2, 1, 1, 1)
        self.rect_w_lbl = QtWidgets.QLabel(self.step2widget)
        self.rect_w_lbl.setObjectName("rect_w_lbl")
        self.gridLayout.addWidget(self.rect_w_lbl, 4, 0, 1, 1)
        self.circle_radio = QtWidgets.QRadioButton(self.step2widget)
        self.circle_radio.setObjectName("circle_radio")
        self.gridLayout.addWidget(self.circle_radio, 2, 3, 1, 1)
        self.hex_radio = QtWidgets.QRadioButton(self.step2widget)
        self.hex_radio.setObjectName("hex_radio")
        self.gridLayout.addWidget(self.hex_radio, 2, 5, 1, 1)
        self.rect_w_line = QtWidgets.QLineEdit(self.step2widget)
        self.rect_w_line.setObjectName("rect_w_line")
        self.gridLayout.addWidget(self.rect_w_line, 4, 1, 1, 1)
        self.rect_h_line = QtWidgets.QLineEdit(self.step2widget)
        self.rect_h_line.setObjectName("rect_h_line")
        self.gridLayout.addWidget(self.rect_h_line, 5, 1, 1, 1)
        self.circ_radius_line = QtWidgets.QLineEdit(self.step2widget)
        self.circ_radius_line.setObjectName("circ_radius_line")
        self.gridLayout.addWidget(self.circ_radius_line, 4, 3, 1, 1)
        self.hex_edge_line = QtWidgets.QLineEdit(self.step2widget)
        self.hex_edge_line.setObjectName("hex_edge_line")
        self.gridLayout.addWidget(self.hex_edge_line, 5, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.step2widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.step2scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.step2scrollArea)
        self.footer2 = QtWidgets.QWidget(self.page_3)
        self.footer2.setMinimumSize(QtCore.QSize(0, 38))
        self.footer2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer2.setObjectName("footer2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.back_button = QtWidgets.QPushButton(self.footer2)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_3.addWidget(self.back_button)
        self.finish_button = QtWidgets.QPushButton(self.footer2)
        self.finish_button.setObjectName("finish_button")
        self.horizontalLayout_3.addWidget(self.finish_button)
        self.verticalLayout_5.addWidget(self.footer2)
        self.shape_stack.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.shape_stack)

        self.retranslateUi(AddShapeDialog)
        self.shape_stack.setCurrentIndex(0)
        self.coords_combo.setCurrentIndex(0)
        self.finish_button.clicked.connect(AddShapeDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(AddShapeDialog)
        AddShapeDialog.setTabOrder(self.step1scrollArea, self.loc_name_combo)
        AddShapeDialog.setTabOrder(self.loc_name_combo, self.shape_name_line)
        AddShapeDialog.setTabOrder(self.shape_name_line, self.name_loc_same_check)
        AddShapeDialog.setTabOrder(self.name_loc_same_check, self.coords_combo)
        AddShapeDialog.setTabOrder(self.coords_combo, self.epsg_line)
        AddShapeDialog.setTabOrder(self.epsg_line, self.next_button)
        AddShapeDialog.setTabOrder(self.next_button, self.step2scrollArea)
        AddShapeDialog.setTabOrder(self.step2scrollArea, self.rectangle_radio)
        AddShapeDialog.setTabOrder(self.rectangle_radio, self.rect_w_line)
        AddShapeDialog.setTabOrder(self.rect_w_line, self.rect_h_line)
        AddShapeDialog.setTabOrder(self.rect_h_line, self.circle_radio)
        AddShapeDialog.setTabOrder(self.circle_radio, self.circ_radius_line)
        AddShapeDialog.setTabOrder(self.circ_radius_line, self.hex_radio)
        AddShapeDialog.setTabOrder(self.hex_radio, self.hex_orient_combo)
        AddShapeDialog.setTabOrder(self.hex_orient_combo, self.hex_edge_line)
        AddShapeDialog.setTabOrder(self.hex_edge_line, self.back_button)
        AddShapeDialog.setTabOrder(self.back_button, self.finish_button)

    def retranslateUi(self, AddShapeDialog):
        _translate = QtCore.QCoreApplication.translate
        AddShapeDialog.setWindowTitle(_translate("AddShapeDialog", "Setup New Project"))
        self.subtitle.setText(_translate("AddShapeDialog", "Define a rectangular, circular or hexagonal simulation boundary"))
        self.title.setText(_translate("AddShapeDialog", "Define Basic Shape Boundary"))
        self.step1title.setText(_translate("AddShapeDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 1 - Select a location, define name and a coordinate system</span></p></body></html>"))
        self.step1descr.setWhatsThis(_translate("AddShapeDialog", "Width of the square cell in the city grid in metres"))
        self.step1descr.setText(_translate("AddShapeDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select from loaded project locations (i.e. points) and define a projection to use for this boundary in the simulation (note that this projection should match all input data maps).</p></body></html>"))
        self.loc_name_combo.setItemText(0, _translate("AddShapeDialog", "(select a project location as centroid)"))
        self.epsg_lbl.setText(_translate("AddShapeDialog", "EPSG Code:"))
        self.shape_name_lbl.setText(_translate("AddShapeDialog", "Boundary Name:"))
        self.coords_combo.setItemText(0, _translate("AddShapeDialog", "(select coordinate system)"))
        self.loc_name_lbl.setText(_translate("AddShapeDialog", "Defined Project Location:"))
        self.coords_lbl.setText(_translate("AddShapeDialog", "Default Coordinate System:"))
        self.name_loc_same_check.setText(_translate("AddShapeDialog", "Same as location"))
        self.next_button.setText(_translate("AddShapeDialog", "Next >"))
        self.step2title.setText(_translate("AddShapeDialog", "<html><head/><body><p><span style=\" font-weight:600;\">STEP 2 - Define Boundary Shape</span></p></body></html>"))
        self.step2descr.setWhatsThis(_translate("AddShapeDialog", "Width of the square cell in the city grid in metres"))
        self.step2descr.setText(_translate("AddShapeDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select from a rectangle, circle or hexagon and specify dimensions [km]</p></body></html>"))
        self.rect_h_lbl.setText(_translate("AddShapeDialog", "H"))
        self.hex_edge_lbl.setText(_translate("AddShapeDialog", "Edge"))
        self.hex_orient_lbl.setText(_translate("AddShapeDialog", "Direction"))
        self.circ_radius_lbl.setText(_translate("AddShapeDialog", "Radius"))
        self.hex_orient_combo.setItemText(0, _translate("AddShapeDialog", "North-South"))
        self.hex_orient_combo.setItemText(1, _translate("AddShapeDialog", "East-West"))
        self.rectangle_radio.setText(_translate("AddShapeDialog", "Rectangle"))
        self.rect_w_lbl.setText(_translate("AddShapeDialog", "W"))
        self.circle_radio.setText(_translate("AddShapeDialog", "Circle"))
        self.hex_radio.setText(_translate("AddShapeDialog", "Hexagon"))
        self.back_button.setText(_translate("AddShapeDialog", "< Back"))
        self.finish_button.setText(_translate("AddShapeDialog", "Finish"))
from . import ubeats_rc
