# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogDialog(object):
    def setupUi(self, LogDialog):
        LogDialog.setObjectName("LogDialog")
        LogDialog.resize(569, 392)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(LogDialog)
        self.header.setObjectName("header")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/Clipboard-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_2.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        self.title.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_2.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.log_widget = QtWidgets.QTabWidget(LogDialog)
        self.log_widget.setObjectName("log_widget")
        self.session_tab = QtWidgets.QWidget()
        self.session_tab.setObjectName("session_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.session_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.session_box = QtWidgets.QPlainTextEdit(self.session_tab)
        self.session_box.setMinimumSize(QtCore.QSize(0, 100))
        self.session_box.setDocumentTitle("")
        self.session_box.setReadOnly(True)
        self.session_box.setObjectName("session_box")
        self.verticalLayout_2.addWidget(self.session_box)
        self.log_widget.addTab(self.session_tab, "")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.history_box = QtWidgets.QPlainTextEdit(self.history_tab)
        self.history_box.setMinimumSize(QtCore.QSize(0, 100))
        self.history_box.setDocumentTitle("")
        self.history_box.setObjectName("history_box")
        self.verticalLayout_3.addWidget(self.history_box)
        self.log_widget.addTab(self.history_tab, "")
        self.verticalLayout.addWidget(self.log_widget)
        self.footer = QtWidgets.QWidget(LogDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.export_log = QtWidgets.QToolButton(self.footer)
        self.export_log.setMinimumSize(QtCore.QSize(75, 20))
        self.export_log.setObjectName("export_log")
        self.horizontalLayout_2.addWidget(self.export_log)
        self.clear_log = QtWidgets.QToolButton(self.footer)
        self.clear_log.setMinimumSize(QtCore.QSize(75, 0))
        self.clear_log.setObjectName("clear_log")
        self.horizontalLayout_2.addWidget(self.clear_log)
        self.done_button = QtWidgets.QPushButton(self.footer)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(LogDialog)
        self.log_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LogDialog)
        LogDialog.setTabOrder(self.log_widget, self.session_box)
        LogDialog.setTabOrder(self.session_box, self.history_box)
        LogDialog.setTabOrder(self.history_box, self.export_log)
        LogDialog.setTabOrder(self.export_log, self.clear_log)
        LogDialog.setTabOrder(self.clear_log, self.done_button)

    def retranslateUi(self, LogDialog):
        _translate = QtCore.QCoreApplication.translate
        LogDialog.setWindowTitle(_translate("LogDialog", "Project Log"))
        self.title.setText(_translate("LogDialog", "Project Log"))
        self.subtitle.setText(_translate("LogDialog", "View session or entire history log"))
        self.session_box.setPlainText(_translate("LogDialog", "<none>"))
        self.log_widget.setTabText(self.log_widget.indexOf(self.session_tab), _translate("LogDialog", "Log for this Session"))
        self.history_box.setPlainText(_translate("LogDialog", "<none>"))
        self.log_widget.setTabText(self.log_widget.indexOf(self.history_tab), _translate("LogDialog", "Project History Log"))
        self.export_log.setText(_translate("LogDialog", "Export"))
        self.clear_log.setText(_translate("LogDialog", "Clear"))
        self.done_button.setText(_translate("LogDialog", "Done"))
from . import ubeats_rc
