# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapexportoptions.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapExportDialog(object):
    def setupUi(self, MapExportDialog):
        MapExportDialog.setObjectName("MapExportDialog")
        MapExportDialog.resize(518, 483)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MapExportDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MapExportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(MapExportDialog)
        self.title_widget.setObjectName("title_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.title_widget)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_logo = QtWidgets.QLabel(self.title_widget)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/maps-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_3.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_3.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.title_widget)
        self.mapexport_widget = QtWidgets.QTabWidget(MapExportDialog)
        self.mapexport_widget.setObjectName("mapexport_widget")
        self.maps_tab = QtWidgets.QWidget()
        self.maps_tab.setObjectName("maps_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.maps_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.maps_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 375))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.selectmaps_title = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.selectmaps_title.setObjectName("selectmaps_title")
        self.verticalLayout_5.addWidget(self.selectmaps_title)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(6, 0, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.maps_suitability = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_suitability.setObjectName("maps_suitability")
        self.gridLayout_2.addWidget(self.maps_suitability, 12, 0, 1, 1)
        self.maps_floodrisk = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_floodrisk.setObjectName("maps_floodrisk")
        self.gridLayout_2.addWidget(self.maps_floodrisk, 8, 1, 1, 1)
        self.maps_service = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_service.setObjectName("maps_service")
        self.gridLayout_2.addWidget(self.maps_service, 13, 1, 1, 1)
        self.maps_planned = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_planned.setObjectName("maps_planned")
        self.gridLayout_2.addWidget(self.maps_planned, 13, 0, 1, 1)
        self.spatialmapping_cat = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spatialmapping_cat.setObjectName("spatialmapping_cat")
        self.gridLayout_2.addWidget(self.spatialmapping_cat, 7, 0, 1, 1)
        self.maps_blocks = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_blocks.setObjectName("maps_blocks")
        self.gridLayout_2.addWidget(self.maps_blocks, 2, 0, 1, 1)
        self.maps_patches = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_patches.setObjectName("maps_patches")
        self.gridLayout_2.addWidget(self.maps_patches, 4, 0, 1, 1)
        self.spatialrep_cat = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spatialrep_cat.setObjectName("spatialrep_cat")
        self.gridLayout_2.addWidget(self.spatialrep_cat, 1, 0, 1, 1)
        self.infrastructure_cat = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.infrastructure_cat.setObjectName("infrastructure_cat")
        self.gridLayout_2.addWidget(self.infrastructure_cat, 11, 0, 1, 1)
        self.maps_boundaries = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_boundaries.setObjectName("maps_boundaries")
        self.gridLayout_2.addWidget(self.maps_boundaries, 3, 1, 1, 1)
        self.performance_cat = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.performance_cat.setObjectName("performance_cat")
        self.gridLayout_2.addWidget(self.performance_cat, 15, 0, 1, 1)
        self.maps_frequency = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_frequency.setObjectName("maps_frequency")
        self.gridLayout_2.addWidget(self.maps_frequency, 12, 1, 1, 1)
        self.maps_luchange = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_luchange.setObjectName("maps_luchange")
        self.gridLayout_2.addWidget(self.maps_luchange, 6, 0, 1, 1)
        self.maps_implemented = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_implemented.setObjectName("maps_implemented")
        self.gridLayout_2.addWidget(self.maps_implemented, 14, 0, 1, 1)
        self.maps_basins = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_basins.setObjectName("maps_basins")
        self.gridLayout_2.addWidget(self.maps_basins, 2, 1, 1, 1)
        self.urbandev_cat = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.urbandev_cat.setObjectName("urbandev_cat")
        self.gridLayout_2.addWidget(self.urbandev_cat, 5, 0, 1, 1)
        self.maps_popchange = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_popchange.setObjectName("maps_popchange")
        self.gridLayout_2.addWidget(self.maps_popchange, 6, 1, 1, 1)
        self.maps_localities = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_localities.setObjectName("maps_localities")
        self.gridLayout_2.addWidget(self.maps_localities, 9, 0, 1, 1)
        self.maps_centrepoints = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_centrepoints.setObjectName("maps_centrepoints")
        self.gridLayout_2.addWidget(self.maps_centrepoints, 3, 0, 1, 1)
        self.maps_pollution = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_pollution.setObjectName("maps_pollution")
        self.gridLayout_2.addWidget(self.maps_pollution, 8, 0, 1, 1)
        self.maps_wds = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_wds.setObjectName("maps_wds")
        self.gridLayout_2.addWidget(self.maps_wds, 16, 0, 1, 1)
        self.maps_uhi = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_uhi.setObjectName("maps_uhi")
        self.gridLayout_2.addWidget(self.maps_uhi, 16, 1, 1, 1)
        self.maps_flowpaths = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.maps_flowpaths.setObjectName("maps_flowpaths")
        self.gridLayout_2.addWidget(self.maps_flowpaths, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.mapexport_widget.addTab(self.maps_tab, "")
        self.formatting_tab = QtWidgets.QWidget()
        self.formatting_tab.setObjectName("formatting_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.formatting_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.formatting_tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 474, 308))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.shp_title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.shp_title.setObjectName("shp_title")
        self.verticalLayout_7.addWidget(self.shp_title)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.projection_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.projection_lbl.setObjectName("projection_lbl")
        self.gridLayout_5.addWidget(self.projection_lbl, 1, 0, 1, 1)
        self.projectionCombo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.projectionCombo.setObjectName("projectionCombo")
        self.projectionCombo.addItem("")
        self.projectionCombo.addItem("")
        self.projectionCombo.addItem("")
        self.gridLayout_5.addWidget(self.projectionCombo, 1, 1, 1, 1)
        self.epsg_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.epsg_lbl.setObjectName("epsg_lbl")
        self.gridLayout_5.addWidget(self.epsg_lbl, 2, 0, 1, 1)
        self.epsg_line = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.epsg_line.setObjectName("epsg_line")
        self.gridLayout_5.addWidget(self.epsg_line, 2, 1, 1, 1)
        self.kmlexport_check = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.kmlexport_check.setObjectName("kmlexport_check")
        self.gridLayout_5.addWidget(self.kmlexport_check, 3, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.offset_title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.offset_title.setObjectName("offset_title")
        self.verticalLayout_8.addWidget(self.offset_title)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.offsetx_box = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.offsetx_box.setObjectName("offsetx_box")
        self.gridLayout_4.addWidget(self.offsetx_box, 4, 0, 1, 1)
        self.offsetfrominput_radio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.offsetfrominput_radio.setObjectName("offsetfrominput_radio")
        self.gridLayout_4.addWidget(self.offsetfrominput_radio, 1, 0, 1, 1)
        self.offsetx_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.offsetx_lbl.setObjectName("offsetx_lbl")
        self.gridLayout_4.addWidget(self.offsetx_lbl, 3, 0, 1, 1)
        self.offsetcustom_radio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.offsetcustom_radio.setObjectName("offsetcustom_radio")
        self.gridLayout_4.addWidget(self.offsetcustom_radio, 2, 0, 1, 1)
        self.offsety_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.offsety_lbl.setObjectName("offsety_lbl")
        self.gridLayout_4.addWidget(self.offsety_lbl, 3, 1, 1, 1)
        self.offsety_box = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.offsety_box.setText("")
        self.offsety_box.setObjectName("offsety_box")
        self.gridLayout_4.addWidget(self.offsety_box, 4, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.mapexport_widget.addTab(self.formatting_tab, "")
        self.verticalLayout.addWidget(self.mapexport_widget)
        self.footer = QtWidgets.QWidget(MapExportDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ok_button = QtWidgets.QToolButton(self.footer)
        self.ok_button.setMinimumSize(QtCore.QSize(75, 0))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.footer)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(MapExportDialog)
        self.mapexport_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MapExportDialog)
        MapExportDialog.setTabOrder(self.mapexport_widget, self.scrollArea)
        MapExportDialog.setTabOrder(self.scrollArea, self.maps_blocks)
        MapExportDialog.setTabOrder(self.maps_blocks, self.maps_basins)
        MapExportDialog.setTabOrder(self.maps_basins, self.maps_centrepoints)
        MapExportDialog.setTabOrder(self.maps_centrepoints, self.maps_boundaries)
        MapExportDialog.setTabOrder(self.maps_boundaries, self.maps_patches)
        MapExportDialog.setTabOrder(self.maps_patches, self.maps_luchange)
        MapExportDialog.setTabOrder(self.maps_luchange, self.maps_popchange)
        MapExportDialog.setTabOrder(self.maps_popchange, self.maps_pollution)
        MapExportDialog.setTabOrder(self.maps_pollution, self.maps_floodrisk)
        MapExportDialog.setTabOrder(self.maps_floodrisk, self.maps_localities)
        MapExportDialog.setTabOrder(self.maps_localities, self.maps_suitability)
        MapExportDialog.setTabOrder(self.maps_suitability, self.maps_frequency)
        MapExportDialog.setTabOrder(self.maps_frequency, self.maps_planned)
        MapExportDialog.setTabOrder(self.maps_planned, self.maps_service)
        MapExportDialog.setTabOrder(self.maps_service, self.maps_implemented)
        MapExportDialog.setTabOrder(self.maps_implemented, self.maps_wds)
        MapExportDialog.setTabOrder(self.maps_wds, self.maps_uhi)
        MapExportDialog.setTabOrder(self.maps_uhi, self.scrollArea_2)
        MapExportDialog.setTabOrder(self.scrollArea_2, self.projectionCombo)
        MapExportDialog.setTabOrder(self.projectionCombo, self.epsg_line)
        MapExportDialog.setTabOrder(self.epsg_line, self.kmlexport_check)
        MapExportDialog.setTabOrder(self.kmlexport_check, self.offsetfrominput_radio)
        MapExportDialog.setTabOrder(self.offsetfrominput_radio, self.offsetcustom_radio)
        MapExportDialog.setTabOrder(self.offsetcustom_radio, self.offsetx_box)
        MapExportDialog.setTabOrder(self.offsetx_box, self.offsety_box)
        MapExportDialog.setTabOrder(self.offsety_box, self.ok_button)
        MapExportDialog.setTabOrder(self.ok_button, self.cancel_button)

    def retranslateUi(self, MapExportDialog):
        _translate = QtCore.QCoreApplication.translate
        MapExportDialog.setWindowTitle(_translate("MapExportDialog", "Add Data..."))
        self.title.setText(_translate("MapExportDialog", "Map Export Options"))
        self.subtitle.setText(_translate("MapExportDialog", "Customize the types of maps and formats to export"))
        self.selectmaps_title.setText(_translate("MapExportDialog", "Select the range of maps you would like to export:"))
        self.maps_suitability.setText(_translate("MapExportDialog", "Spatial Suitability Map"))
        self.maps_floodrisk.setText(_translate("MapExportDialog", "Flood Risk Map"))
        self.maps_service.setText(_translate("MapExportDialog", "Service Map"))
        self.maps_planned.setText(_translate("MapExportDialog", "Planned Infrastructure"))
        self.spatialmapping_cat.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Spatial Mapping</span></p></body></html>"))
        self.maps_blocks.setText(_translate("MapExportDialog", "Building Blocks"))
        self.maps_patches.setText(_translate("MapExportDialog", "Patch Data"))
        self.spatialrep_cat.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Spatial Representation</span></p></body></html>"))
        self.infrastructure_cat.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Infrastructure Planning</span></p></body></html>"))
        self.maps_boundaries.setText(_translate("MapExportDialog", "Boundaries"))
        self.performance_cat.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Performance Evaluation</span></p></body></html>"))
        self.maps_frequency.setText(_translate("MapExportDialog", "Frequency Map"))
        self.maps_luchange.setText(_translate("MapExportDialog", "Land Use Change"))
        self.maps_implemented.setText(_translate("MapExportDialog", "Implemented Infrastructure"))
        self.maps_basins.setText(_translate("MapExportDialog", "Basin Map"))
        self.urbandev_cat.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Urban Development</span></p></body></html>"))
        self.maps_popchange.setText(_translate("MapExportDialog", "Population Change"))
        self.maps_localities.setText(_translate("MapExportDialog", "Localities"))
        self.maps_centrepoints.setText(_translate("MapExportDialog", "Centre Points for Blocks"))
        self.maps_pollution.setText(_translate("MapExportDialog", "Stormwater Pollution Map"))
        self.maps_wds.setText(_translate("MapExportDialog", "Water Distribution System Link"))
        self.maps_uhi.setText(_translate("MapExportDialog", "Urban Heat Island"))
        self.maps_flowpaths.setText(_translate("MapExportDialog", "Flow Paths"))
        self.mapexport_widget.setTabText(self.mapexport_widget.indexOf(self.maps_tab), _translate("MapExportDialog", "Maps"))
        self.shp_title.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Shapefile Projection &amp; Additional Formats</span></p></body></html>"))
        self.projection_lbl.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Select Projection:</span></p></body></html>"))
        self.projectionCombo.setItemText(0, _translate("MapExportDialog", "Universal Transverse Mercator (UTM)"))
        self.projectionCombo.setItemText(1, _translate("MapExportDialog", "GDA MGA"))
        self.projectionCombo.setItemText(2, _translate("MapExportDialog", "Other..."))
        self.epsg_lbl.setText(_translate("MapExportDialog", "Custom (EPSG):"))
        self.kmlexport_check.setText(_translate("MapExportDialog", "Export KML Maps (Google Earth)"))
        self.offset_title.setText(_translate("MapExportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Offset Exported Map:</span></p></body></html>"))
        self.offsetfrominput_radio.setText(_translate("MapExportDialog", "Use input data to align maps"))
        self.offsetx_lbl.setText(_translate("MapExportDialog", "x-Offset [m]:"))
        self.offsetcustom_radio.setText(_translate("MapExportDialog", "Use custom offsets (from global origin 0,0)"))
        self.offsety_lbl.setText(_translate("MapExportDialog", "y-Offset [m]:"))
        self.mapexport_widget.setTabText(self.mapexport_widget.indexOf(self.formatting_tab), _translate("MapExportDialog", "Formatting"))
        self.ok_button.setText(_translate("MapExportDialog", "OK"))
        self.cancel_button.setText(_translate("MapExportDialog", "Cancel"))
from . import ubeats_rc
