# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_infrastructureguilaunch.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Infrastructure_Dialog(object):
    def setupUi(self, Infrastructure_Dialog):
        Infrastructure_Dialog.setObjectName("Infrastructure_Dialog")
        Infrastructure_Dialog.resize(551, 445)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Infrastructure_Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Infrastructure_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(Infrastructure_Dialog)
        self.title_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.title_widget.setObjectName("title_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.title_widget)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_logo = QtWidgets.QLabel(self.title_widget)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/Bench-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_3.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_3.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.title_widget)
        self.widget = QtWidgets.QWidget(Infrastructure_Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.select_text = QtWidgets.QLabel(self.widget)
        self.select_text.setWordWrap(True)
        self.select_text.setObjectName("select_text")
        self.verticalLayout_2.addWidget(self.select_text)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.md_watersupply_check = QtWidgets.QCheckBox(self.widget)
        self.md_watersupply_check.setMaximumSize(QtCore.QSize(13, 13))
        self.md_watersupply_check.setText("")
        self.md_watersupply_check.setObjectName("md_watersupply_check")
        self.gridLayout.addWidget(self.md_watersupply_check, 2, 1, 1, 1)
        self.md_sww_check = QtWidgets.QCheckBox(self.widget)
        self.md_sww_check.setMaximumSize(QtCore.QSize(13, 13))
        self.md_sww_check.setText("")
        self.md_sww_check.setObjectName("md_sww_check")
        self.gridLayout.addWidget(self.md_sww_check, 4, 1, 1, 1)
        self.md_nbsplanning_button = QtWidgets.QPushButton(self.widget)
        self.md_nbsplanning_button.setMinimumSize(QtCore.QSize(200, 60))
        self.md_nbsplanning_button.setMaximumSize(QtCore.QSize(200, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Tree-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.md_nbsplanning_button.setIcon(icon1)
        self.md_nbsplanning_button.setIconSize(QtCore.QSize(50, 50))
        self.md_nbsplanning_button.setCheckable(False)
        self.md_nbsplanning_button.setChecked(False)
        self.md_nbsplanning_button.setObjectName("md_nbsplanning_button")
        self.gridLayout.addWidget(self.md_nbsplanning_button, 6, 2, 1, 1)
        self.md_sww_button = QtWidgets.QPushButton(self.widget)
        self.md_sww_button.setMinimumSize(QtCore.QSize(200, 60))
        self.md_sww_button.setMaximumSize(QtCore.QSize(200, 60))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Water-closet-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.md_sww_button.setIcon(icon2)
        self.md_sww_button.setIconSize(QtCore.QSize(50, 50))
        self.md_sww_button.setObjectName("md_sww_button")
        self.gridLayout.addWidget(self.md_sww_button, 4, 2, 1, 1)
        self.md_nbsplanning_check = QtWidgets.QCheckBox(self.widget)
        self.md_nbsplanning_check.setMaximumSize(QtCore.QSize(13, 13))
        self.md_nbsplanning_check.setText("")
        self.md_nbsplanning_check.setObjectName("md_nbsplanning_check")
        self.gridLayout.addWidget(self.md_nbsplanning_check, 6, 1, 1, 1)
        self.md_watersupply_button = QtWidgets.QPushButton(self.widget)
        self.md_watersupply_button.setMinimumSize(QtCore.QSize(200, 60))
        self.md_watersupply_button.setMaximumSize(QtCore.QSize(200, 60))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Industry-Water-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.md_watersupply_button.setIcon(icon3)
        self.md_watersupply_button.setIconSize(QtCore.QSize(50, 50))
        self.md_watersupply_button.setObjectName("md_watersupply_button")
        self.gridLayout.addWidget(self.md_watersupply_button, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.widget)
        self.footer = QtWidgets.QWidget(Infrastructure_Dialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.pushButton_3 = QtWidgets.QPushButton(self.footer)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(Infrastructure_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Infrastructure_Dialog)

    def retranslateUi(self, Infrastructure_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Infrastructure_Dialog.setWindowTitle(_translate("Infrastructure_Dialog", "Infrastructure Planning..."))
        self.title.setText(_translate("Infrastructure_Dialog", "Infrastructure Planning Module"))
        self.subtitle.setText(_translate("Infrastructure_Dialog", "Plan different kinds of sustainable and resilient urban infrastructure"))
        self.select_text.setText(_translate("Infrastructure_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Select which types of infrastructure to plan and customise parameters:</span></p></body></html>"))
        self.md_nbsplanning_button.setText(_translate("Infrastructure_Dialog", "Nature-based Solutions"))
        self.md_sww_button.setText(_translate("Infrastructure_Dialog", "Wastewater System"))
        self.md_watersupply_button.setText(_translate("Infrastructure_Dialog", "Water Supply Strategies"))
        self.label.setText(_translate("Infrastructure_Dialog", "Plan water supply and distribution strategies across the case study region. This module generates a synthetic centralised water supply system and explores diversity and security of supply sources."))
        self.label_2.setText(_translate("Infrastructure_Dialog", "Plan the wastewater system. This module generates a synthetic sewer system, assesses potential decentralised options and explore transition strategies for sustainable wastewater management."))
        self.label_3.setText(_translate("Infrastructure_Dialog", "Design decentralised stormwater management schemes and leverage the multiple benefits of nature-based solutions (also known as Water Sensitive Urban Design, Low Impact Development, Sustainable Urban Drainage Systems)."))
        self.pushButton_3.setText(_translate("Infrastructure_Dialog", "Close"))
from . import ubeats_rc
