# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_subgui_dp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomPatternDialog(object):
    def setupUi(self, CustomPatternDialog):
        CustomPatternDialog.setObjectName("CustomPatternDialog")
        CustomPatternDialog.resize(283, 460)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomPatternDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.demand_down_title = QtWidgets.QLabel(CustomPatternDialog)
        self.demand_down_title.setEnabled(True)
        self.demand_down_title.setMinimumSize(QtCore.QSize(0, 16))
        self.demand_down_title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.demand_down_title.setObjectName("demand_down_title")
        self.verticalLayout.addWidget(self.demand_down_title)
        self.widget = QtWidgets.QWidget(CustomPatternDialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enduselbl = QtWidgets.QLabel(self.widget)
        self.enduselbl.setObjectName("enduselbl")
        self.horizontalLayout_2.addWidget(self.enduselbl)
        self.endusetype = QtWidgets.QLineEdit(self.widget)
        self.endusetype.setAcceptDrops(False)
        self.endusetype.setReadOnly(True)
        self.endusetype.setObjectName("endusetype")
        self.horizontalLayout_2.addWidget(self.endusetype)
        self.endusetype.raise_()
        self.enduselbl.raise_()
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget = QtWidgets.QTableWidget(CustomPatternDialog)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(23, 0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout.addWidget(self.tableWidget)
        self.widget_2 = QtWidgets.QWidget(CustomPatternDialog)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.avg_lbl = QtWidgets.QLabel(self.widget_2)
        self.avg_lbl.setObjectName("avg_lbl")
        self.horizontalLayout.addWidget(self.avg_lbl)
        self.avg_box = QtWidgets.QLineEdit(self.widget_2)
        self.avg_box.setAcceptDrops(False)
        self.avg_box.setReadOnly(True)
        self.avg_box.setObjectName("avg_box")
        self.horizontalLayout.addWidget(self.avg_box)
        self.verticalLayout.addWidget(self.widget_2)
        self.footer_widget = QtWidgets.QWidget(CustomPatternDialog)
        self.footer_widget.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_widget.setObjectName("footer_widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_Box = QtWidgets.QDialogButtonBox(self.footer_widget)
        self.button_Box.setOrientation(QtCore.Qt.Horizontal)
        self.button_Box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_Box.setObjectName("button_Box")
        self.horizontalLayout_7.addWidget(self.button_Box)
        self.verticalLayout.addWidget(self.footer_widget)

        self.retranslateUi(CustomPatternDialog)
        self.button_Box.accepted.connect(CustomPatternDialog.accept)
        self.button_Box.rejected.connect(CustomPatternDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CustomPatternDialog)

    def retranslateUi(self, CustomPatternDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomPatternDialog.setWindowTitle(_translate("CustomPatternDialog", "Define Custom Pattern"))
        self.demand_down_title.setText(_translate("CustomPatternDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Define Custom Pattern (24h)</span></p></body></html>"))
        self.enduselbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">End Use:</span></p></body></html>"))
        self.endusetype.setText(_translate("CustomPatternDialog", "<end use type>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "      00:00      "))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("CustomPatternDialog", "      01:00"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("CustomPatternDialog", "      02:00"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("CustomPatternDialog", "      03:00"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("CustomPatternDialog", "      04:00"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("CustomPatternDialog", "      05:00"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("CustomPatternDialog", "      06:00"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("CustomPatternDialog", "      07:00"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("CustomPatternDialog", "      08:00"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("CustomPatternDialog", "      09:00"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("CustomPatternDialog", "      10:00"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("CustomPatternDialog", "      11:00"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("CustomPatternDialog", "      12:00"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("CustomPatternDialog", "      13:00"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("CustomPatternDialog", "      14:00"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("CustomPatternDialog", "      15:00"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("CustomPatternDialog", "      16:00"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("CustomPatternDialog", "      17:00"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("CustomPatternDialog", "      18:00"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("CustomPatternDialog", "      19:00"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("CustomPatternDialog", "      20:00"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("CustomPatternDialog", "      21:00"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("CustomPatternDialog", "      22:00"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("CustomPatternDialog", "      23:00"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "Scaling Factor"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.avg_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p>Average Scaling:</p></body></html>"))
        self.avg_box.setText(_translate("CustomPatternDialog", "1.0"))

