# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_subgui_influence.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomPatternDialog(object):
    def setupUi(self, CustomPatternDialog):
        CustomPatternDialog.setObjectName("CustomPatternDialog")
        CustomPatternDialog.resize(650, 535)
        self.gridLayout = QtWidgets.QGridLayout(CustomPatternDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.footer_widget = QtWidgets.QWidget(CustomPatternDialog)
        self.footer_widget.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_widget.setObjectName("footer_widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.createButton = QtWidgets.QPushButton(self.footer_widget)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_7.addWidget(self.createButton)
        self.cancelButton = QtWidgets.QPushButton(self.footer_widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_7.addWidget(self.cancelButton)
        self.gridLayout.addWidget(self.footer_widget, 3, 0, 1, 2)
        self.title = QtWidgets.QLabel(CustomPatternDialog)
        self.title.setEnabled(True)
        self.title.setMinimumSize(QtCore.QSize(0, 16))
        self.title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 2)
        self.input_widget = QtWidgets.QWidget(CustomPatternDialog)
        self.input_widget.setObjectName("input_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.datainputmethod_lbl = QtWidgets.QLabel(self.input_widget)
        self.datainputmethod_lbl.setObjectName("datainputmethod_lbl")
        self.verticalLayout_2.addWidget(self.datainputmethod_lbl)
        self.datainputmethod_combo = QtWidgets.QComboBox(self.input_widget)
        self.datainputmethod_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.datainputmethod_combo.setObjectName("datainputmethod_combo")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.verticalLayout_2.addWidget(self.datainputmethod_combo)
        self.standardlib_lbl = QtWidgets.QLabel(self.input_widget)
        self.standardlib_lbl.setObjectName("standardlib_lbl")
        self.verticalLayout_2.addWidget(self.standardlib_lbl)
        self.standardlib_combo = QtWidgets.QComboBox(self.input_widget)
        self.standardlib_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.standardlib_combo.setObjectName("standardlib_combo")
        self.standardlib_combo.addItem("")
        self.verticalLayout_2.addWidget(self.standardlib_combo)
        self.landuse_title = QtWidgets.QLabel(self.input_widget)
        self.landuse_title.setObjectName("landuse_title")
        self.verticalLayout_2.addWidget(self.landuse_title)
        self.define_luc_lbl = QtWidgets.QLabel(self.input_widget)
        self.define_luc_lbl.setObjectName("define_luc_lbl")
        self.verticalLayout_2.addWidget(self.define_luc_lbl)
        self.define_luc_combo = QtWidgets.QComboBox(self.input_widget)
        self.define_luc_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.define_luc_combo.setObjectName("define_luc_combo")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.verticalLayout_2.addWidget(self.define_luc_combo)
        self.influence_lbl = QtWidgets.QLabel(self.input_widget)
        self.influence_lbl.setObjectName("influence_lbl")
        self.verticalLayout_2.addWidget(self.influence_lbl)
        self.influence_luc_combo = QtWidgets.QComboBox(self.input_widget)
        self.influence_luc_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.influence_luc_combo.setObjectName("influence_luc_combo")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.verticalLayout_2.addWidget(self.influence_luc_combo)
        self.weight_title = QtWidgets.QLabel(self.input_widget)
        self.weight_title.setObjectName("weight_title")
        self.verticalLayout_2.addWidget(self.weight_title)
        self.datapoints_widget = QtWidgets.QWidget(self.input_widget)
        self.datapoints_widget.setObjectName("datapoints_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.datapoints_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datapoints_lbl = QtWidgets.QLabel(self.datapoints_widget)
        self.datapoints_lbl.setObjectName("datapoints_lbl")
        self.horizontalLayout.addWidget(self.datapoints_lbl)
        self.datapoints_spin = QtWidgets.QSpinBox(self.datapoints_widget)
        self.datapoints_spin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.datapoints_spin.setMinimum(2)
        self.datapoints_spin.setMaximum(30)
        self.datapoints_spin.setObjectName("datapoints_spin")
        self.horizontalLayout.addWidget(self.datapoints_spin)
        self.verticalLayout_2.addWidget(self.datapoints_widget)
        self.datatable = QtWidgets.QTableWidget(self.input_widget)
        self.datatable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datatable.setObjectName("datatable")
        self.datatable.setColumnCount(1)
        self.datatable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.datatable.setHorizontalHeaderItem(0, item)
        self.datatable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.datatable)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.input_widget, 1, 0, 1, 1)
        self.view_widget = QtWidgets.QWidget(CustomPatternDialog)
        self.view_widget.setMinimumSize(QtCore.QSize(400, 0))
        self.view_widget.setObjectName("view_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.view_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataplot_lbl = QtWidgets.QLabel(self.view_widget)
        self.dataplot_lbl.setObjectName("dataplot_lbl")
        self.verticalLayout.addWidget(self.dataplot_lbl)
        self.dataplot = QtWidgets.QGraphicsView(self.view_widget)
        self.dataplot.setMinimumSize(QtCore.QSize(0, 0))
        self.dataplot.setObjectName("dataplot")
        self.verticalLayout.addWidget(self.dataplot)
        self.metadata_title = QtWidgets.QLabel(self.view_widget)
        self.metadata_title.setObjectName("metadata_title")
        self.verticalLayout.addWidget(self.metadata_title)
        self.metadata_sourcetext = QtWidgets.QLabel(self.view_widget)
        self.metadata_sourcetext.setWordWrap(True)
        self.metadata_sourcetext.setObjectName("metadata_sourcetext")
        self.verticalLayout.addWidget(self.metadata_sourcetext)
        self.metadata_statstext = QtWidgets.QLabel(self.view_widget)
        self.metadata_statstext.setWordWrap(True)
        self.metadata_statstext.setObjectName("metadata_statstext")
        self.verticalLayout.addWidget(self.metadata_statstext)
        self.gridLayout.addWidget(self.view_widget, 1, 1, 1, 1)

        self.retranslateUi(CustomPatternDialog)
        self.datainputmethod_combo.setCurrentIndex(0)
        self.standardlib_combo.setCurrentIndex(0)
        self.define_luc_combo.setCurrentIndex(0)
        self.influence_luc_combo.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(CustomPatternDialog)

    def retranslateUi(self, CustomPatternDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomPatternDialog.setWindowTitle(_translate("CustomPatternDialog", "Define Custom Pattern"))
        self.createButton.setText(_translate("CustomPatternDialog", "Create"))
        self.cancelButton.setText(_translate("CustomPatternDialog", "Cancel"))
        self.title.setText(_translate("CustomPatternDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">DEFINE A NEW INFLUENCE FUNCTION</span></p></body></html>"))
        self.datainputmethod_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Select Method of Data Input:</span></p></body></html>"))
        self.datainputmethod_combo.setItemText(0, _translate("CustomPatternDialog", "(no method selected)"))
        self.datainputmethod_combo.setItemText(1, _translate("CustomPatternDialog", "Import Template (.ubif)"))
        self.datainputmethod_combo.setItemText(2, _translate("CustomPatternDialog", "Select from Standard Library"))
        self.datainputmethod_combo.setItemText(3, _translate("CustomPatternDialog", "Manual Data Entry"))
        self.datainputmethod_combo.setItemText(4, _translate("CustomPatternDialog", "Use Existing Function"))
        self.standardlib_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p>Standard Library / Select Function:</p></body></html>"))
        self.standardlib_combo.setItemText(0, _translate("CustomPatternDialog", "(none)"))
        self.landuse_title.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Define Land Uses</span></p></body></html>"))
        self.define_luc_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p>Defined for (active land use):</p></body></html>"))
        self.define_luc_combo.setItemText(0, _translate("CustomPatternDialog", "Residential"))
        self.define_luc_combo.setItemText(1, _translate("CustomPatternDialog", "Commercial"))
        self.define_luc_combo.setItemText(2, _translate("CustomPatternDialog", "Industrial"))
        self.define_luc_combo.setItemText(3, _translate("CustomPatternDialog", "Mixed Development"))
        self.influence_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p>Influenced by:</p></body></html>"))
        self.influence_luc_combo.setItemText(0, _translate("CustomPatternDialog", "Agriculture"))
        self.influence_luc_combo.setItemText(1, _translate("CustomPatternDialog", "Civic"))
        self.influence_luc_combo.setItemText(2, _translate("CustomPatternDialog", "Commercial"))
        self.influence_luc_combo.setItemText(3, _translate("CustomPatternDialog", "Forest"))
        self.influence_luc_combo.setItemText(4, _translate("CustomPatternDialog", "Industrial"))
        self.influence_luc_combo.setItemText(5, _translate("CustomPatternDialog", "Mixed Development"))
        self.influence_luc_combo.setItemText(6, _translate("CustomPatternDialog", "Parks and Gardens"))
        self.influence_luc_combo.setItemText(7, _translate("CustomPatternDialog", "Reserves and Floodways"))
        self.influence_luc_combo.setItemText(8, _translate("CustomPatternDialog", "Residential"))
        self.influence_luc_combo.setItemText(9, _translate("CustomPatternDialog", "Road"))
        self.influence_luc_combo.setItemText(10, _translate("CustomPatternDialog", "Service and Utility"))
        self.influence_luc_combo.setItemText(11, _translate("CustomPatternDialog", "Transport"))
        self.influence_luc_combo.setItemText(12, _translate("CustomPatternDialog", "Unclassified"))
        self.influence_luc_combo.setItemText(13, _translate("CustomPatternDialog", "Undeveloped"))
        self.influence_luc_combo.setItemText(14, _translate("CustomPatternDialog", "Water"))
        self.weight_title.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Weight vs. Distance</span></p></body></html>"))
        self.datapoints_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p>Number of Data Points:</p></body></html>"))
        item = self.datatable.verticalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "0"))
        item = self.datatable.verticalHeaderItem(1)
        item.setText(_translate("CustomPatternDialog", "max."))
        item = self.datatable.horizontalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "Weight"))
        self.dataplot_lbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Influence Function</span></p></body></html>"))
        self.metadata_title.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Metadata</span></p></body></html>"))
        self.metadata_sourcetext.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-style:italic;\">using Standard Library</span></p></body></html>"))
        self.metadata_statstext.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Maximum Weight: ??? @ ?? km        Minimum Weight: ??? @ ?? km</span></p></body></html>"))

