# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_subgui_influence.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfluenceFunctionDialog(object):
    def setupUi(self, InfluenceFunctionDialog):
        InfluenceFunctionDialog.setObjectName("InfluenceFunctionDialog")
        InfluenceFunctionDialog.resize(650, 580)
        self.gridLayout = QtWidgets.QGridLayout(InfluenceFunctionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.title = QtWidgets.QLabel(InfluenceFunctionDialog)
        self.title.setEnabled(True)
        self.title.setMinimumSize(QtCore.QSize(0, 16))
        self.title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 2)
        self.input_widget = QtWidgets.QWidget(InfluenceFunctionDialog)
        self.input_widget.setObjectName("input_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_widget)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.datainputmethod_lbl = QtWidgets.QLabel(self.input_widget)
        self.datainputmethod_lbl.setObjectName("datainputmethod_lbl")
        self.verticalLayout_2.addWidget(self.datainputmethod_lbl)
        self.datainputmethod_combo = QtWidgets.QComboBox(self.input_widget)
        self.datainputmethod_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.datainputmethod_combo.setObjectName("datainputmethod_combo")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.datainputmethod_combo.addItem("")
        self.verticalLayout_2.addWidget(self.datainputmethod_combo)
        self.standardlib_lbl = QtWidgets.QLabel(self.input_widget)
        self.standardlib_lbl.setObjectName("standardlib_lbl")
        self.verticalLayout_2.addWidget(self.standardlib_lbl)
        self.standardlib_combo = QtWidgets.QComboBox(self.input_widget)
        self.standardlib_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.standardlib_combo.setObjectName("standardlib_combo")
        self.standardlib_combo.addItem("")
        self.verticalLayout_2.addWidget(self.standardlib_combo)
        self.functionname_lbl = QtWidgets.QLabel(self.input_widget)
        self.functionname_lbl.setObjectName("functionname_lbl")
        self.verticalLayout_2.addWidget(self.functionname_lbl)
        self.functionname_box = QtWidgets.QLineEdit(self.input_widget)
        self.functionname_box.setObjectName("functionname_box")
        self.verticalLayout_2.addWidget(self.functionname_box)
        self.landuse_title = QtWidgets.QLabel(self.input_widget)
        self.landuse_title.setObjectName("landuse_title")
        self.verticalLayout_2.addWidget(self.landuse_title)
        self.define_luc_lbl = QtWidgets.QLabel(self.input_widget)
        self.define_luc_lbl.setObjectName("define_luc_lbl")
        self.verticalLayout_2.addWidget(self.define_luc_lbl)
        self.define_luc_combo = QtWidgets.QComboBox(self.input_widget)
        self.define_luc_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.define_luc_combo.setObjectName("define_luc_combo")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.define_luc_combo.addItem("")
        self.verticalLayout_2.addWidget(self.define_luc_combo)
        self.influence_lbl = QtWidgets.QLabel(self.input_widget)
        self.influence_lbl.setObjectName("influence_lbl")
        self.verticalLayout_2.addWidget(self.influence_lbl)
        self.influence_luc_combo = QtWidgets.QComboBox(self.input_widget)
        self.influence_luc_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.influence_luc_combo.setObjectName("influence_luc_combo")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.influence_luc_combo.addItem("")
        self.verticalLayout_2.addWidget(self.influence_luc_combo)
        self.weight_title = QtWidgets.QLabel(self.input_widget)
        self.weight_title.setObjectName("weight_title")
        self.verticalLayout_2.addWidget(self.weight_title)
        self.datapoints_widget = QtWidgets.QWidget(self.input_widget)
        self.datapoints_widget.setObjectName("datapoints_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.datapoints_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datapoints_lbl = QtWidgets.QLabel(self.datapoints_widget)
        self.datapoints_lbl.setObjectName("datapoints_lbl")
        self.horizontalLayout.addWidget(self.datapoints_lbl)
        self.datapoints_spin = QtWidgets.QSpinBox(self.datapoints_widget)
        self.datapoints_spin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.datapoints_spin.setMinimum(2)
        self.datapoints_spin.setMaximum(30)
        self.datapoints_spin.setObjectName("datapoints_spin")
        self.horizontalLayout.addWidget(self.datapoints_spin)
        self.verticalLayout_2.addWidget(self.datapoints_widget)
        self.datatable = QtWidgets.QTableWidget(self.input_widget)
        self.datatable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datatable.setObjectName("datatable")
        self.datatable.setColumnCount(2)
        self.datatable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.datatable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.datatable.setHorizontalHeaderItem(1, item)
        self.datatable.horizontalHeader().setDefaultSectionSize(80)
        self.datatable.horizontalHeader().setStretchLastSection(True)
        self.datatable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.datatable)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.input_widget, 2, 0, 1, 1)
        self.view_widget = QtWidgets.QWidget(InfluenceFunctionDialog)
        self.view_widget.setMinimumSize(QtCore.QSize(400, 0))
        self.view_widget.setObjectName("view_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.view_widget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.view_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.widget_2 = QtWidgets.QWidget(self.view_widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.savefunction_button = QtWidgets.QPushButton(self.widget_2)
        self.savefunction_button.setObjectName("savefunction_button")
        self.horizontalLayout_3.addWidget(self.savefunction_button)
        self.deletefunction_button = QtWidgets.QPushButton(self.widget_2)
        self.deletefunction_button.setObjectName("deletefunction_button")
        self.horizontalLayout_3.addWidget(self.deletefunction_button)
        self.exportfunction_button = QtWidgets.QPushButton(self.widget_2)
        self.exportfunction_button.setObjectName("exportfunction_button")
        self.horizontalLayout_3.addWidget(self.exportfunction_button)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.view_widget, 2, 1, 1, 1)
        self.footer_widget = QtWidgets.QWidget(InfluenceFunctionDialog)
        self.footer_widget.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_widget.setObjectName("footer_widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.createButton = QtWidgets.QPushButton(self.footer_widget)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_7.addWidget(self.createButton)
        self.cancelButton = QtWidgets.QPushButton(self.footer_widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_7.addWidget(self.cancelButton)
        self.gridLayout.addWidget(self.footer_widget, 4, 0, 1, 2)
        self.widget = QtWidgets.QWidget(InfluenceFunctionDialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_lbl = QtWidgets.QLabel(self.widget)
        self.select_lbl.setMaximumSize(QtCore.QSize(200, 16777215))
        self.select_lbl.setObjectName("select_lbl")
        self.horizontalLayout_2.addWidget(self.select_lbl)
        self.select_combo = QtWidgets.QComboBox(self.widget)
        self.select_combo.setObjectName("select_combo")
        self.select_combo.addItem("")
        self.select_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.select_combo)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 2)

        self.retranslateUi(InfluenceFunctionDialog)
        self.datainputmethod_combo.setCurrentIndex(0)
        self.standardlib_combo.setCurrentIndex(0)
        self.define_luc_combo.setCurrentIndex(0)
        self.influence_luc_combo.setCurrentIndex(8)
        self.createButton.clicked.connect(InfluenceFunctionDialog.accept)
        self.cancelButton.clicked.connect(InfluenceFunctionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InfluenceFunctionDialog)

    def retranslateUi(self, InfluenceFunctionDialog):
        _translate = QtCore.QCoreApplication.translate
        InfluenceFunctionDialog.setWindowTitle(_translate("InfluenceFunctionDialog", "Define Influence Functions"))
        self.title.setText(_translate("InfluenceFunctionDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">URBAN MODELLING  - INFLUENCE FUNCTIONS</span></p></body></html>"))
        self.datainputmethod_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Select Method of Data Input:</span></p></body></html>"))
        self.datainputmethod_combo.setItemText(0, _translate("InfluenceFunctionDialog", "(no method selected)"))
        self.datainputmethod_combo.setItemText(1, _translate("InfluenceFunctionDialog", "Import Template (.ubif)"))
        self.datainputmethod_combo.setItemText(2, _translate("InfluenceFunctionDialog", "Manual Data Entry"))
        self.datainputmethod_combo.setItemText(3, _translate("InfluenceFunctionDialog", "Use a Standard Pattern"))
        self.datainputmethod_combo.setItemText(4, _translate("InfluenceFunctionDialog", "Modify an Existing Function"))
        self.standardlib_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p>Standard Library / Select Function:</p></body></html>"))
        self.standardlib_combo.setItemText(0, _translate("InfluenceFunctionDialog", "(none)"))
        self.functionname_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Define Function Nickname</span></p></body></html>"))
        self.landuse_title.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Define Land Uses</span></p></body></html>"))
        self.define_luc_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p>Defined for (active land use):</p></body></html>"))
        self.define_luc_combo.setItemText(0, _translate("InfluenceFunctionDialog", "Residential"))
        self.define_luc_combo.setItemText(1, _translate("InfluenceFunctionDialog", "Commercial"))
        self.define_luc_combo.setItemText(2, _translate("InfluenceFunctionDialog", "Industrial"))
        self.define_luc_combo.setItemText(3, _translate("InfluenceFunctionDialog", "Mixed Development"))
        self.influence_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p>Influenced by:</p></body></html>"))
        self.influence_luc_combo.setItemText(0, _translate("InfluenceFunctionDialog", "Agriculture"))
        self.influence_luc_combo.setItemText(1, _translate("InfluenceFunctionDialog", "Civic"))
        self.influence_luc_combo.setItemText(2, _translate("InfluenceFunctionDialog", "Commercial"))
        self.influence_luc_combo.setItemText(3, _translate("InfluenceFunctionDialog", "Forest"))
        self.influence_luc_combo.setItemText(4, _translate("InfluenceFunctionDialog", "Industrial"))
        self.influence_luc_combo.setItemText(5, _translate("InfluenceFunctionDialog", "Mixed Development"))
        self.influence_luc_combo.setItemText(6, _translate("InfluenceFunctionDialog", "Parks and Gardens"))
        self.influence_luc_combo.setItemText(7, _translate("InfluenceFunctionDialog", "Reserves and Floodways"))
        self.influence_luc_combo.setItemText(8, _translate("InfluenceFunctionDialog", "Residential"))
        self.influence_luc_combo.setItemText(9, _translate("InfluenceFunctionDialog", "Road"))
        self.influence_luc_combo.setItemText(10, _translate("InfluenceFunctionDialog", "Service and Utility"))
        self.influence_luc_combo.setItemText(11, _translate("InfluenceFunctionDialog", "Transport"))
        self.influence_luc_combo.setItemText(12, _translate("InfluenceFunctionDialog", "Unclassified"))
        self.influence_luc_combo.setItemText(13, _translate("InfluenceFunctionDialog", "Undeveloped"))
        self.influence_luc_combo.setItemText(14, _translate("InfluenceFunctionDialog", "Water"))
        self.weight_title.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Weight vs. Distance [km]</span></p></body></html>"))
        self.datapoints_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p>Number of Data Points:</p></body></html>"))
        item = self.datatable.verticalHeaderItem(0)
        item.setText(_translate("InfluenceFunctionDialog", "1"))
        item = self.datatable.verticalHeaderItem(1)
        item.setText(_translate("InfluenceFunctionDialog", "2"))
        item = self.datatable.horizontalHeaderItem(0)
        item.setText(_translate("InfluenceFunctionDialog", "Distance"))
        item = self.datatable.horizontalHeaderItem(1)
        item.setText(_translate("InfluenceFunctionDialog", "Weight"))
        self.savefunction_button.setText(_translate("InfluenceFunctionDialog", "Save Function"))
        self.deletefunction_button.setText(_translate("InfluenceFunctionDialog", "Delete"))
        self.exportfunction_button.setText(_translate("InfluenceFunctionDialog", "Export..."))
        self.createButton.setText(_translate("InfluenceFunctionDialog", "OK"))
        self.cancelButton.setText(_translate("InfluenceFunctionDialog", "Cancel"))
        self.select_lbl.setText(_translate("InfluenceFunctionDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Select an Influence Function:</span></p></body></html>"))
        self.select_combo.setItemText(0, _translate("InfluenceFunctionDialog", "<no selection>"))
        self.select_combo.setItemText(1, _translate("InfluenceFunctionDialog", "<create new influence function>"))
from PyQt5 import QtWebEngineWidgets
