# Form implementation generated from reading ui file 'newscenario_timestep.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimeStep_Dialog(object):
    def setupUi(self, TimeStep_Dialog):
        TimeStep_Dialog.setObjectName("TimeStep_Dialog")
        TimeStep_Dialog.resize(174, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimeStep_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timestep_title = QtWidgets.QLabel(TimeStep_Dialog)
        self.timestep_title.setMinimumSize(QtCore.QSize(120, 0))
        self.timestep_title.setObjectName("timestep_title")
        self.verticalLayout.addWidget(self.timestep_title)
        self.timestep_descr = QtWidgets.QLabel(TimeStep_Dialog)
        self.timestep_descr.setMinimumSize(QtCore.QSize(120, 0))
        self.timestep_descr.setObjectName("timestep_descr")
        self.verticalLayout.addWidget(self.timestep_descr)
        self.years_list = QtWidgets.QListWidget(TimeStep_Dialog)
        self.years_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.years_list.setObjectName("years_list")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.years_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.years_list.addItem(item)
        self.verticalLayout.addWidget(self.years_list)
        self.buttonBox = QtWidgets.QDialogButtonBox(TimeStep_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TimeStep_Dialog)
        self.buttonBox.accepted.connect(TimeStep_Dialog.accept)
        self.buttonBox.rejected.connect(TimeStep_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TimeStep_Dialog)

    def retranslateUi(self, TimeStep_Dialog):
        _translate = QtCore.QCoreApplication.translate
        TimeStep_Dialog.setWindowTitle(_translate("TimeStep_Dialog", "Dialog"))
        self.timestep_title.setWhatsThis(_translate("TimeStep_Dialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.timestep_title.setText(_translate("TimeStep_Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Irregular Time Steps</span></p></body></html>"))
        self.timestep_descr.setWhatsThis(_translate("TimeStep_Dialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.timestep_descr.setText(_translate("TimeStep_Dialog", "<html><head/><body><p>Select Years of Interest:</p></body></html>"))
        __sortingEnabled = self.years_list.isSortingEnabled()
        self.years_list.setSortingEnabled(False)
        item = self.years_list.item(0)
        item.setText(_translate("TimeStep_Dialog", "2018"))
        item = self.years_list.item(1)
        item.setText(_translate("TimeStep_Dialog", "2019"))
        item = self.years_list.item(2)
        item.setText(_translate("TimeStep_Dialog", "2020"))
        item = self.years_list.item(3)
        item.setText(_translate("TimeStep_Dialog", "2021"))
        item = self.years_list.item(4)
        item.setText(_translate("TimeStep_Dialog", "2022"))
        item = self.years_list.item(5)
        item.setText(_translate("TimeStep_Dialog", "2023"))
        item = self.years_list.item(6)
        item.setText(_translate("TimeStep_Dialog", "2024"))
        item = self.years_list.item(7)
        item.setText(_translate("TimeStep_Dialog", "2025"))
        item = self.years_list.item(8)
        item.setText(_translate("TimeStep_Dialog", "2026"))
        item = self.years_list.item(9)
        item.setText(_translate("TimeStep_Dialog", "2027"))
        item = self.years_list.item(10)
        item.setText(_translate("TimeStep_Dialog", "2028"))
        item = self.years_list.item(11)
        item.setText(_translate("TimeStep_Dialog", "2029"))
        item = self.years_list.item(12)
        item.setText(_translate("TimeStep_Dialog", "2030"))
        item = self.years_list.item(13)
        item.setText(_translate("TimeStep_Dialog", "2031"))
        item = self.years_list.item(14)
        item.setText(_translate("TimeStep_Dialog", "2032"))
        self.years_list.setSortingEnabled(__sortingEnabled)

