# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newscenario.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewScenarioDialog(object):
    def setupUi(self, NewScenarioDialog):
        NewScenarioDialog.setObjectName("NewScenarioDialog")
        NewScenarioDialog.resize(518, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewScenarioDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewScenarioDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(NewScenarioDialog)
        self.title_widget.setObjectName("title_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.title_widget)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_logo = QtWidgets.QLabel(self.title_widget)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/Map-icon (1).png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_3.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_3.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.title_widget)
        self.name_widget = QtWidgets.QWidget(NewScenarioDialog)
        self.name_widget.setObjectName("name_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.name_widget)
        self.gridLayout_8.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.name_box = QtWidgets.QLineEdit(self.name_widget)
        self.name_box.setEnabled(True)
        self.name_box.setReadOnly(False)
        self.name_box.setObjectName("name_box")
        self.gridLayout_8.addWidget(self.name_box, 0, 1, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.name_widget)
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout_8.addWidget(self.name_lbl, 0, 0, 1, 1)
        self.boundary_lbl = QtWidgets.QLabel(self.name_widget)
        self.boundary_lbl.setObjectName("boundary_lbl")
        self.gridLayout_8.addWidget(self.boundary_lbl, 1, 0, 1, 1)
        self.boundary_combo = QtWidgets.QComboBox(self.name_widget)
        self.boundary_combo.setObjectName("boundary_combo")
        self.boundary_combo.addItem("")
        self.gridLayout_8.addWidget(self.boundary_combo, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.name_widget)
        self.simtype_widget = QtWidgets.QWidget(NewScenarioDialog)
        self.simtype_widget.setObjectName("simtype_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.simtype_widget)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.simtype_lbl = QtWidgets.QLabel(self.simtype_widget)
        self.simtype_lbl.setObjectName("simtype_lbl")
        self.horizontalLayout_3.addWidget(self.simtype_lbl)
        self.static_radio = QtWidgets.QRadioButton(self.simtype_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.static_radio.setIcon(icon1)
        self.static_radio.setObjectName("static_radio")
        self.horizontalLayout_3.addWidget(self.static_radio)
        self.benchmark_radio = QtWidgets.QRadioButton(self.simtype_widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/78125-park-bench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.benchmark_radio.setIcon(icon2)
        self.benchmark_radio.setObjectName("benchmark_radio")
        self.horizontalLayout_3.addWidget(self.benchmark_radio)
        self.dynamic_radio = QtWidgets.QRadioButton(self.simtype_widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/55191-clock-symbol-of-circular-shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dynamic_radio.setIcon(icon3)
        self.dynamic_radio.setObjectName("dynamic_radio")
        self.horizontalLayout_3.addWidget(self.dynamic_radio)
        self.verticalLayout.addWidget(self.simtype_widget)
        self.setup_widget = QtWidgets.QTabWidget(NewScenarioDialog)
        self.setup_widget.setObjectName("setup_widget")
        self.narrative_tab = QtWidgets.QWidget()
        self.narrative_tab.setObjectName("narrative_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.narrative_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.narrative_lbl = QtWidgets.QLabel(self.narrative_tab)
        self.narrative_lbl.setObjectName("narrative_lbl")
        self.verticalLayout_6.addWidget(self.narrative_lbl)
        self.narrative_box = QtWidgets.QPlainTextEdit(self.narrative_tab)
        self.narrative_box.setMinimumSize(QtCore.QSize(0, 100))
        self.narrative_box.setDocumentTitle("")
        self.narrative_box.setObjectName("narrative_box")
        self.verticalLayout_6.addWidget(self.narrative_box)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pages-brown-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_widget.addTab(self.narrative_tab, icon4, "")
        self.details_tab = QtWidgets.QWidget()
        self.details_tab.setObjectName("details_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.details_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.timestep_widget = QtWidgets.QWidget(self.details_tab)
        self.timestep_widget.setObjectName("timestep_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.timestep_widget)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.simyear_lbl2 = QtWidgets.QLabel(self.timestep_widget)
        self.simyear_lbl2.setObjectName("simyear_lbl2")
        self.gridLayout_6.addWidget(self.simyear_lbl2, 0, 3, 1, 1)
        self.endyear_spin = QtWidgets.QSpinBox(self.timestep_widget)
        self.endyear_spin.setMinimumSize(QtCore.QSize(75, 0))
        self.endyear_spin.setMinimum(1900)
        self.endyear_spin.setMaximum(2500)
        self.endyear_spin.setProperty("value", 2068)
        self.endyear_spin.setObjectName("endyear_spin")
        self.gridLayout_6.addWidget(self.endyear_spin, 0, 4, 1, 1)
        self.timestep_lbl = QtWidgets.QLabel(self.timestep_widget)
        self.timestep_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.timestep_lbl.setObjectName("timestep_lbl")
        self.gridLayout_6.addWidget(self.timestep_lbl, 1, 0, 1, 1)
        self.timestep_spin = QtWidgets.QSpinBox(self.timestep_widget)
        self.timestep_spin.setMinimum(1)
        self.timestep_spin.setMaximum(20)
        self.timestep_spin.setProperty("value", 1)
        self.timestep_spin.setObjectName("timestep_spin")
        self.gridLayout_6.addWidget(self.timestep_spin, 1, 2, 1, 1)
        self.startyear_spin = QtWidgets.QSpinBox(self.timestep_widget)
        self.startyear_spin.setMinimumSize(QtCore.QSize(75, 0))
        self.startyear_spin.setMinimum(1900)
        self.startyear_spin.setMaximum(2500)
        self.startyear_spin.setProperty("value", 2018)
        self.startyear_spin.setObjectName("startyear_spin")
        self.gridLayout_6.addWidget(self.startyear_spin, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 5, 1, 1)
        self.simyear_lbl = QtWidgets.QLabel(self.timestep_widget)
        self.simyear_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.simyear_lbl.setObjectName("simyear_lbl")
        self.gridLayout_6.addWidget(self.simyear_lbl, 0, 0, 1, 1)
        self.timestep_irregular = QtWidgets.QCheckBox(self.timestep_widget)
        self.timestep_irregular.setObjectName("timestep_irregular")
        self.gridLayout_6.addWidget(self.timestep_irregular, 1, 4, 1, 1)
        self.timestep_irregular_button = QtWidgets.QPushButton(self.timestep_widget)
        self.timestep_irregular_button.setObjectName("timestep_irregular_button")
        self.gridLayout_6.addWidget(self.timestep_irregular_button, 1, 5, 1, 1)
        self.verticalLayout_8.addWidget(self.timestep_widget)
        self.timestep_widget_2 = QtWidgets.QWidget(self.details_tab)
        self.timestep_widget_2.setObjectName("timestep_widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.timestep_widget_2)
        self.gridLayout_7.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.benchmark_spin = QtWidgets.QSpinBox(self.timestep_widget_2)
        self.benchmark_spin.setMinimumSize(QtCore.QSize(75, 0))
        self.benchmark_spin.setMinimum(10)
        self.benchmark_spin.setMaximum(10000)
        self.benchmark_spin.setSingleStep(10)
        self.benchmark_spin.setProperty("value", 100)
        self.benchmark_spin.setObjectName("benchmark_spin")
        self.gridLayout_7.addWidget(self.benchmark_spin, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 3, 1, 1)
        self.benchmark_lbl = QtWidgets.QLabel(self.timestep_widget_2)
        self.benchmark_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.benchmark_lbl.setObjectName("benchmark_lbl")
        self.gridLayout_7.addWidget(self.benchmark_lbl, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.timestep_widget_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 193, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_widget.addTab(self.details_tab, icon5, "")
        self.module_tab = QtWidgets.QWidget()
        self.module_tab.setObjectName("module_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.module_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.descr_lbl = QtWidgets.QLabel(self.module_tab)
        self.descr_lbl.setObjectName("descr_lbl")
        self.verticalLayout_7.addWidget(self.descr_lbl)
        self.scrollArea = QtWidgets.QScrollArea(self.module_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.descr_lbl3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descr_lbl3.setObjectName("descr_lbl3")
        self.gridLayout_5.addWidget(self.descr_lbl3, 2, 0, 1, 1)
        self.watercycle = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/iconfinder_Ecology_tap_water_2992443.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.watercycle.setIcon(icon6)
        self.watercycle.setObjectName("watercycle")
        self.gridLayout_5.addWidget(self.watercycle, 11, 0, 1, 1)
        self.descr_lbl4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descr_lbl4.setObjectName("descr_lbl4")
        self.gridLayout_5.addWidget(self.descr_lbl4, 4, 0, 1, 1)
        self.citydevelopment = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Very-Basic-Design-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.citydevelopment.setIcon(icon7)
        self.citydevelopment.setObjectName("citydevelopment")
        self.gridLayout_5.addWidget(self.citydevelopment, 3, 0, 1, 1)
        self.climate = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.climate.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/cloudy-with-rain-2667018_960_720.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.climate.setIcon(icon8)
        self.climate.setCheckable(True)
        self.climate.setChecked(True)
        self.climate.setObjectName("climate")
        self.gridLayout_5.addWidget(self.climate, 1, 1, 1, 1)
        self.flood = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/iconfinder_wave_ocean_sea_water_surf_splash_5296676.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flood.setIcon(icon9)
        self.flood.setObjectName("flood")
        self.gridLayout_5.addWidget(self.flood, 12, 0, 1, 1)
        self.spatialmapping = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/GISLayers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spatialmapping.setIcon(icon10)
        self.spatialmapping.setObjectName("spatialmapping")
        self.gridLayout_5.addWidget(self.spatialmapping, 5, 1, 1, 1)
        self.bluegreen = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Tree-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bluegreen.setIcon(icon11)
        self.bluegreen.setObjectName("bluegreen")
        self.gridLayout_5.addWidget(self.bluegreen, 7, 1, 1, 1)
        self.descr_lbl5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descr_lbl5.setObjectName("descr_lbl5")
        self.gridLayout_5.addWidget(self.descr_lbl5, 10, 0, 1, 1)
        self.urbanplanning = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/City_icon_(Noun_Project).svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urbanplanning.setIcon(icon12)
        self.urbanplanning.setObjectName("urbanplanning")
        self.gridLayout_5.addWidget(self.urbanplanning, 5, 0, 1, 1)
        self.economics = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/dollar-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.economics.setIcon(icon13)
        self.economics.setObjectName("economics")
        self.gridLayout_5.addWidget(self.economics, 12, 1, 1, 1)
        self.infrastructure = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/images/md_infrastructure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infrastructure.setIcon(icon14)
        self.infrastructure.setObjectName("infrastructure")
        self.gridLayout_5.addWidget(self.infrastructure, 7, 0, 1, 1)
        self.spatialsetup = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.spatialsetup.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/Data-Grid-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spatialsetup.setIcon(icon15)
        self.spatialsetup.setCheckable(True)
        self.spatialsetup.setChecked(True)
        self.spatialsetup.setTristate(False)
        self.spatialsetup.setObjectName("spatialsetup")
        self.gridLayout_5.addWidget(self.spatialsetup, 1, 0, 1, 1)
        self.microclimate = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/temperature-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.microclimate.setIcon(icon16)
        self.microclimate.setObjectName("microclimate")
        self.gridLayout_5.addWidget(self.microclimate, 11, 1, 1, 1)
        self.descr_lbl2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descr_lbl2.setObjectName("descr_lbl2")
        self.gridLayout_5.addWidget(self.descr_lbl2, 0, 0, 1, 1)
        self.urbandynamics = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/Transport-Road-Worker-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urbandynamics.setIcon(icon17)
        self.urbandynamics.setObjectName("urbandynamics")
        self.gridLayout_5.addWidget(self.urbandynamics, 3, 1, 1, 1)
        self.descr_lbl4_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descr_lbl4_2.setObjectName("descr_lbl4_2")
        self.gridLayout_5.addWidget(self.descr_lbl4_2, 6, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/palette-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_widget.addTab(self.module_tab, icon18, "")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.data_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.datalibrary = QtWidgets.QWidget(self.data_tab)
        self.datalibrary.setObjectName("datalibrary")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.datalibrary)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.datalibrary_tree = QtWidgets.QTreeWidget(self.datalibrary)
        self.datalibrary_tree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datalibrary_tree.setObjectName("datalibrary_tree")
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.datalibrary_tree.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.datalibrary_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.datalibrary_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.datalibrary_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_4.addWidget(self.datalibrary_tree)
        self.horizontalLayout_4.addWidget(self.datalibrary)
        self.scenariodata = QtWidgets.QWidget(self.data_tab)
        self.scenariodata.setMinimumSize(QtCore.QSize(200, 0))
        self.scenariodata.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scenariodata.setObjectName("scenariodata")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scenariodata)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scenariodata_tree = QtWidgets.QTreeWidget(self.scenariodata)
        self.scenariodata_tree.setObjectName("scenariodata_tree")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scenariodata_tree.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.scenariodata_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.scenariodata_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.scenariodata_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_3.addWidget(self.scenariodata_tree)
        self.add_to_button = QtWidgets.QPushButton(self.scenariodata)
        self.add_to_button.setObjectName("add_to_button")
        self.verticalLayout_3.addWidget(self.add_to_button)
        self.remove_from_button = QtWidgets.QPushButton(self.scenariodata)
        self.remove_from_button.setObjectName("remove_from_button")
        self.verticalLayout_3.addWidget(self.remove_from_button)
        self.horizontalLayout_4.addWidget(self.scenariodata)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/Misc-Database-3-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_widget.addTab(self.data_tab, icon19, "")
        self.output_tab = QtWidgets.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.output_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.naming_convention = QtWidgets.QWidget(self.output_tab)
        self.naming_convention.setObjectName("naming_convention")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.naming_convention)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.naming_lbl = QtWidgets.QLabel(self.naming_convention)
        self.naming_lbl.setObjectName("naming_lbl")
        self.gridLayout_2.addWidget(self.naming_lbl, 0, 0, 1, 1)
        self.naming_line = QtWidgets.QLineEdit(self.naming_convention)
        self.naming_line.setEnabled(True)
        self.naming_line.setReadOnly(False)
        self.naming_line.setObjectName("naming_line")
        self.gridLayout_2.addWidget(self.naming_line, 0, 1, 1, 1)
        self.naming_check = QtWidgets.QCheckBox(self.naming_convention)
        self.naming_check.setObjectName("naming_check")
        self.gridLayout_2.addWidget(self.naming_check, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.naming_convention)
        spacerItem4 = QtWidgets.QSpacerItem(20, 260, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.naming_convention.raise_()
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_widget.addTab(self.output_tab, icon20, "")
        self.verticalLayout.addWidget(self.setup_widget)
        self.footer = QtWidgets.QWidget(NewScenarioDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.create_button = QtWidgets.QToolButton(self.footer)
        self.create_button.setMinimumSize(QtCore.QSize(75, 20))
        self.create_button.setObjectName("create_button")
        self.horizontalLayout_2.addWidget(self.create_button)
        self.clear_button = QtWidgets.QToolButton(self.footer)
        self.clear_button.setMinimumSize(QtCore.QSize(75, 0))
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.cancel_button = QtWidgets.QPushButton(self.footer)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(NewScenarioDialog)
        self.setup_widget.setCurrentIndex(0)
        self.cancel_button.clicked.connect(NewScenarioDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewScenarioDialog)
        NewScenarioDialog.setTabOrder(self.name_box, self.static_radio)
        NewScenarioDialog.setTabOrder(self.static_radio, self.benchmark_radio)
        NewScenarioDialog.setTabOrder(self.benchmark_radio, self.dynamic_radio)
        NewScenarioDialog.setTabOrder(self.dynamic_radio, self.datalibrary_tree)
        NewScenarioDialog.setTabOrder(self.datalibrary_tree, self.scenariodata_tree)
        NewScenarioDialog.setTabOrder(self.scenariodata_tree, self.add_to_button)
        NewScenarioDialog.setTabOrder(self.add_to_button, self.remove_from_button)
        NewScenarioDialog.setTabOrder(self.remove_from_button, self.naming_line)
        NewScenarioDialog.setTabOrder(self.naming_line, self.create_button)
        NewScenarioDialog.setTabOrder(self.create_button, self.clear_button)
        NewScenarioDialog.setTabOrder(self.clear_button, self.cancel_button)

    def retranslateUi(self, NewScenarioDialog):
        _translate = QtCore.QCoreApplication.translate
        NewScenarioDialog.setWindowTitle(_translate("NewScenarioDialog", "Add Data..."))
        self.title.setText(_translate("NewScenarioDialog", "Create New Scenario"))
        self.subtitle.setText(_translate("NewScenarioDialog", "Customize the simulation type and modules."))
        self.name_box.setText(_translate("NewScenarioDialog", "(enter scenario name)"))
        self.name_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.name_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Scenario Name:</span></p></body></html>"))
        self.boundary_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.boundary_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Simulation Boundary:</span></p></body></html>"))
        self.boundary_combo.setItemText(0, _translate("NewScenarioDialog", "(select simulation boundary)"))
        self.simtype_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.simtype_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Simulation Type:</span></p></body></html>"))
        self.static_radio.setText(_translate("NewScenarioDialog", "Static"))
        self.benchmark_radio.setText(_translate("NewScenarioDialog", "Benchmark"))
        self.dynamic_radio.setText(_translate("NewScenarioDialog", "Dynamic"))
        self.narrative_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.narrative_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p>Provide some details on the scenario</p></body></html>"))
        self.narrative_box.setPlainText(_translate("NewScenarioDialog", "(enter scenario description)"))
        self.setup_widget.setTabText(self.setup_widget.indexOf(self.narrative_tab), _translate("NewScenarioDialog", "Narrative"))
        self.simyear_lbl2.setText(_translate("NewScenarioDialog", "to"))
        self.timestep_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.timestep_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p>Dynamic Time Step:</p></body></html>"))
        self.timestep_spin.setSuffix(_translate("NewScenarioDialog", " years"))
        self.simyear_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.simyear_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p>Simulation Period:</p></body></html>"))
        self.timestep_irregular.setText(_translate("NewScenarioDialog", "Irregular"))
        self.timestep_irregular_button.setText(_translate("NewScenarioDialog", "Select Years to Run"))
        self.benchmark_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.benchmark_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p>Benchmark Iterations:</p></body></html>"))
        self.setup_widget.setTabText(self.setup_widget.indexOf(self.details_tab), _translate("NewScenarioDialog", "Details"))
        self.descr_lbl.setText(_translate("NewScenarioDialog", "Select the Modules you would like to include (you can selectively run modules later):"))
        self.descr_lbl3.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Urban Development</span></p></body></html>"))
        self.watercycle.setText(_translate("NewScenarioDialog", "Water Cycle"))
        self.descr_lbl4.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Environment Mapping</span></p></body></html>"))
        self.citydevelopment.setText(_translate("NewScenarioDialog", "Development Setup"))
        self.climate.setText(_translate("NewScenarioDialog", "Climate Setup"))
        self.flood.setText(_translate("NewScenarioDialog", "Flood Assessment"))
        self.spatialmapping.setText(_translate("NewScenarioDialog", "Spatial Analyst"))
        self.bluegreen.setText(_translate("NewScenarioDialog", "Blue-Green Systems"))
        self.descr_lbl5.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Evaluation</span></p></body></html>"))
        self.urbanplanning.setText(_translate("NewScenarioDialog", "Urban Form"))
        self.economics.setText(_translate("NewScenarioDialog", "Economic Valuation"))
        self.infrastructure.setText(_translate("NewScenarioDialog", "Water Infrastructure"))
        self.spatialsetup.setText(_translate("NewScenarioDialog", "Spatial Setup"))
        self.microclimate.setText(_translate("NewScenarioDialog", "Urban Microclimate"))
        self.descr_lbl2.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Data Processing</span></p></body></html>"))
        self.urbandynamics.setText(_translate("NewScenarioDialog", "Urban Dynamics"))
        self.descr_lbl4_2.setText(_translate("NewScenarioDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Infrastructure Planning</span></p></body></html>"))
        self.setup_widget.setTabText(self.setup_widget.indexOf(self.module_tab), _translate("NewScenarioDialog", "Customize Modules"))
        self.datalibrary_tree.headerItem().setText(0, _translate("NewScenarioDialog", "Project Data Library"))
        __sortingEnabled = self.datalibrary_tree.isSortingEnabled()
        self.datalibrary_tree.setSortingEnabled(False)
        self.datalibrary_tree.topLevelItem(0).setText(0, _translate("NewScenarioDialog", "Spatial Data"))
        self.datalibrary_tree.topLevelItem(0).child(0).setText(0, _translate("NewScenarioDialog", "Boundaries"))
        self.datalibrary_tree.topLevelItem(0).child(0).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(1).setText(0, _translate("NewScenarioDialog", "Built Infrastructure"))
        self.datalibrary_tree.topLevelItem(0).child(1).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(2).setText(0, _translate("NewScenarioDialog", "Elevation"))
        self.datalibrary_tree.topLevelItem(0).child(2).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(3).setText(0, _translate("NewScenarioDialog", "Employment"))
        self.datalibrary_tree.topLevelItem(0).child(3).child(0).setText(0, _translate("NewScenarioDialog", "<none>"))
        self.datalibrary_tree.topLevelItem(0).child(4).setText(0, _translate("NewScenarioDialog", "Land Use"))
        self.datalibrary_tree.topLevelItem(0).child(4).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(5).setText(0, _translate("NewScenarioDialog", "Locality Maps"))
        self.datalibrary_tree.topLevelItem(0).child(5).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(6).setText(0, _translate("NewScenarioDialog", "Overlays"))
        self.datalibrary_tree.topLevelItem(0).child(6).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(7).setText(0, _translate("NewScenarioDialog", "Population"))
        self.datalibrary_tree.topLevelItem(0).child(7).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(8).setText(0, _translate("NewScenarioDialog", "Soil"))
        self.datalibrary_tree.topLevelItem(0).child(8).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(0).child(9).setText(0, _translate("NewScenarioDialog", "Water Bodies"))
        self.datalibrary_tree.topLevelItem(0).child(9).child(0).setText(0, _translate("NewScenarioDialog", "<none>"))
        self.datalibrary_tree.topLevelItem(1).setText(0, _translate("NewScenarioDialog", "Time Series Data"))
        self.datalibrary_tree.topLevelItem(1).child(0).setText(0, _translate("NewScenarioDialog", "Rainfall"))
        self.datalibrary_tree.topLevelItem(1).child(0).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(1).child(1).setText(0, _translate("NewScenarioDialog", "Evapotranspiration"))
        self.datalibrary_tree.topLevelItem(1).child(1).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(1).child(2).setText(0, _translate("NewScenarioDialog", "Solar Radiation"))
        self.datalibrary_tree.topLevelItem(1).child(2).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(1).child(3).setText(0, _translate("NewScenarioDialog", "Temperature"))
        self.datalibrary_tree.topLevelItem(1).child(3).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.topLevelItem(2).setText(0, _translate("NewScenarioDialog", "Qualitative Data"))
        self.datalibrary_tree.topLevelItem(2).child(0).setText(0, _translate("NewScenarioDialog", "<no data>"))
        self.datalibrary_tree.setSortingEnabled(__sortingEnabled)
        self.scenariodata_tree.headerItem().setText(0, _translate("NewScenarioDialog", "Scenario Data Set"))
        __sortingEnabled = self.scenariodata_tree.isSortingEnabled()
        self.scenariodata_tree.setSortingEnabled(False)
        self.scenariodata_tree.topLevelItem(0).setText(0, _translate("NewScenarioDialog", "Spatial Data"))
        self.scenariodata_tree.topLevelItem(0).child(0).setText(0, _translate("NewScenarioDialog", "<none>"))
        self.scenariodata_tree.topLevelItem(1).setText(0, _translate("NewScenarioDialog", "Temporal Data"))
        self.scenariodata_tree.topLevelItem(1).child(0).setText(0, _translate("NewScenarioDialog", "<none>"))
        self.scenariodata_tree.topLevelItem(2).setText(0, _translate("NewScenarioDialog", "Qualitative Data"))
        self.scenariodata_tree.topLevelItem(2).child(0).setText(0, _translate("NewScenarioDialog", "<none>"))
        self.scenariodata_tree.setSortingEnabled(__sortingEnabled)
        self.add_to_button.setText(_translate("NewScenarioDialog", ">> Add to Scenario"))
        self.remove_from_button.setText(_translate("NewScenarioDialog", "<< Remove from Scenario"))
        self.setup_widget.setTabText(self.setup_widget.indexOf(self.data_tab), _translate("NewScenarioDialog", "Select Data"))
        self.naming_lbl.setWhatsThis(_translate("NewScenarioDialog", "Rainfall time series, obtain data from weather station or climate authority of your city. Time series should be in rainfall depth and have units millimetres."))
        self.naming_lbl.setText(_translate("NewScenarioDialog", "<html><head/><body><p>File naming convention:</p></body></html>"))
        self.naming_line.setText(_translate("NewScenarioDialog", "(enter a naming convention for outputs)"))
        self.naming_check.setText(_translate("NewScenarioDialog", "Use scenario name (spaces become underscores)"))
        self.setup_widget.setTabText(self.setup_widget.indexOf(self.output_tab), _translate("NewScenarioDialog", "Output"))
        self.create_button.setText(_translate("NewScenarioDialog", "Create"))
        self.clear_button.setText(_translate("NewScenarioDialog", "Clear"))
        self.cancel_button.setText(_translate("NewScenarioDialog", "Cancel"))
from . import ubeats_rc
