# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openprojectdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpenProjectDialog(object):
    def setupUi(self, OpenProjectDialog):
        OpenProjectDialog.setObjectName("OpenProjectDialog")
        OpenProjectDialog.resize(586, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenProjectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(OpenProjectDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/open-file-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.recentproject_title_3 = QtWidgets.QLabel(OpenProjectDialog)
        self.recentproject_title_3.setObjectName("recentproject_title_3")
        self.verticalLayout.addWidget(self.recentproject_title_3)
        self.path_widget = QtWidgets.QWidget(OpenProjectDialog)
        self.path_widget.setObjectName("path_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.path_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projpath_button = QtWidgets.QPushButton(self.path_widget)
        self.projpath_button.setObjectName("projpath_button")
        self.gridLayout_3.addWidget(self.projpath_button, 1, 1, 1, 1)
        self.projpath_line = QtWidgets.QLineEdit(self.path_widget)
        self.projpath_line.setEnabled(True)
        self.projpath_line.setMinimumSize(QtCore.QSize(463, 0))
        self.projpath_line.setReadOnly(True)
        self.projpath_line.setObjectName("projpath_line")
        self.gridLayout_3.addWidget(self.projpath_line, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.path_widget)
        self.recentproject_title_2 = QtWidgets.QLabel(OpenProjectDialog)
        self.recentproject_title_2.setObjectName("recentproject_title_2")
        self.verticalLayout.addWidget(self.recentproject_title_2)
        self.path_widget_2 = QtWidgets.QWidget(OpenProjectDialog)
        self.path_widget_2.setObjectName("path_widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.path_widget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.path_widget_3 = QtWidgets.QWidget(self.path_widget_2)
        self.path_widget_3.setObjectName("path_widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.path_widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_button = QtWidgets.QPushButton(self.path_widget_3)
        self.info_button.setMinimumSize(QtCore.QSize(0, 0))
        self.info_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.info_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Info-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_button.setIcon(icon)
        self.info_button.setIconSize(QtCore.QSize(25, 25))
        self.info_button.setObjectName("info_button")
        self.verticalLayout_2.addWidget(self.info_button)
        self.import_button = QtWidgets.QPushButton(self.path_widget_3)
        self.import_button.setMinimumSize(QtCore.QSize(0, 0))
        self.import_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.import_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/import-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_button.setIcon(icon1)
        self.import_button.setIconSize(QtCore.QSize(25, 25))
        self.import_button.setObjectName("import_button")
        self.verticalLayout_2.addWidget(self.import_button)
        self.export_button = QtWidgets.QPushButton(self.path_widget_3)
        self.export_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_button.setIcon(icon2)
        self.export_button.setIconSize(QtCore.QSize(25, 25))
        self.export_button.setObjectName("export_button")
        self.verticalLayout_2.addWidget(self.export_button)
        self.delete_button = QtWidgets.QPushButton(self.path_widget_3)
        self.delete_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/delete-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon3)
        self.delete_button.setIconSize(QtCore.QSize(25, 25))
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_2.addWidget(self.delete_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.path_widget_3, 1, 1, 1, 1)
        self.project_table = QtWidgets.QTableWidget(self.path_widget_2)
        self.project_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.project_table.setObjectName("project_table")
        self.project_table.setColumnCount(3)
        self.project_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.project_table, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.path_widget_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(OpenProjectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OpenProjectDialog)
        self.buttonBox.accepted.connect(OpenProjectDialog.accept)
        self.buttonBox.rejected.connect(OpenProjectDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OpenProjectDialog)

    def retranslateUi(self, OpenProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        OpenProjectDialog.setWindowTitle(_translate("OpenProjectDialog", "Open Existing Project"))
        self.subtitle.setText(_translate("OpenProjectDialog", "Select a recent project or browse for a project folder..."))
        self.title.setText(_translate("OpenProjectDialog", "Open an existing project..."))
        self.recentproject_title_3.setText(_translate("OpenProjectDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Open an existing Project Folder</span></p></body></html>"))
        self.projpath_button.setText(_translate("OpenProjectDialog", "Browse..."))
        self.projpath_line.setText(_translate("OpenProjectDialog", "<none>"))
        self.recentproject_title_2.setText(_translate("OpenProjectDialog", "<html><head/><body><p><span style=\" font-weight:600;\">or select a Recent Project</span></p></body></html>"))
        self.info_button.setToolTip(_translate("OpenProjectDialog", "<html><head/><body><p>Project Info</p></body></html>"))
        self.import_button.setToolTip(_translate("OpenProjectDialog", "<html><head/><body><p>Import Project</p></body></html>"))
        self.export_button.setToolTip(_translate("OpenProjectDialog", "<html><head/><body><p>Export Selected Project</p></body></html>"))
        self.delete_button.setToolTip(_translate("OpenProjectDialog", "<html><head/><body><p>Delete Project</p></body></html>"))
        item = self.project_table.horizontalHeaderItem(0)
        item.setText(_translate("OpenProjectDialog", "Project Name"))
        item = self.project_table.horizontalHeaderItem(1)
        item.setText(_translate("OpenProjectDialog", "Creator"))
        item = self.project_table.horizontalHeaderItem(2)
        item.setText(_translate("OpenProjectDialog", "Path"))

import ubeats_rc
