# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openprojectdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpenProjectDialog(object):
    def setupUi(self, OpenProjectDialog):
        OpenProjectDialog.setObjectName("OpenProjectDialog")
        OpenProjectDialog.resize(629, 401)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenProjectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(OpenProjectDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/open-file-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.recentproject_title = QtWidgets.QLabel(OpenProjectDialog)
        self.recentproject_title.setObjectName("recentproject_title")
        self.verticalLayout.addWidget(self.recentproject_title)
        self.project_table = QtWidgets.QTableWidget(OpenProjectDialog)
        self.project_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.project_table.setObjectName("project_table")
        self.project_table.setColumnCount(3)
        self.project_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.project_table)
        self.path_widget = QtWidgets.QWidget(OpenProjectDialog)
        self.path_widget.setObjectName("path_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.path_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projpath_lbl = QtWidgets.QLabel(self.path_widget)
        self.projpath_lbl.setObjectName("projpath_lbl")
        self.gridLayout_3.addWidget(self.projpath_lbl, 1, 0, 1, 1)
        self.projpath_button = QtWidgets.QPushButton(self.path_widget)
        self.projpath_button.setObjectName("projpath_button")
        self.gridLayout_3.addWidget(self.projpath_button, 1, 2, 1, 1)
        self.projpath_line = QtWidgets.QLineEdit(self.path_widget)
        self.projpath_line.setEnabled(False)
        self.projpath_line.setReadOnly(True)
        self.projpath_line.setObjectName("projpath_line")
        self.gridLayout_3.addWidget(self.projpath_line, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.path_widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(OpenProjectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OpenProjectDialog)
        self.buttonBox.accepted.connect(OpenProjectDialog.accept)
        self.buttonBox.rejected.connect(OpenProjectDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OpenProjectDialog)

    def retranslateUi(self, OpenProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        OpenProjectDialog.setWindowTitle(_translate("OpenProjectDialog", "Open Existing Project"))
        self.subtitle.setText(_translate("OpenProjectDialog", "Select a recent project or browse for a project folder..."))
        self.title.setText(_translate("OpenProjectDialog", "Open an existing project..."))
        self.recentproject_title.setText(_translate("OpenProjectDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Select a Recent Project</span></p></body></html>"))
        item = self.project_table.horizontalHeaderItem(0)
        item.setText(_translate("OpenProjectDialog", "Project Name"))
        item = self.project_table.horizontalHeaderItem(1)
        item.setText(_translate("OpenProjectDialog", "Creator"))
        item = self.project_table.horizontalHeaderItem(2)
        item.setText(_translate("OpenProjectDialog", "Path"))
        self.projpath_lbl.setText(_translate("OpenProjectDialog", "Project Path"))
        self.projpath_button.setText(_translate("OpenProjectDialog", "Browse..."))
        self.projpath_line.setText(_translate("OpenProjectDialog", "<none>"))

import ubeats_rc
