# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(534, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(PreferencesDialog)
        self.header.setObjectName("header")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.header)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.title_logo = QtWidgets.QLabel(self.header)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/Settings-icon (1).png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_12.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_12.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.header)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_12.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.header)
        self.options_tabs = QtWidgets.QTabWidget(PreferencesDialog)
        self.options_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.options_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.options_tabs.setObjectName("options_tabs")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.general_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.general_scrollArea = QtWidgets.QScrollArea(self.general_tab)
        self.general_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.general_scrollArea.setWidgetResizable(True)
        self.general_scrollArea.setObjectName("general_scrollArea")
        self.general_scrollAreaContents = QtWidgets.QWidget()
        self.general_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 473, 476))
        self.general_scrollAreaContents.setObjectName("general_scrollAreaContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.general_scrollAreaContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.user_details = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.user_details.setObjectName("user_details")
        self.verticalLayout_14.addWidget(self.user_details)
        self.user_details_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.user_details_widget.setObjectName("user_details_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.user_details_widget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.modelleraffil_line = QtWidgets.QLineEdit(self.user_details_widget)
        self.modelleraffil_line.setObjectName("modelleraffil_line")
        self.gridLayout.addWidget(self.modelleraffil_line, 1, 1, 1, 1)
        self.modellername_lbl = QtWidgets.QLabel(self.user_details_widget)
        self.modellername_lbl.setObjectName("modellername_lbl")
        self.gridLayout.addWidget(self.modellername_lbl, 0, 0, 1, 1)
        self.modellername_line = QtWidgets.QLineEdit(self.user_details_widget)
        self.modellername_line.setObjectName("modellername_line")
        self.gridLayout.addWidget(self.modellername_line, 0, 1, 1, 1)
        self.modelleraffil_lbl = QtWidgets.QLabel(self.user_details_widget)
        self.modelleraffil_lbl.setObjectName("modelleraffil_lbl")
        self.gridLayout.addWidget(self.modelleraffil_lbl, 1, 0, 1, 1)
        self.projectlog_lbl = QtWidgets.QLabel(self.user_details_widget)
        self.projectlog_lbl.setObjectName("projectlog_lbl")
        self.gridLayout.addWidget(self.projectlog_lbl, 2, 0, 1, 1)
        self.projectlog_widget = QtWidgets.QWidget(self.user_details_widget)
        self.projectlog_widget.setObjectName("projectlog_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.projectlog_widget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.projectlog_simple = QtWidgets.QRadioButton(self.projectlog_widget)
        self.projectlog_simple.setObjectName("projectlog_simple")
        self.horizontalLayout.addWidget(self.projectlog_simple)
        self.projectlog_compreh = QtWidgets.QRadioButton(self.projectlog_widget)
        self.projectlog_compreh.setObjectName("projectlog_compreh")
        self.horizontalLayout.addWidget(self.projectlog_compreh)
        self.gridLayout.addWidget(self.projectlog_widget, 2, 1, 1, 1)
        self.verticalLayout_14.addWidget(self.user_details_widget)
        self.language = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.language.setObjectName("language")
        self.verticalLayout_14.addWidget(self.language)
        self.language_sub = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.language_sub.setObjectName("language_sub")
        self.verticalLayout_14.addWidget(self.language_sub)
        self.language_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.language_widget.setObjectName("language_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.language_widget)
        self.gridLayout_7.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lang_lbl = QtWidgets.QLabel(self.language_widget)
        self.lang_lbl.setObjectName("lang_lbl")
        self.gridLayout_7.addWidget(self.lang_lbl, 1, 0, 1, 1)
        self.lang_combo = QtWidgets.QComboBox(self.language_widget)
        self.lang_combo.setObjectName("lang_combo")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.gridLayout_7.addWidget(self.lang_combo, 1, 1, 1, 1)
        self.verticalLayout_14.addWidget(self.language_widget)
        self.location = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.location.setObjectName("location")
        self.verticalLayout_14.addWidget(self.location)
        self.location_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.location_widget.setObjectName("location_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.location_widget)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.country_combo = QtWidgets.QComboBox(self.location_widget)
        self.country_combo.setObjectName("country_combo")
        self.country_combo.addItem("")
        self.gridLayout_2.addWidget(self.country_combo, 0, 2, 1, 1)
        self.location_lbl = QtWidgets.QLabel(self.location_widget)
        self.location_lbl.setObjectName("location_lbl")
        self.gridLayout_2.addWidget(self.location_lbl, 1, 0, 1, 1)
        self.country_lbl = QtWidgets.QLabel(self.location_widget)
        self.country_lbl.setObjectName("country_lbl")
        self.gridLayout_2.addWidget(self.country_lbl, 0, 0, 1, 1)
        self.location_combo = QtWidgets.QComboBox(self.location_widget)
        self.location_combo.setObjectName("location_combo")
        self.location_combo.addItem("")
        self.gridLayout_2.addWidget(self.location_combo, 1, 2, 1, 1)
        self.verticalLayout_14.addWidget(self.location_widget)
        self.path = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.path.setObjectName("path")
        self.verticalLayout_14.addWidget(self.path)
        self.path_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.path_widget.setObjectName("path_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.path_widget)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projpath_line = QtWidgets.QLineEdit(self.path_widget)
        self.projpath_line.setReadOnly(True)
        self.projpath_line.setObjectName("projpath_line")
        self.gridLayout_3.addWidget(self.projpath_line, 0, 1, 1, 1)
        self.temppath_lbl = QtWidgets.QLabel(self.path_widget)
        self.temppath_lbl.setObjectName("temppath_lbl")
        self.gridLayout_3.addWidget(self.temppath_lbl, 1, 0, 1, 1)
        self.projpath_lbl = QtWidgets.QLabel(self.path_widget)
        self.projpath_lbl.setObjectName("projpath_lbl")
        self.gridLayout_3.addWidget(self.projpath_lbl, 0, 0, 1, 1)
        self.projpath_button = QtWidgets.QPushButton(self.path_widget)
        self.projpath_button.setObjectName("projpath_button")
        self.gridLayout_3.addWidget(self.projpath_button, 0, 2, 1, 1)
        self.temppath_line = QtWidgets.QLineEdit(self.path_widget)
        self.temppath_line.setReadOnly(True)
        self.temppath_line.setObjectName("temppath_line")
        self.gridLayout_3.addWidget(self.temppath_line, 1, 1, 1, 1)
        self.temppath_button = QtWidgets.QPushButton(self.path_widget)
        self.temppath_button.setObjectName("temppath_button")
        self.gridLayout_3.addWidget(self.temppath_button, 1, 2, 1, 1)
        self.temppath_check = QtWidgets.QCheckBox(self.path_widget)
        self.temppath_check.setObjectName("temppath_check")
        self.gridLayout_3.addWidget(self.temppath_check, 2, 1, 1, 1)
        self.verticalLayout_14.addWidget(self.path_widget)
        self.project_settings_title = QtWidgets.QLabel(self.general_scrollAreaContents)
        self.project_settings_title.setObjectName("project_settings_title")
        self.verticalLayout_14.addWidget(self.project_settings_title)
        self.project_settings_widget = QtWidgets.QWidget(self.general_scrollAreaContents)
        self.project_settings_widget.setObjectName("project_settings_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.project_settings_widget)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.simboundary_featcount_spin = QtWidgets.QSpinBox(self.project_settings_widget)
        self.simboundary_featcount_spin.setMinimum(10)
        self.simboundary_featcount_spin.setMaximum(100)
        self.simboundary_featcount_spin.setProperty("value", 100)
        self.simboundary_featcount_spin.setObjectName("simboundary_featcount_spin")
        self.gridLayout_4.addWidget(self.simboundary_featcount_spin, 0, 1, 1, 1)
        self.simboundary_featcount_lbl = QtWidgets.QLabel(self.project_settings_widget)
        self.simboundary_featcount_lbl.setObjectName("simboundary_featcount_lbl")
        self.gridLayout_4.addWidget(self.simboundary_featcount_lbl, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_14.addWidget(self.project_settings_widget)
        self.verticalLayout_2.addLayout(self.verticalLayout_14)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.general_scrollArea.setWidget(self.general_scrollAreaContents)
        self.verticalLayout_3.addWidget(self.general_scrollArea)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Info-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.general_tab, icon, "")
        self.appearance = QtWidgets.QWidget()
        self.appearance.setObjectName("appearance")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.appearance)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.general_scrollArea_2 = QtWidgets.QScrollArea(self.appearance)
        self.general_scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.general_scrollArea_2.setWidgetResizable(True)
        self.general_scrollArea_2.setObjectName("general_scrollArea_2")
        self.general_scrollAreaContents_2 = QtWidgets.QWidget()
        self.general_scrollAreaContents_2.setGeometry(QtCore.QRect(0, 0, 473, 462))
        self.general_scrollAreaContents_2.setObjectName("general_scrollAreaContents_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.general_scrollAreaContents_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.appearance_2 = QtWidgets.QLabel(self.general_scrollAreaContents_2)
        self.appearance_2.setObjectName("appearance_2")
        self.verticalLayout_15.addWidget(self.appearance_2)
        self.appearance_widget_2 = QtWidgets.QWidget(self.general_scrollAreaContents_2)
        self.appearance_widget_2.setObjectName("appearance_widget_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.appearance_widget_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.consolets_combo_2 = QtWidgets.QComboBox(self.appearance_widget_2)
        self.consolets_combo_2.setMinimumSize(QtCore.QSize(0, 0))
        self.consolets_combo_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.consolets_combo_2.setObjectName("consolets_combo_2")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/colors/colours/black_hex000000.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consolets_combo_2.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/colors/colours/teal_hex255255.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consolets_combo_2.addItem(icon2, "")
        self.gridLayout_17.addWidget(self.consolets_combo_2, 3, 1, 1, 1)
        self.error_combo_2 = QtWidgets.QComboBox(self.appearance_widget_2)
        self.error_combo_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.error_combo_2.setObjectName("error_combo_2")
        self.error_combo_2.addItem(icon1, "")
        self.error_combo_2.addItem(icon2, "")
        self.gridLayout_17.addWidget(self.error_combo_2, 4, 1, 1, 1)
        self.bodytext_lbl_2 = QtWidgets.QLabel(self.appearance_widget_2)
        self.bodytext_lbl_2.setObjectName("bodytext_lbl_2")
        self.gridLayout_17.addWidget(self.bodytext_lbl_2, 1, 0, 1, 1)
        self.bodytext_combo_2 = QtWidgets.QComboBox(self.appearance_widget_2)
        self.bodytext_combo_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bodytext_combo_2.setObjectName("bodytext_combo_2")
        self.bodytext_combo_2.addItem(icon1, "")
        self.bodytext_combo_2.addItem(icon2, "")
        self.gridLayout_17.addWidget(self.bodytext_combo_2, 1, 1, 1, 1)
        self.consolets_lbl_2 = QtWidgets.QLabel(self.appearance_widget_2)
        self.consolets_lbl_2.setObjectName("consolets_lbl_2")
        self.gridLayout_17.addWidget(self.consolets_lbl_2, 3, 0, 1, 1)
        self.error_lbl_2 = QtWidgets.QLabel(self.appearance_widget_2)
        self.error_lbl_2.setObjectName("error_lbl_2")
        self.gridLayout_17.addWidget(self.error_lbl_2, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem2, 1, 2, 1, 1)
        self.verticalLayout_15.addWidget(self.appearance_widget_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_15)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.general_scrollArea_2.setWidget(self.general_scrollAreaContents_2)
        self.verticalLayout_13.addWidget(self.general_scrollArea_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/palette-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.appearance, icon3, "")
        self.simulation_tab = QtWidgets.QWidget()
        self.simulation_tab.setObjectName("simulation_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.simulation_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.simulation_scrollArea = QtWidgets.QScrollArea(self.simulation_tab)
        self.simulation_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.simulation_scrollArea.setWidgetResizable(True)
        self.simulation_scrollArea.setObjectName("simulation_scrollArea")
        self.simulation_scrollAreaContents = QtWidgets.QWidget()
        self.simulation_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 473, 462))
        self.simulation_scrollAreaContents.setObjectName("simulation_scrollAreaContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.simulation_scrollAreaContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.caching = QtWidgets.QLabel(self.simulation_scrollAreaContents)
        self.caching.setObjectName("caching")
        self.verticalLayout_16.addWidget(self.caching)
        self.caching_widget = QtWidgets.QWidget(self.simulation_scrollAreaContents)
        self.caching_widget.setObjectName("caching_widget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.caching_widget)
        self.gridLayout_13.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.caching_limit_lbl = QtWidgets.QLabel(self.caching_widget)
        self.caching_limit_lbl.setObjectName("caching_limit_lbl")
        self.gridLayout_13.addWidget(self.caching_limit_lbl, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem4, 0, 2, 1, 1)
        self.caching_limit_spin = QtWidgets.QSpinBox(self.caching_widget)
        self.caching_limit_spin.setSuffix("")
        self.caching_limit_spin.setMinimum(1)
        self.caching_limit_spin.setMaximum(10)
        self.caching_limit_spin.setSingleStep(1)
        self.caching_limit_spin.setProperty("value", 5)
        self.caching_limit_spin.setObjectName("caching_limit_spin")
        self.gridLayout_13.addWidget(self.caching_limit_spin, 0, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.caching_widget)
        self.activity = QtWidgets.QLabel(self.simulation_scrollAreaContents)
        self.activity.setObjectName("activity")
        self.verticalLayout_16.addWidget(self.activity)
        self.activity_widget = QtWidgets.QWidget(self.simulation_scrollAreaContents)
        self.activity_widget.setObjectName("activity_widget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.activity_widget)
        self.gridLayout_14.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem5, 0, 2, 1, 1)
        self.activity_thresh_spin = QtWidgets.QDoubleSpinBox(self.activity_widget)
        self.activity_thresh_spin.setMaximum(5.0)
        self.activity_thresh_spin.setSingleStep(0.01)
        self.activity_thresh_spin.setProperty("value", 0.1)
        self.activity_thresh_spin.setObjectName("activity_thresh_spin")
        self.gridLayout_14.addWidget(self.activity_thresh_spin, 0, 1, 1, 1)
        self.activity_thresh_lbl = QtWidgets.QLabel(self.activity_widget)
        self.activity_thresh_lbl.setObjectName("activity_thresh_lbl")
        self.gridLayout_14.addWidget(self.activity_thresh_lbl, 0, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.activity_widget)
        self.iterations = QtWidgets.QLabel(self.simulation_scrollAreaContents)
        self.iterations.setObjectName("iterations")
        self.verticalLayout_16.addWidget(self.iterations)
        self.iterations_widget = QtWidgets.QWidget(self.simulation_scrollAreaContents)
        self.iterations_widget.setObjectName("iterations_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.iterations_widget)
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tolerance_lbl = QtWidgets.QLabel(self.iterations_widget)
        self.tolerance_lbl.setObjectName("tolerance_lbl")
        self.gridLayout_5.addWidget(self.tolerance_lbl, 1, 0, 1, 1)
        self.numiter_lbl = QtWidgets.QLabel(self.iterations_widget)
        self.numiter_lbl.setObjectName("numiter_lbl")
        self.gridLayout_5.addWidget(self.numiter_lbl, 0, 0, 1, 1)
        self.numiter_spin = QtWidgets.QSpinBox(self.iterations_widget)
        self.numiter_spin.setSuffix("")
        self.numiter_spin.setMinimum(1000)
        self.numiter_spin.setMaximum(100000)
        self.numiter_spin.setSingleStep(1000)
        self.numiter_spin.setObjectName("numiter_spin")
        self.gridLayout_5.addWidget(self.numiter_spin, 0, 1, 1, 1)
        self.tolerance_spin = QtWidgets.QDoubleSpinBox(self.iterations_widget)
        self.tolerance_spin.setPrefix("")
        self.tolerance_spin.setDecimals(2)
        self.tolerance_spin.setMinimum(0.01)
        self.tolerance_spin.setMaximum(5.0)
        self.tolerance_spin.setSingleStep(0.01)
        self.tolerance_spin.setObjectName("tolerance_spin")
        self.gridLayout_5.addWidget(self.tolerance_spin, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout_16.addWidget(self.iterations_widget)
        self.modeldecisions = QtWidgets.QLabel(self.simulation_scrollAreaContents)
        self.modeldecisions.setObjectName("modeldecisions")
        self.verticalLayout_16.addWidget(self.modeldecisions)
        self.modeldecisions_sub = QtWidgets.QLabel(self.simulation_scrollAreaContents)
        self.modeldecisions_sub.setObjectName("modeldecisions_sub")
        self.verticalLayout_16.addWidget(self.modeldecisions_sub)
        self.modeldecisions_widget = QtWidgets.QWidget(self.simulation_scrollAreaContents)
        self.modeldecisions_widget.setObjectName("modeldecisions_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.modeldecisions_widget)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.decision_lbl = QtWidgets.QLabel(self.modeldecisions_widget)
        self.decision_lbl.setObjectName("decision_lbl")
        self.gridLayout_6.addWidget(self.decision_lbl, 1, 0, 1, 1)
        self.decision_combo = QtWidgets.QComboBox(self.modeldecisions_widget)
        self.decision_combo.setObjectName("decision_combo")
        self.decision_combo.addItem("")
        self.decision_combo.addItem("")
        self.decision_combo.addItem("")
        self.gridLayout_6.addWidget(self.decision_combo, 1, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.modeldecisions_widget)
        self.verticalLayout_6.addLayout(self.verticalLayout_16)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.simulation_scrollArea.setWidget(self.simulation_scrollAreaContents)
        self.verticalLayout_4.addWidget(self.simulation_scrollArea)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Play-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.simulation_tab, icon4, "")
        self.mapsettings_tab = QtWidgets.QWidget()
        self.mapsettings_tab.setObjectName("mapsettings_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mapsettings_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mapsettings_scrollArea = QtWidgets.QScrollArea(self.mapsettings_tab)
        self.mapsettings_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.mapsettings_scrollArea.setWidgetResizable(True)
        self.mapsettings_scrollArea.setObjectName("mapsettings_scrollArea")
        self.mapsettings_scrollAreaContents = QtWidgets.QWidget()
        self.mapsettings_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 473, 462))
        self.mapsettings_scrollAreaContents.setObjectName("mapsettings_scrollAreaContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mapsettings_scrollAreaContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.mapstyle = QtWidgets.QLabel(self.mapsettings_scrollAreaContents)
        self.mapstyle.setObjectName("mapstyle")
        self.verticalLayout_17.addWidget(self.mapstyle)
        self.mapstyle_widget = QtWidgets.QWidget(self.mapsettings_scrollAreaContents)
        self.mapstyle_widget.setObjectName("mapstyle_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mapstyle_widget)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mapstyle_subwidget = QtWidgets.QWidget(self.mapstyle_widget)
        self.mapstyle_subwidget.setObjectName("mapstyle_subwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.mapstyle_subwidget)
        self.gridLayout_8.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.mapstyle_lbl = QtWidgets.QLabel(self.mapstyle_subwidget)
        self.mapstyle_lbl.setObjectName("mapstyle_lbl")
        self.gridLayout_8.addWidget(self.mapstyle_lbl, 0, 0, 1, 1)
        self.tileserver_line = QtWidgets.QLineEdit(self.mapstyle_subwidget)
        self.tileserver_line.setObjectName("tileserver_line")
        self.gridLayout_8.addWidget(self.tileserver_line, 1, 2, 1, 1)
        self.offline_check = QtWidgets.QCheckBox(self.mapstyle_subwidget)
        self.offline_check.setObjectName("offline_check")
        self.gridLayout_8.addWidget(self.offline_check, 2, 2, 1, 1)
        self.mapstyle_combo = QtWidgets.QComboBox(self.mapstyle_subwidget)
        self.mapstyle_combo.setObjectName("mapstyle_combo")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.mapstyle_combo.addItem("")
        self.gridLayout_8.addWidget(self.mapstyle_combo, 0, 2, 1, 1)
        self.tileserver_lbl = QtWidgets.QLabel(self.mapstyle_subwidget)
        self.tileserver_lbl.setObjectName("tileserver_lbl")
        self.gridLayout_8.addWidget(self.tileserver_lbl, 1, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem8, 3, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.mapstyle_subwidget)
        self.mapstyle_pic = QtWidgets.QLabel(self.mapstyle_widget)
        self.mapstyle_pic.setMinimumSize(QtCore.QSize(100, 129))
        self.mapstyle_pic.setText("")
        self.mapstyle_pic.setPixmap(QtGui.QPixmap(":/media/map templates/gui/mt_opentopomap.png"))
        self.mapstyle_pic.setObjectName("mapstyle_pic")
        self.horizontalLayout_3.addWidget(self.mapstyle_pic)
        self.verticalLayout_17.addWidget(self.mapstyle_widget)
        self.datadisplay = QtWidgets.QLabel(self.mapsettings_scrollAreaContents)
        self.datadisplay.setObjectName("datadisplay")
        self.verticalLayout_17.addWidget(self.datadisplay)
        self.datadisplay_widget = QtWidgets.QWidget(self.mapsettings_scrollAreaContents)
        self.datadisplay_widget.setObjectName("datadisplay_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.datadisplay_widget)
        self.gridLayout_9.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.epsg_lbl = QtWidgets.QLabel(self.datadisplay_widget)
        self.epsg_lbl.setObjectName("epsg_lbl")
        self.gridLayout_9.addWidget(self.epsg_lbl, 2, 0, 1, 1)
        self.coords_combo = QtWidgets.QComboBox(self.datadisplay_widget)
        self.coords_combo.setEditable(True)
        self.coords_combo.setObjectName("coords_combo")
        self.coords_combo.addItem("")
        self.gridLayout_9.addWidget(self.coords_combo, 1, 1, 1, 1)
        self.epsg_line = QtWidgets.QLineEdit(self.datadisplay_widget)
        self.epsg_line.setObjectName("epsg_line")
        self.gridLayout_9.addWidget(self.epsg_line, 2, 1, 1, 1)
        self.coords_lbl_2 = QtWidgets.QLabel(self.datadisplay_widget)
        self.coords_lbl_2.setMinimumSize(QtCore.QSize(150, 0))
        self.coords_lbl_2.setObjectName("coords_lbl_2")
        self.gridLayout_9.addWidget(self.coords_lbl_2, 1, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.datadisplay_widget)
        self.verticalLayout_7.addLayout(self.verticalLayout_17)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.mapsettings_scrollArea.setWidget(self.mapsettings_scrollAreaContents)
        self.verticalLayout_9.addWidget(self.mapsettings_scrollArea)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/GISLayers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.mapsettings_tab, icon5, "")
        self.external_tab = QtWidgets.QWidget()
        self.external_tab.setObjectName("external_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.external_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.external_scrollArea = QtWidgets.QScrollArea(self.external_tab)
        self.external_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.external_scrollArea.setWidgetResizable(True)
        self.external_scrollArea.setObjectName("external_scrollArea")
        self.external_scrollAreaContents = QtWidgets.QWidget()
        self.external_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 473, 462))
        self.external_scrollAreaContents.setObjectName("external_scrollAreaContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.external_scrollAreaContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.externalprograms = QtWidgets.QLabel(self.external_scrollAreaContents)
        self.externalprograms.setObjectName("externalprograms")
        self.verticalLayout_18.addWidget(self.externalprograms)
        self.externalprograms_2 = QtWidgets.QWidget(self.external_scrollAreaContents)
        self.externalprograms_2.setObjectName("externalprograms_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.externalprograms_2)
        self.gridLayout_10.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.musicpath_button = QtWidgets.QPushButton(self.externalprograms_2)
        self.musicpath_button.setObjectName("musicpath_button")
        self.gridLayout_10.addWidget(self.musicpath_button, 2, 2, 1, 1)
        self.epanetpath_line = QtWidgets.QLineEdit(self.externalprograms_2)
        self.epanetpath_line.setReadOnly(True)
        self.epanetpath_line.setObjectName("epanetpath_line")
        self.gridLayout_10.addWidget(self.epanetpath_line, 0, 1, 1, 1)
        self.epanetpath_button = QtWidgets.QPushButton(self.externalprograms_2)
        self.epanetpath_button.setObjectName("epanetpath_button")
        self.gridLayout_10.addWidget(self.epanetpath_button, 0, 2, 1, 1)
        self.musicpath_lbl = QtWidgets.QLabel(self.externalprograms_2)
        self.musicpath_lbl.setObjectName("musicpath_lbl")
        self.gridLayout_10.addWidget(self.musicpath_lbl, 2, 0, 1, 1)
        self.epanetpath_lbl = QtWidgets.QLabel(self.externalprograms_2)
        self.epanetpath_lbl.setObjectName("epanetpath_lbl")
        self.gridLayout_10.addWidget(self.epanetpath_lbl, 0, 0, 1, 1)
        self.musicpath_line = QtWidgets.QLineEdit(self.externalprograms_2)
        self.musicpath_line.setReadOnly(True)
        self.musicpath_line.setObjectName("musicpath_line")
        self.gridLayout_10.addWidget(self.musicpath_line, 2, 1, 1, 1)
        self.swmmpath_lbl = QtWidgets.QLabel(self.externalprograms_2)
        self.swmmpath_lbl.setObjectName("swmmpath_lbl")
        self.gridLayout_10.addWidget(self.swmmpath_lbl, 1, 0, 1, 1)
        self.swmmpath_line = QtWidgets.QLineEdit(self.externalprograms_2)
        self.swmmpath_line.setReadOnly(True)
        self.swmmpath_line.setObjectName("swmmpath_line")
        self.gridLayout_10.addWidget(self.swmmpath_line, 1, 1, 1, 1)
        self.swmmpath_button = QtWidgets.QPushButton(self.externalprograms_2)
        self.swmmpath_button.setObjectName("swmmpath_button")
        self.gridLayout_10.addWidget(self.swmmpath_button, 1, 2, 1, 1)
        self.verticalLayout_18.addWidget(self.externalprograms_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_18)
        spacerItem10 = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.external_scrollArea.setWidget(self.external_scrollAreaContents)
        self.verticalLayout_5.addWidget(self.external_scrollArea)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.external_tab, icon6, "")
        self.online_tab = QtWidgets.QWidget()
        self.online_tab.setObjectName("online_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.online_tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.online_scrollArea = QtWidgets.QScrollArea(self.online_tab)
        self.online_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.online_scrollArea.setWidgetResizable(True)
        self.online_scrollArea.setObjectName("online_scrollArea")
        self.online_scrollAreaContents = QtWidgets.QWidget()
        self.online_scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 473, 462))
        self.online_scrollAreaContents.setObjectName("online_scrollAreaContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.online_scrollAreaContents)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.comingsoon = QtWidgets.QLabel(self.online_scrollAreaContents)
        self.comingsoon.setObjectName("comingsoon")
        self.verticalLayout_19.addWidget(self.comingsoon)
        self.comingsoon_widget = QtWidgets.QWidget(self.online_scrollAreaContents)
        self.comingsoon_widget.setObjectName("comingsoon_widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.comingsoon_widget)
        self.gridLayout_11.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.comingsoon_lbl = QtWidgets.QLabel(self.comingsoon_widget)
        self.comingsoon_lbl.setObjectName("comingsoon_lbl")
        self.gridLayout_11.addWidget(self.comingsoon_lbl, 0, 1, 1, 1)
        self.verticalLayout_19.addWidget(self.comingsoon_widget)
        self.verticalLayout_10.addLayout(self.verticalLayout_19)
        spacerItem11 = QtWidgets.QSpacerItem(20, 343, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.online_scrollArea.setWidget(self.online_scrollAreaContents)
        self.verticalLayout_11.addWidget(self.online_scrollArea)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Network-Globe-Connected-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_tabs.addTab(self.online_tab, icon7, "")
        self.verticalLayout.addWidget(self.options_tabs)
        self.footer = QtWidgets.QWidget(PreferencesDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.footer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.reset_button = QtWidgets.QPushButton(self.footer)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_2.addWidget(self.reset_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(PreferencesDialog)
        self.options_tabs.setCurrentIndex(0)
        self.lang_combo.setCurrentIndex(1)
        self.country_combo.setCurrentIndex(0)
        self.location_combo.setCurrentIndex(0)
        self.mapstyle_combo.setCurrentIndex(0)
        self.coords_combo.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.options_tabs, self.general_scrollArea)
        PreferencesDialog.setTabOrder(self.general_scrollArea, self.modellername_line)
        PreferencesDialog.setTabOrder(self.modellername_line, self.modelleraffil_line)
        PreferencesDialog.setTabOrder(self.modelleraffil_line, self.projectlog_simple)
        PreferencesDialog.setTabOrder(self.projectlog_simple, self.projectlog_compreh)
        PreferencesDialog.setTabOrder(self.projectlog_compreh, self.lang_combo)
        PreferencesDialog.setTabOrder(self.lang_combo, self.country_combo)
        PreferencesDialog.setTabOrder(self.country_combo, self.projpath_line)
        PreferencesDialog.setTabOrder(self.projpath_line, self.projpath_button)
        PreferencesDialog.setTabOrder(self.projpath_button, self.temppath_line)
        PreferencesDialog.setTabOrder(self.temppath_line, self.temppath_button)
        PreferencesDialog.setTabOrder(self.temppath_button, self.temppath_check)
        PreferencesDialog.setTabOrder(self.temppath_check, self.numiter_spin)
        PreferencesDialog.setTabOrder(self.numiter_spin, self.tolerance_spin)
        PreferencesDialog.setTabOrder(self.tolerance_spin, self.decision_combo)
        PreferencesDialog.setTabOrder(self.decision_combo, self.mapstyle_combo)
        PreferencesDialog.setTabOrder(self.mapstyle_combo, self.tileserver_line)
        PreferencesDialog.setTabOrder(self.tileserver_line, self.offline_check)
        PreferencesDialog.setTabOrder(self.offline_check, self.coords_combo)
        PreferencesDialog.setTabOrder(self.coords_combo, self.epsg_line)
        PreferencesDialog.setTabOrder(self.epsg_line, self.epanetpath_line)
        PreferencesDialog.setTabOrder(self.epanetpath_line, self.epanetpath_button)
        PreferencesDialog.setTabOrder(self.epanetpath_button, self.swmmpath_line)
        PreferencesDialog.setTabOrder(self.swmmpath_line, self.swmmpath_button)
        PreferencesDialog.setTabOrder(self.swmmpath_button, self.musicpath_line)
        PreferencesDialog.setTabOrder(self.musicpath_line, self.musicpath_button)
        PreferencesDialog.setTabOrder(self.musicpath_button, self.buttonBox)
        PreferencesDialog.setTabOrder(self.buttonBox, self.reset_button)
        PreferencesDialog.setTabOrder(self.reset_button, self.simulation_scrollArea)
        PreferencesDialog.setTabOrder(self.simulation_scrollArea, self.mapsettings_scrollArea)
        PreferencesDialog.setTabOrder(self.mapsettings_scrollArea, self.external_scrollArea)
        PreferencesDialog.setTabOrder(self.external_scrollArea, self.online_scrollArea)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.title.setText(_translate("PreferencesDialog", "Preferences"))
        self.subtitle.setText(_translate("PreferencesDialog", "Program configuration, simulation and display options..."))
        self.user_details.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">User Details</span></p></body></html>"))
        self.modellername_lbl.setText(_translate("PreferencesDialog", "Default Modeller Name: "))
        self.modelleraffil_lbl.setText(_translate("PreferencesDialog", "Default Affiliation:"))
        self.projectlog_lbl.setText(_translate("PreferencesDialog", "Project Log Style:"))
        self.projectlog_simple.setText(_translate("PreferencesDialog", "Simplified Log"))
        self.projectlog_compreh.setText(_translate("PreferencesDialog", "Comprehensive"))
        self.language.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Language Settings</span></p></body></html>"))
        self.language_sub.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-style:italic;\">(changes will be applied upon restart)</span></p></body></html>"))
        self.lang_lbl.setText(_translate("PreferencesDialog", "Interface Language:"))
        self.lang_combo.setItemText(0, _translate("PreferencesDialog", "Deutsch"))
        self.lang_combo.setItemText(1, _translate("PreferencesDialog", "English"))
        self.lang_combo.setItemText(2, _translate("PreferencesDialog", "Español"))
        self.lang_combo.setItemText(3, _translate("PreferencesDialog", "Français"))
        self.lang_combo.setItemText(4, _translate("PreferencesDialog", "Português"))
        self.lang_combo.setItemText(5, _translate("PreferencesDialog", "中文"))
        self.lang_combo.setItemText(6, _translate("PreferencesDialog", "日本語"))
        self.location.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Location Settings</span></p></body></html>"))
        self.country_combo.setItemText(0, _translate("PreferencesDialog", "(select country)"))
        self.location_lbl.setText(_translate("PreferencesDialog", "Default Closest City:"))
        self.country_lbl.setText(_translate("PreferencesDialog", "Default Country:"))
        self.location_combo.setItemText(0, _translate("PreferencesDialog", "(select city)"))
        self.path.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Path Settings</span></p></body></html>"))
        self.temppath_lbl.setText(_translate("PreferencesDialog", "Temp Directory:"))
        self.projpath_lbl.setText(_translate("PreferencesDialog", "Default Project Path:"))
        self.projpath_button.setText(_translate("PreferencesDialog", "Change..."))
        self.temppath_button.setText(_translate("PreferencesDialog", "Change..."))
        self.temppath_check.setText(_translate("PreferencesDialog", "Use Windows Default Temp Directory"))
        self.project_settings_title.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Project Management Settings</span></p></body></html>"))
        self.simboundary_featcount_lbl.setText(_translate("PreferencesDialog", "Simulation Boundary Feature Count Warning:"))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.general_tab), _translate("PreferencesDialog", "General"))
        self.appearance_2.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Text Appearance</span></p></body></html>"))
        self.consolets_combo_2.setItemText(0, _translate("PreferencesDialog", "Black"))
        self.consolets_combo_2.setItemText(1, _translate("PreferencesDialog", "Teal"))
        self.error_combo_2.setItemText(0, _translate("PreferencesDialog", "Black"))
        self.error_combo_2.setItemText(1, _translate("PreferencesDialog", "Teal"))
        self.bodytext_lbl_2.setText(_translate("PreferencesDialog", "Body Text Colour:"))
        self.bodytext_combo_2.setItemText(0, _translate("PreferencesDialog", "Black"))
        self.bodytext_combo_2.setItemText(1, _translate("PreferencesDialog", "Teal"))
        self.consolets_lbl_2.setText(_translate("PreferencesDialog", "Console Timestamp Text:"))
        self.error_lbl_2.setText(_translate("PreferencesDialog", "Errors and Warnings Text:"))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.appearance), _translate("PreferencesDialog", "Appearance"))
        self.caching.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Asset Caching</span></p></body></html>"))
        self.caching_limit_lbl.setText(_translate("PreferencesDialog", "Temporary Cache Limit [number of simulations]:"))
        self.activity.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Block Data Handling</span></p></body></html>"))
        self.activity_thresh_spin.setSuffix(_translate("PreferencesDialog", "%"))
        self.activity_thresh_lbl.setText(_translate("PreferencesDialog", "Global Threshold for minimum Block Activity:"))
        self.iterations.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Iterative Calculations</span></p></body></html>"))
        self.tolerance_lbl.setText(_translate("PreferencesDialog", "Global Tolerance Level for Convergence:"))
        self.numiter_lbl.setText(_translate("PreferencesDialog", "Maximum number of Technology Iterations:"))
        self.tolerance_spin.setSuffix(_translate("PreferencesDialog", "%"))
        self.modeldecisions.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Model Selection Heuristics</span></p></body></html>"))
        self.modeldecisions_sub.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Define default choices that the model should make when...</span></p></body></html>"))
        self.decision_lbl.setText(_translate("PreferencesDialog", "No suitable options are found:"))
        self.decision_combo.setItemText(0, _translate("PreferencesDialog", "Pick the closest options"))
        self.decision_combo.setItemText(1, _translate("PreferencesDialog", "Pick random options"))
        self.decision_combo.setItemText(2, _translate("PreferencesDialog", "Do not pick options"))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.simulation_tab), _translate("PreferencesDialog", "Simulation"))
        self.mapstyle.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Select Map Style</span></p></body></html>"))
        self.mapstyle_lbl.setText(_translate("PreferencesDialog", "Map Style:"))
        self.offline_check.setText(_translate("PreferencesDialog", "Offline Mode"))
        self.mapstyle_combo.setItemText(0, _translate("PreferencesDialog", "CartoDB Positron"))
        self.mapstyle_combo.setItemText(1, _translate("PreferencesDialog", "CartoDB DarkMatter"))
        self.mapstyle_combo.setItemText(2, _translate("PreferencesDialog", "ESRI World"))
        self.mapstyle_combo.setItemText(3, _translate("PreferencesDialog", "Open Topo Map"))
        self.mapstyle_combo.setItemText(4, _translate("PreferencesDialog", "Stamen (Toner)"))
        self.mapstyle_combo.setItemText(5, _translate("PreferencesDialog", "Stamen (Terrain)"))
        self.mapstyle_combo.setItemText(6, _translate("PreferencesDialog", "Stamen (Watercolor)"))
        self.tileserver_lbl.setText(_translate("PreferencesDialog", "Enter custom tileserver:"))
        self.datadisplay.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Spatial Data Handling</span></p></body></html>"))
        self.epsg_lbl.setText(_translate("PreferencesDialog", "EPSG Code:"))
        self.coords_combo.setItemText(0, _translate("PreferencesDialog", "(select coordinate system)"))
        self.coords_lbl_2.setText(_translate("PreferencesDialog", "Default Coordinate System:"))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.mapsettings_tab), _translate("PreferencesDialog", "Maps"))
        self.externalprograms.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">External Programs</span></p></body></html>"))
        self.musicpath_button.setText(_translate("PreferencesDialog", "Set..."))
        self.epanetpath_button.setText(_translate("PreferencesDialog", "Set..."))
        self.musicpath_lbl.setText(_translate("PreferencesDialog", "eWater MUSIC path:"))
        self.epanetpath_lbl.setText(_translate("PreferencesDialog", "EPANET2 path:"))
        self.swmmpath_lbl.setText(_translate("PreferencesDialog", "SWMM path:"))
        self.swmmpath_button.setText(_translate("PreferencesDialog", "Set..."))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.external_tab), _translate("PreferencesDialog", "External"))
        self.comingsoon.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Coming Soon...</span></p></body></html>"))
        self.comingsoon_lbl.setText(_translate("PreferencesDialog", "Features coming soon"))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.online_tab), _translate("PreferencesDialog", "Online"))
        self.reset_button.setText(_translate("PreferencesDialog", "Reset All"))
from . import ubeats_rc
