# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportoptions.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportingDialog(object):
    def setupUi(self, ReportingDialog):
        ReportingDialog.setObjectName("ReportingDialog")
        ReportingDialog.resize(482, 483)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../ubeatsicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReportingDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReportingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(ReportingDialog)
        self.title_widget.setObjectName("title_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.title_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_logo = QtWidgets.QLabel(self.title_widget)
        self.title_logo.setMinimumSize(QtCore.QSize(30, 30))
        self.title_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/Reports-icon.png"))
        self.title_logo.setScaledContents(True)
        self.title_logo.setObjectName("title_logo")
        self.gridLayout_3.addWidget(self.title_logo, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 1, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_3.addWidget(self.subtitle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.title_widget)
        self.scrollArea = QtWidgets.QScrollArea(ReportingDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 445, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.results = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/chart-search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.results.setIcon(icon1)
        self.results.setObjectName("results")
        self.gridLayout_2.addWidget(self.results, 14, 0, 1, 1)
        self.additional_filefolder = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.additional_filefolder.setObjectName("additional_filefolder")
        self.gridLayout_2.addWidget(self.additional_filefolder, 21, 1, 1, 1)
        self.scenario_modules = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.scenario_modules.setObjectName("scenario_modules")
        self.gridLayout_2.addWidget(self.scenario_modules, 10, 1, 1, 1)
        self.results_spatial = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.results_spatial.setObjectName("results_spatial")
        self.gridLayout_2.addWidget(self.results_spatial, 14, 1, 1, 1)
        self.results_strategies = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.results_strategies.setObjectName("results_strategies")
        self.gridLayout_2.addWidget(self.results_strategies, 16, 1, 1, 1)
        self.scenario_calibration = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.scenario_calibration.setObjectName("scenario_calibration")
        self.gridLayout_2.addWidget(self.scenario_calibration, 12, 1, 1, 1)
        self.scenario_setup = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.scenario_setup.setObjectName("scenario_setup")
        self.gridLayout_2.addWidget(self.scenario_setup, 11, 1, 1, 1)
        self.results_sysperf = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.results_sysperf.setObjectName("results_sysperf")
        self.gridLayout_2.addWidget(self.results_sysperf, 17, 1, 1, 1)
        self.scenario = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pages-brown-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scenario.setIcon(icon2)
        self.scenario.setObjectName("scenario")
        self.gridLayout_2.addWidget(self.scenario, 9, 0, 1, 1)
        self.scenario_inputdata = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.scenario_inputdata.setObjectName("scenario_inputdata")
        self.gridLayout_2.addWidget(self.scenario_inputdata, 9, 1, 1, 1)
        self.reportsections_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.reportsections_lbl.setObjectName("reportsections_lbl")
        self.gridLayout_2.addWidget(self.reportsections_lbl, 4, 0, 1, 1)
        self.additional = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.additional.setIcon(icon3)
        self.additional.setObjectName("additional")
        self.gridLayout_2.addWidget(self.additional, 19, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 8, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 13, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 18, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 18, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 13, 0, 1, 1)
        self.datalibrary = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Misc-Database-3-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datalibrary.setIcon(icon4)
        self.datalibrary.setObjectName("datalibrary")
        self.gridLayout_2.addWidget(self.datalibrary, 7, 0, 1, 1)
        self.additional_dataexport = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.additional_dataexport.setObjectName("additional_dataexport")
        self.gridLayout_2.addWidget(self.additional_dataexport, 22, 1, 1, 1)
        self.radioPlainText = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioPlainText.setObjectName("radioPlainText")
        self.gridLayout_2.addWidget(self.radioPlainText, 3, 1, 1, 1)
        self.projectdetails = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Info-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.projectdetails.setIcon(icon5)
        self.projectdetails.setObjectName("projectdetails")
        self.gridLayout_2.addWidget(self.projectdetails, 5, 0, 1, 1)
        self.additional_log = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.additional_log.setObjectName("additional_log")
        self.gridLayout_2.addWidget(self.additional_log, 19, 1, 1, 1)
        self.reportformat_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.reportformat_lbl.setObjectName("reportformat_lbl")
        self.gridLayout_2.addWidget(self.reportformat_lbl, 2, 0, 1, 1)
        self.reporttype_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.reporttype_lbl.setObjectName("reporttype_lbl")
        self.gridLayout_2.addWidget(self.reporttype_lbl, 1, 0, 1, 1)
        self.reporttype_combo = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.reporttype_combo.setObjectName("reporttype_combo")
        self.reporttype_combo.addItem("")
        self.reporttype_combo.addItem("")
        self.gridLayout_2.addWidget(self.reporttype_combo, 1, 1, 1, 1)
        self.radioHTML = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioHTML.setObjectName("radioHTML")
        self.gridLayout_2.addWidget(self.radioHTML, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.footer = QtWidgets.QWidget(ReportingDialog)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.create_button = QtWidgets.QToolButton(self.footer)
        self.create_button.setMinimumSize(QtCore.QSize(75, 0))
        self.create_button.setObjectName("create_button")
        self.horizontalLayout_2.addWidget(self.create_button)
        self.done_button = QtWidgets.QPushButton(self.footer)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(ReportingDialog)
        QtCore.QMetaObject.connectSlotsByName(ReportingDialog)
        ReportingDialog.setTabOrder(self.scrollArea, self.radioPlainText)
        ReportingDialog.setTabOrder(self.radioPlainText, self.projectdetails)
        ReportingDialog.setTabOrder(self.projectdetails, self.datalibrary)
        ReportingDialog.setTabOrder(self.datalibrary, self.scenario)
        ReportingDialog.setTabOrder(self.scenario, self.scenario_inputdata)
        ReportingDialog.setTabOrder(self.scenario_inputdata, self.scenario_modules)
        ReportingDialog.setTabOrder(self.scenario_modules, self.scenario_setup)
        ReportingDialog.setTabOrder(self.scenario_setup, self.scenario_calibration)
        ReportingDialog.setTabOrder(self.scenario_calibration, self.results)
        ReportingDialog.setTabOrder(self.results, self.results_spatial)
        ReportingDialog.setTabOrder(self.results_spatial, self.results_strategies)
        ReportingDialog.setTabOrder(self.results_strategies, self.results_sysperf)
        ReportingDialog.setTabOrder(self.results_sysperf, self.additional)
        ReportingDialog.setTabOrder(self.additional, self.additional_log)
        ReportingDialog.setTabOrder(self.additional_log, self.additional_filefolder)
        ReportingDialog.setTabOrder(self.additional_filefolder, self.additional_dataexport)
        ReportingDialog.setTabOrder(self.additional_dataexport, self.create_button)
        ReportingDialog.setTabOrder(self.create_button, self.done_button)

    def retranslateUi(self, ReportingDialog):
        _translate = QtCore.QCoreApplication.translate
        ReportingDialog.setWindowTitle(_translate("ReportingDialog", "Add Data..."))
        self.title.setText(_translate("ReportingDialog", "Reporting Options"))
        self.subtitle.setText(_translate("ReportingDialog", "Configure how UrbanBEATS should report results"))
        self.results.setText(_translate("ReportingDialog", "Results"))
        self.additional_filefolder.setText(_translate("ReportingDialog", "File and Folder Information"))
        self.scenario_modules.setText(_translate("ReportingDialog", "Module Details"))
        self.results_spatial.setText(_translate("ReportingDialog", "Spatial Analysis"))
        self.results_strategies.setText(_translate("ReportingDialog", "Strategies"))
        self.scenario_calibration.setText(_translate("ReportingDialog", "Calibration"))
        self.scenario_setup.setText(_translate("ReportingDialog", "Detailed Module Setup"))
        self.results_sysperf.setText(_translate("ReportingDialog", "System Performance"))
        self.scenario.setText(_translate("ReportingDialog", "Scenario Summary"))
        self.scenario_inputdata.setText(_translate("ReportingDialog", "Input Data"))
        self.reportsections_lbl.setText(_translate("ReportingDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Report Sections</span></p></body></html>"))
        self.additional.setText(_translate("ReportingDialog", "Additional Sections"))
        self.datalibrary.setText(_translate("ReportingDialog", "Data Library Summary"))
        self.additional_dataexport.setText(_translate("ReportingDialog", "Data Export Settings"))
        self.radioPlainText.setText(_translate("ReportingDialog", "Plain Text Report"))
        self.projectdetails.setText(_translate("ReportingDialog", "Project Details"))
        self.additional_log.setText(_translate("ReportingDialog", "Project Log"))
        self.reportformat_lbl.setText(_translate("ReportingDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Report Format</span></p></body></html>"))
        self.reporttype_lbl.setText(_translate("ReportingDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Report Type</span></p></body></html>"))
        self.reporttype_combo.setItemText(0, _translate("ReportingDialog", "Full Project Report"))
        self.reporttype_combo.setItemText(1, _translate("ReportingDialog", "Scenario Report"))
        self.radioHTML.setText(_translate("ReportingDialog", "HTML Report"))
        self.create_button.setText(_translate("ReportingDialog", "Create"))
        self.done_button.setText(_translate("ReportingDialog", "Done"))
from . import ubeats_rc
