# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urbanbeatscalibration.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResultsExplorer(object):
    def setupUi(self, ResultsExplorer):
        ResultsExplorer.setObjectName("ResultsExplorer")
        ResultsExplorer.resize(1300, 680)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ResultsExplorer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigation_widget = QtWidgets.QWidget(ResultsExplorer)
        self.navigation_widget.setObjectName("navigation_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.navigation_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.navigation_widget)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 65))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.subtitle = QtWidgets.QLabel(self.title_frame)
        self.subtitle.setWordWrap(True)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout.addWidget(self.subtitle, 1, 2, 1, 1)
        self.title = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 2, 1, 1)
        self.module_logo = QtWidgets.QLabel(self.title_frame)
        self.module_logo.setMinimumSize(QtCore.QSize(40, 40))
        self.module_logo.setMaximumSize(QtCore.QSize(40, 40))
        self.module_logo.setText("")
        self.module_logo.setPixmap(QtGui.QPixmap(":/icons/chart-search-icon.png"))
        self.module_logo.setScaledContents(True)
        self.module_logo.setObjectName("module_logo")
        self.gridLayout.addWidget(self.module_logo, 0, 0, 3, 1)
        self.verticalLayout.addWidget(self.title_frame)
        self.calibrationSettings = QtWidgets.QWidget(self.navigation_widget)
        self.calibrationSettings.setMinimumSize(QtCore.QSize(250, 0))
        self.calibrationSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calibrationSettings.setObjectName("calibrationSettings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.calibrationSettings)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calibset_title = QtWidgets.QLabel(self.calibrationSettings)
        self.calibset_title.setObjectName("calibset_title")
        self.verticalLayout_3.addWidget(self.calibset_title)
        self.set_param_lbl = QtWidgets.QLabel(self.calibrationSettings)
        self.set_param_lbl.setObjectName("set_param_lbl")
        self.verticalLayout_3.addWidget(self.set_param_lbl)
        self.set_param_combo = QtWidgets.QComboBox(self.calibrationSettings)
        self.set_param_combo.setObjectName("set_param_combo")
        self.set_param_combo.addItem("")
        self.set_param_combo.addItem("")
        self.set_param_combo.addItem("")
        self.set_param_combo.addItem("")
        self.set_param_combo.addItem("")
        self.set_param_combo.addItem("")
        self.verticalLayout_3.addWidget(self.set_param_combo)
        self.widget_2 = QtWidgets.QWidget(self.calibrationSettings)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.set_typetotal_radio = QtWidgets.QRadioButton(self.widget_2)
        self.set_typetotal_radio.setObjectName("set_typetotal_radio")
        self.horizontalLayout_3.addWidget(self.set_typetotal_radio)
        self.set_typeblock_radio = QtWidgets.QRadioButton(self.widget_2)
        self.set_typeblock_radio.setObjectName("set_typeblock_radio")
        self.horizontalLayout_3.addWidget(self.set_typeblock_radio)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.set_data_lbl_2 = QtWidgets.QLabel(self.calibrationSettings)
        self.set_data_lbl_2.setObjectName("set_data_lbl_2")
        self.verticalLayout_3.addWidget(self.set_data_lbl_2)
        self.set_totvalue_lbl = QtWidgets.QLabel(self.calibrationSettings)
        self.set_totvalue_lbl.setObjectName("set_totvalue_lbl")
        self.verticalLayout_3.addWidget(self.set_totvalue_lbl)
        self.set_totvalue_box = QtWidgets.QLineEdit(self.calibrationSettings)
        self.set_totvalue_box.setObjectName("set_totvalue_box")
        self.verticalLayout_3.addWidget(self.set_totvalue_box)
        self.set_gen_lbl = QtWidgets.QLabel(self.calibrationSettings)
        self.set_gen_lbl.setObjectName("set_gen_lbl")
        self.verticalLayout_3.addWidget(self.set_gen_lbl)
        self.set_gen_combo = QtWidgets.QComboBox(self.calibrationSettings)
        self.set_gen_combo.setObjectName("set_gen_combo")
        self.set_gen_combo.addItem("")
        self.set_gen_combo.addItem("")
        self.set_gen_combo.addItem("")
        self.set_gen_combo.addItem("")
        self.verticalLayout_3.addWidget(self.set_gen_combo)
        self.set_data_table = QtWidgets.QTableWidget(self.calibrationSettings)
        self.set_data_table.setGridStyle(QtCore.Qt.SolidLine)
        self.set_data_table.setObjectName("set_data_table")
        self.set_data_table.setColumnCount(2)
        self.set_data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.set_data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.set_data_table.setHorizontalHeaderItem(1, item)
        self.set_data_table.horizontalHeader().setVisible(True)
        self.set_data_table.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.set_data_table)
        self.widget_4 = QtWidgets.QWidget(self.calibrationSettings)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.set_data_export = QtWidgets.QPushButton(self.widget_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_data_export.setIcon(icon)
        self.set_data_export.setObjectName("set_data_export")
        self.horizontalLayout_5.addWidget(self.set_data_export)
        self.set_data_reset = QtWidgets.QPushButton(self.widget_4)
        self.set_data_reset.setObjectName("set_data_reset")
        self.horizontalLayout_5.addWidget(self.set_data_reset)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.calibrationSettings)
        self.horizontalLayout.addWidget(self.navigation_widget)
        self.widget = QtWidgets.QWidget(ResultsExplorer)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calibrationResults = QtWidgets.QWidget(self.widget)
        self.calibrationResults.setMinimumSize(QtCore.QSize(250, 0))
        self.calibrationResults.setObjectName("calibrationResults")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.calibrationResults)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.caliboutput_title = QtWidgets.QLabel(self.calibrationResults)
        self.caliboutput_title.setObjectName("caliboutput_title")
        self.verticalLayout_2.addWidget(self.caliboutput_title)
        self.out_box = QtWidgets.QPlainTextEdit(self.calibrationResults)
        self.out_box.setObjectName("out_box")
        self.verticalLayout_2.addWidget(self.out_box)
        self.widget_7 = QtWidgets.QWidget(self.calibrationResults)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.out_export = QtWidgets.QPushButton(self.widget_7)
        self.out_export.setIcon(icon)
        self.out_export.setObjectName("out_export")
        self.horizontalLayout_8.addWidget(self.out_export)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.set_eval_lbl = QtWidgets.QLabel(self.calibrationResults)
        self.set_eval_lbl.setObjectName("set_eval_lbl")
        self.verticalLayout_2.addWidget(self.set_eval_lbl)
        self.set_eval_nash = QtWidgets.QCheckBox(self.calibrationResults)
        self.set_eval_nash.setObjectName("set_eval_nash")
        self.verticalLayout_2.addWidget(self.set_eval_nash)
        self.set_eval_rmse = QtWidgets.QCheckBox(self.calibrationResults)
        self.set_eval_rmse.setObjectName("set_eval_rmse")
        self.verticalLayout_2.addWidget(self.set_eval_rmse)
        self.set_eval_error = QtWidgets.QCheckBox(self.calibrationResults)
        self.set_eval_error.setObjectName("set_eval_error")
        self.verticalLayout_2.addWidget(self.set_eval_error)
        self.plottype_lbl = QtWidgets.QLabel(self.calibrationResults)
        self.plottype_lbl.setObjectName("plottype_lbl")
        self.verticalLayout_2.addWidget(self.plottype_lbl)
        self.plottype_combo = QtWidgets.QComboBox(self.calibrationResults)
        self.plottype_combo.setObjectName("plottype_combo")
        self.plottype_combo.addItem("")
        self.plottype_combo.addItem("")
        self.plottype_combo.addItem("")
        self.verticalLayout_2.addWidget(self.plottype_combo)
        self.set_eval_11line = QtWidgets.QCheckBox(self.calibrationResults)
        self.set_eval_11line.setObjectName("set_eval_11line")
        self.verticalLayout_2.addWidget(self.set_eval_11line)
        self.horizontalLayout_2.addWidget(self.calibrationResults)
        self.calibrationView = QtWebKitWidgets.QWebView(self.widget)
        self.calibrationView.setMinimumSize(QtCore.QSize(550, 0))
        self.calibrationView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calibrationView.setUrl(QtCore.QUrl("about:blank"))
        self.calibrationView.setObjectName("calibrationView")
        self.horizontalLayout_2.addWidget(self.calibrationView)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ResultsExplorer)
        QtCore.QMetaObject.connectSlotsByName(ResultsExplorer)

    def retranslateUi(self, ResultsExplorer):
        _translate = QtCore.QCoreApplication.translate
        ResultsExplorer.setWindowTitle(_translate("ResultsExplorer", "UrbanBEATS Results Explorer"))
        self.subtitle.setText(_translate("ResultsExplorer", "Calibrate Spatial Model Outputs"))
        self.title.setText(_translate("ResultsExplorer", "<html><head/><body><p>Model Calibration Viewer</p></body></html>"))
        self.calibset_title.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Calibration Settings</span></p></body></html>"))
        self.set_param_lbl.setText(_translate("ResultsExplorer", "Select Parameter and Type of Calibration:"))
        self.set_param_combo.setItemText(0, _translate("ResultsExplorer", "<select parameter to calibrate>"))
        self.set_param_combo.setItemText(1, _translate("ResultsExplorer", "Impervious Area"))
        self.set_param_combo.setItemText(2, _translate("ResultsExplorer", "Residential Allotment Count"))
        self.set_param_combo.setItemText(3, _translate("ResultsExplorer", "Residential House Count"))
        self.set_param_combo.setItemText(4, _translate("ResultsExplorer", "Total Residential Roof Area"))
        self.set_param_combo.setItemText(5, _translate("ResultsExplorer", "Water Demand"))
        self.set_typetotal_radio.setText(_translate("ResultsExplorer", "Total Value"))
        self.set_typeblock_radio.setText(_translate("ResultsExplorer", "Block-by-block"))
        self.set_data_lbl_2.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Calibration Data</span></p></body></html>"))
        self.set_totvalue_lbl.setText(_translate("ResultsExplorer", "Enter Total Value (units [%]) :"))
        self.set_gen_lbl.setText(_translate("ResultsExplorer", "Create/Select Calibration Data Set:"))
        self.set_gen_combo.setItemText(0, _translate("ResultsExplorer", "Manual Data Entry..."))
        self.set_gen_combo.setItemText(1, _translate("ResultsExplorer", "Load Existing Data Set..."))
        self.set_gen_combo.setItemText(2, _translate("ResultsExplorer", "MW MUSIC Guide"))
        self.set_gen_combo.setItemText(3, _translate("ResultsExplorer", "Sponge Cities Guidelines"))
        self.set_data_table.setSortingEnabled(False)
        item = self.set_data_table.horizontalHeaderItem(0)
        item.setText(_translate("ResultsExplorer", "BlockID"))
        item = self.set_data_table.horizontalHeaderItem(1)
        item.setText(_translate("ResultsExplorer", "Observed"))
        self.set_data_export.setText(_translate("ResultsExplorer", "Export Data..."))
        self.set_data_reset.setText(_translate("ResultsExplorer", "Reset Table"))
        self.caliboutput_title.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Calibration Outputs</span></p></body></html>"))
        self.out_box.setPlainText(_translate("ResultsExplorer", "Results:"))
        self.out_export.setText(_translate("ResultsExplorer", "Export Results..."))
        self.set_eval_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Evaluation Statistics:</span></p></body></html>"))
        self.set_eval_nash.setText(_translate("ResultsExplorer", "Nash-Sutcliffe Coefficient"))
        self.set_eval_rmse.setText(_translate("ResultsExplorer", "Root Mean Squared Error"))
        self.set_eval_error.setText(_translate("ResultsExplorer", "Relative Errors"))
        self.plottype_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Select Plot Type:</span></p></body></html>"))
        self.plottype_combo.setItemText(0, _translate("ResultsExplorer", "Modelled vs. Observed"))
        self.plottype_combo.setItemText(1, _translate("ResultsExplorer", "Residual Plot"))
        self.plottype_combo.setItemText(2, _translate("ResultsExplorer", "Error Distribution"))
        self.set_eval_11line.setText(_translate("ResultsExplorer", "Display 1:1 Line?"))

from PyQt5 import QtWebKitWidgets
import ubeats_rc
