# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urbanbeatsresults.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultsExplorer(object):
    def setupUi(self, ResultsExplorer):
        ResultsExplorer.setObjectName("ResultsExplorer")
        ResultsExplorer.resize(1300, 680)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ResultsExplorer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigation_widget = QtWidgets.QWidget(ResultsExplorer)
        self.navigation_widget.setObjectName("navigation_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.navigation_widget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.navigation_widget)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 65))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.module_logo = QtWidgets.QLabel(self.title_frame)
        self.module_logo.setMinimumSize(QtCore.QSize(40, 40))
        self.module_logo.setMaximumSize(QtCore.QSize(40, 40))
        self.module_logo.setText("")
        self.module_logo.setPixmap(QtGui.QPixmap(":/icons/chart-search-icon.png"))
        self.module_logo.setScaledContents(True)
        self.module_logo.setObjectName("module_logo")
        self.gridLayout.addWidget(self.module_logo, 0, 0, 3, 1)
        self.title = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 2, 1, 1)
        self.subtitle = QtWidgets.QLabel(self.title_frame)
        self.subtitle.setWordWrap(False)
        self.subtitle.setObjectName("subtitle")
        self.gridLayout.addWidget(self.subtitle, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.title_frame)
        self.resultsNavigator = QtWidgets.QTabWidget(self.navigation_widget)
        self.resultsNavigator.setTabPosition(QtWidgets.QTabWidget.West)
        self.resultsNavigator.setObjectName("resultsNavigator")
        self.summary = QtWidgets.QWidget()
        self.summary.setObjectName("summary")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.summary)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.summary_scenario = QtWidgets.QLabel(self.summary)
        self.summary_scenario.setWordWrap(False)
        self.summary_scenario.setObjectName("summary_scenario")
        self.verticalLayout_3.addWidget(self.summary_scenario)
        self.summary_scenario_combo = QtWidgets.QComboBox(self.summary)
        self.summary_scenario_combo.setObjectName("summary_scenario_combo")
        self.verticalLayout_3.addWidget(self.summary_scenario_combo)
        self.summary_results = QtWidgets.QLabel(self.summary)
        self.summary_results.setWordWrap(False)
        self.summary_results.setObjectName("summary_results")
        self.verticalLayout_3.addWidget(self.summary_results)
        self.summary_results_tree = QtWidgets.QTreeWidget(self.summary)
        self.summary_results_tree.setObjectName("summary_results_tree")
        self.summary_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_3.addWidget(self.summary_results_tree)
        self.widget_3 = QtWidgets.QWidget(self.summary)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Clipboard-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.summary, icon2, "")
        self.map = QtWidgets.QWidget()
        self.map.setObjectName("map")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.map)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.map_scenario = QtWidgets.QLabel(self.map)
        self.map_scenario.setWordWrap(False)
        self.map_scenario.setObjectName("map_scenario")
        self.verticalLayout_4.addWidget(self.map_scenario)
        self.map_scenario_combo = QtWidgets.QComboBox(self.map)
        self.map_scenario_combo.setObjectName("map_scenario_combo")
        self.verticalLayout_4.addWidget(self.map_scenario_combo)
        self.map_resulttype = QtWidgets.QLabel(self.map)
        self.map_resulttype.setWordWrap(False)
        self.map_resulttype.setObjectName("map_resulttype")
        self.verticalLayout_4.addWidget(self.map_resulttype)
        self.map_resulttype_combo = QtWidgets.QComboBox(self.map)
        self.map_resulttype_combo.setObjectName("map_resulttype_combo")
        self.map_resulttype_combo.addItem("")
        self.map_resulttype_combo.addItem("")
        self.map_resulttype_combo.addItem("")
        self.map_resulttype_combo.addItem("")
        self.verticalLayout_4.addWidget(self.map_resulttype_combo)
        self.map_viewmode = QtWidgets.QLabel(self.map)
        self.map_viewmode.setWordWrap(False)
        self.map_viewmode.setObjectName("map_viewmode")
        self.verticalLayout_4.addWidget(self.map_viewmode)
        self.map_viewmode_combo = QtWidgets.QComboBox(self.map)
        self.map_viewmode_combo.setObjectName("map_viewmode_combo")
        self.map_viewmode_combo.addItem("")
        self.map_viewmode_combo.addItem("")
        self.map_viewmode_combo.addItem("")
        self.verticalLayout_4.addWidget(self.map_viewmode_combo)
        self.map_results = QtWidgets.QLabel(self.map)
        self.map_results.setWordWrap(False)
        self.map_results.setObjectName("map_results")
        self.verticalLayout_4.addWidget(self.map_results)
        self.map_results_tree = QtWidgets.QTreeWidget(self.map)
        self.map_results_tree.setObjectName("map_results_tree")
        self.map_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.map_results_tree)
        self.map_control = QtWidgets.QWidget(self.map)
        self.map_control.setObjectName("map_control")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.map_control)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.map_options_button = QtWidgets.QPushButton(self.map_control)
        self.map_options_button.setText("")
        self.map_options_button.setIcon(icon1)
        self.map_options_button.setObjectName("map_options_button")
        self.gridLayout_2.addWidget(self.map_options_button, 0, 1, 1, 1)
        self.map_extents_button = QtWidgets.QPushButton(self.map_control)
        self.map_extents_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/2216358 - globe locati.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.map_extents_button.setIcon(icon3)
        self.map_extents_button.setObjectName("map_extents_button")
        self.gridLayout_2.addWidget(self.map_extents_button, 0, 0, 1, 1)
        self.map_export_button = QtWidgets.QPushButton(self.map_control)
        self.map_export_button.setText("")
        self.map_export_button.setIcon(icon)
        self.map_export_button.setObjectName("map_export_button")
        self.gridLayout_2.addWidget(self.map_export_button, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.map_control)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/GISLayers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.map, icon4, "")
        self.network = QtWidgets.QWidget()
        self.network.setObjectName("network")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.network)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.networks_scenario = QtWidgets.QLabel(self.network)
        self.networks_scenario.setWordWrap(False)
        self.networks_scenario.setObjectName("networks_scenario")
        self.verticalLayout_12.addWidget(self.networks_scenario)
        self.networks_scenario_combo = QtWidgets.QComboBox(self.network)
        self.networks_scenario_combo.setObjectName("networks_scenario_combo")
        self.verticalLayout_12.addWidget(self.networks_scenario_combo)
        self.networks_results = QtWidgets.QLabel(self.network)
        self.networks_results.setWordWrap(False)
        self.networks_results.setObjectName("networks_results")
        self.verticalLayout_12.addWidget(self.networks_results)
        self.networks_results_tree = QtWidgets.QTreeWidget(self.network)
        self.networks_results_tree.setObjectName("networks_results_tree")
        self.networks_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_12.addWidget(self.networks_results_tree)
        self.network_highlight = QtWidgets.QLabel(self.network)
        self.network_highlight.setWordWrap(False)
        self.network_highlight.setObjectName("network_highlight")
        self.verticalLayout_12.addWidget(self.network_highlight)
        self.network_highlightdegree = QtWidgets.QRadioButton(self.network)
        self.network_highlightdegree.setObjectName("network_highlightdegree")
        self.verticalLayout_12.addWidget(self.network_highlightdegree)
        self.network_highlightcentrality = QtWidgets.QRadioButton(self.network)
        self.network_highlightcentrality.setObjectName("network_highlightcentrality")
        self.verticalLayout_12.addWidget(self.network_highlightcentrality)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons8-mind-map-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.network, icon5, "")
        self.spatial = QtWidgets.QWidget()
        self.spatial.setObjectName("spatial")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.spatial)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stats_scenario = QtWidgets.QLabel(self.spatial)
        self.stats_scenario.setWordWrap(False)
        self.stats_scenario.setObjectName("stats_scenario")
        self.verticalLayout_5.addWidget(self.stats_scenario)
        self.stats_scenario_combo = QtWidgets.QComboBox(self.spatial)
        self.stats_scenario_combo.setObjectName("stats_scenario_combo")
        self.verticalLayout_5.addWidget(self.stats_scenario_combo)
        self.stats_query = QtWidgets.QLabel(self.spatial)
        self.stats_query.setWordWrap(False)
        self.stats_query.setObjectName("stats_query")
        self.verticalLayout_5.addWidget(self.stats_query)
        self.stats_query_combo = QtWidgets.QComboBox(self.spatial)
        self.stats_query_combo.setObjectName("stats_query_combo")
        self.verticalLayout_5.addWidget(self.stats_query_combo)
        self.stats_region_combo = QtWidgets.QLabel(self.spatial)
        self.stats_region_combo.setWordWrap(False)
        self.stats_region_combo.setObjectName("stats_region_combo")
        self.verticalLayout_5.addWidget(self.stats_region_combo)
        self.stats_region_list = QtWidgets.QListWidget(self.spatial)
        self.stats_region_list.setMinimumSize(QtCore.QSize(0, 0))
        self.stats_region_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.stats_region_list.setObjectName("stats_region_list")
        self.verticalLayout_5.addWidget(self.stats_region_list)
        self.stats_results = QtWidgets.QLabel(self.spatial)
        self.stats_results.setWordWrap(False)
        self.stats_results.setObjectName("stats_results")
        self.verticalLayout_5.addWidget(self.stats_results)
        self.stats_results_tree = QtWidgets.QTreeWidget(self.spatial)
        self.stats_results_tree.setObjectName("stats_results_tree")
        self.stats_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.stats_results_tree)
        self.stats_control = QtWidgets.QWidget(self.spatial)
        self.stats_control.setObjectName("stats_control")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.stats_control)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.stats_control)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.stats_control)
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.stats_control)
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.stats_control)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/gps-2845363_960_720.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.spatial, icon6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.correl_scenario = QtWidgets.QLabel(self.tab)
        self.correl_scenario.setWordWrap(False)
        self.correl_scenario.setObjectName("correl_scenario")
        self.verticalLayout_18.addWidget(self.correl_scenario)
        self.correl_scenario_combo = QtWidgets.QComboBox(self.tab)
        self.correl_scenario_combo.setObjectName("correl_scenario_combo")
        self.verticalLayout_18.addWidget(self.correl_scenario_combo)
        self.correl_query = QtWidgets.QLabel(self.tab)
        self.correl_query.setWordWrap(False)
        self.correl_query.setObjectName("correl_query")
        self.verticalLayout_18.addWidget(self.correl_query)
        self.correl_query_combo = QtWidgets.QComboBox(self.tab)
        self.correl_query_combo.setObjectName("correl_query_combo")
        self.verticalLayout_18.addWidget(self.correl_query_combo)
        self.correl_x = QtWidgets.QLabel(self.tab)
        self.correl_x.setWordWrap(False)
        self.correl_x.setObjectName("correl_x")
        self.verticalLayout_18.addWidget(self.correl_x)
        self.correl_x_combo = QtWidgets.QComboBox(self.tab)
        self.correl_x_combo.setObjectName("correl_x_combo")
        self.verticalLayout_18.addWidget(self.correl_x_combo)
        self.correl_y = QtWidgets.QLabel(self.tab)
        self.correl_y.setWordWrap(False)
        self.correl_y.setObjectName("correl_y")
        self.verticalLayout_18.addWidget(self.correl_y)
        self.correl_y_combo = QtWidgets.QComboBox(self.tab)
        self.correl_y_combo.setObjectName("correl_y_combo")
        self.verticalLayout_18.addWidget(self.correl_y_combo)
        self.correl_results = QtWidgets.QLabel(self.tab)
        self.correl_results.setWordWrap(False)
        self.correl_results.setObjectName("correl_results")
        self.verticalLayout_18.addWidget(self.correl_results)
        self.correl_results_tree = QtWidgets.QTreeWidget(self.tab)
        self.correl_results_tree.setObjectName("correl_results_tree")
        self.correl_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_18.addWidget(self.correl_results_tree)
        self.correl_pearson_check = QtWidgets.QCheckBox(self.tab)
        self.correl_pearson_check.setObjectName("correl_pearson_check")
        self.verticalLayout_18.addWidget(self.correl_pearson_check)
        self.correl_spearman_check = QtWidgets.QCheckBox(self.tab)
        self.correl_spearman_check.setObjectName("correl_spearman_check")
        self.verticalLayout_18.addWidget(self.correl_spearman_check)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Actions-office-chart-area-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.tab, icon7, "")
        self.compare = QtWidgets.QWidget()
        self.compare.setObjectName("compare")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.compare)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.compare_scenarioA = QtWidgets.QLabel(self.compare)
        self.compare_scenarioA.setWordWrap(False)
        self.compare_scenarioA.setObjectName("compare_scenarioA")
        self.verticalLayout_6.addWidget(self.compare_scenarioA)
        self.compare_scenarioA_combo = QtWidgets.QComboBox(self.compare)
        self.compare_scenarioA_combo.setObjectName("compare_scenarioA_combo")
        self.verticalLayout_6.addWidget(self.compare_scenarioA_combo)
        self.compare_scenarioB = QtWidgets.QLabel(self.compare)
        self.compare_scenarioB.setWordWrap(False)
        self.compare_scenarioB.setObjectName("compare_scenarioB")
        self.verticalLayout_6.addWidget(self.compare_scenarioB)
        self.compare_scenarioB_combo = QtWidgets.QComboBox(self.compare)
        self.compare_scenarioB_combo.setObjectName("compare_scenarioB_combo")
        self.verticalLayout_6.addWidget(self.compare_scenarioB_combo)
        self.compare_query = QtWidgets.QLabel(self.compare)
        self.compare_query.setWordWrap(False)
        self.compare_query.setObjectName("compare_query")
        self.verticalLayout_6.addWidget(self.compare_query)
        self.compare_query_combo = QtWidgets.QComboBox(self.compare)
        self.compare_query_combo.setObjectName("compare_query_combo")
        self.verticalLayout_6.addWidget(self.compare_query_combo)
        self.compare_results = QtWidgets.QLabel(self.compare)
        self.compare_results.setWordWrap(False)
        self.compare_results.setObjectName("compare_results")
        self.verticalLayout_6.addWidget(self.compare_results)
        self.compare_results_tree = QtWidgets.QTreeWidget(self.compare)
        self.compare_results_tree.setObjectName("compare_results_tree")
        self.compare_results_tree.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.compare_results_tree)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Bar-chart-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsNavigator.addTab(self.compare, icon8, "")
        self.verticalLayout.addWidget(self.resultsNavigator)
        self.horizontalLayout.addWidget(self.navigation_widget)
        self.resultsViewStack = QtWidgets.QStackedWidget(ResultsExplorer)
        self.resultsViewStack.setMinimumSize(QtCore.QSize(1000, 0))
        self.resultsViewStack.setObjectName("resultsViewStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.summary_group = QtWidgets.QGroupBox(self.page)
        self.summary_group.setObjectName("summary_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.summary_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.summary_view = QtWebEngineWidgets.QWebEngineView(self.summary_group)
        self.summary_view.setObjectName("summary_view")
        self.gridLayout_6.addWidget(self.summary_view, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.summary_group)
        self.resultsViewStack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.map_view = QtWebEngineWidgets.QWebEngineView(self.page_2)
        self.map_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.map_view.setObjectName("map_view")
        self.verticalLayout_11.addWidget(self.map_view)
        self.resultsViewStack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.network_view = QtWidgets.QGraphicsView(self.page_3)
        self.network_view.setObjectName("network_view")
        self.verticalLayout_14.addWidget(self.network_view)
        self.widget_4 = QtWidgets.QWidget(self.page_3)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 10))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.widget_4)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout_15.addWidget(self.horizontalScrollBar)
        self.verticalLayout_14.addWidget(self.widget_4)
        self.resultsViewStack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.stats_view = QtWebEngineWidgets.QWebEngineView(self.page_4)
        self.stats_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.stats_view.setObjectName("stats_view")
        self.verticalLayout_16.addWidget(self.stats_view)
        self.resultsViewStack.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.correl_group = QtWidgets.QGroupBox(self.page_6)
        self.correl_group.setObjectName("correl_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.correl_group)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.x_label = QtWidgets.QLabel(self.correl_group)
        self.x_label.setObjectName("x_label")
        self.gridLayout_4.addWidget(self.x_label, 0, 0, 1, 1)
        self.y_label = QtWidgets.QLabel(self.correl_group)
        self.y_label.setObjectName("y_label")
        self.gridLayout_4.addWidget(self.y_label, 0, 1, 1, 1)
        self.x_view = QtWebEngineWidgets.QWebEngineView(self.correl_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_view.sizePolicy().hasHeightForWidth())
        self.x_view.setSizePolicy(sizePolicy)
        self.x_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.x_view.setObjectName("x_view")
        self.gridLayout_4.addWidget(self.x_view, 1, 0, 1, 1)
        self.y_view = QtWebEngineWidgets.QWebEngineView(self.correl_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_view.sizePolicy().hasHeightForWidth())
        self.y_view.setSizePolicy(sizePolicy)
        self.y_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.y_view.setObjectName("y_view")
        self.gridLayout_4.addWidget(self.y_view, 1, 1, 1, 1)
        self.correl_lbl = QtWidgets.QLabel(self.correl_group)
        self.correl_lbl.setObjectName("correl_lbl")
        self.gridLayout_4.addWidget(self.correl_lbl, 2, 0, 1, 1)
        self.correl_summary_lbl = QtWidgets.QLabel(self.correl_group)
        self.correl_summary_lbl.setObjectName("correl_summary_lbl")
        self.gridLayout_4.addWidget(self.correl_summary_lbl, 2, 1, 1, 1)
        self.correl_view = QtWebEngineWidgets.QWebEngineView(self.correl_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correl_view.sizePolicy().hasHeightForWidth())
        self.correl_view.setSizePolicy(sizePolicy)
        self.correl_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.correl_view.setObjectName("correl_view")
        self.gridLayout_4.addWidget(self.correl_view, 3, 0, 1, 1)
        self.correl_summary_view = QtWebEngineWidgets.QWebEngineView(self.correl_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correl_summary_view.sizePolicy().hasHeightForWidth())
        self.correl_summary_view.setSizePolicy(sizePolicy)
        self.correl_summary_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.correl_summary_view.setObjectName("correl_summary_view")
        self.gridLayout_4.addWidget(self.correl_summary_view, 3, 1, 1, 1)
        self.verticalLayout_20.addWidget(self.correl_group)
        self.resultsViewStack.addWidget(self.page_6)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.compare_group = QtWidgets.QGroupBox(self.page_5)
        self.compare_group.setObjectName("compare_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.compare_group)
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.a_lbl = QtWidgets.QLabel(self.compare_group)
        self.a_lbl.setObjectName("a_lbl")
        self.gridLayout_5.addWidget(self.a_lbl, 0, 0, 1, 1)
        self.b_lbl = QtWidgets.QLabel(self.compare_group)
        self.b_lbl.setObjectName("b_lbl")
        self.gridLayout_5.addWidget(self.b_lbl, 0, 1, 1, 1)
        self.a_view = QtWebEngineWidgets.QWebEngineView(self.compare_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_view.sizePolicy().hasHeightForWidth())
        self.a_view.setSizePolicy(sizePolicy)
        self.a_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.a_view.setObjectName("a_view")
        self.gridLayout_5.addWidget(self.a_view, 1, 0, 1, 1)
        self.b_view = QtWebEngineWidgets.QWebEngineView(self.compare_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_view.sizePolicy().hasHeightForWidth())
        self.b_view.setSizePolicy(sizePolicy)
        self.b_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.b_view.setObjectName("b_view")
        self.gridLayout_5.addWidget(self.b_view, 1, 1, 1, 1)
        self.avb_lbl = QtWidgets.QLabel(self.compare_group)
        self.avb_lbl.setObjectName("avb_lbl")
        self.gridLayout_5.addWidget(self.avb_lbl, 2, 0, 1, 1)
        self.avb_summary_lbl = QtWidgets.QLabel(self.compare_group)
        self.avb_summary_lbl.setObjectName("avb_summary_lbl")
        self.gridLayout_5.addWidget(self.avb_summary_lbl, 2, 1, 1, 1)
        self.avb_view = QtWebEngineWidgets.QWebEngineView(self.compare_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avb_view.sizePolicy().hasHeightForWidth())
        self.avb_view.setSizePolicy(sizePolicy)
        self.avb_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.avb_view.setObjectName("avb_view")
        self.gridLayout_5.addWidget(self.avb_view, 3, 0, 1, 1)
        self.avb_summary_view = QtWebEngineWidgets.QWebEngineView(self.compare_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avb_summary_view.sizePolicy().hasHeightForWidth())
        self.avb_summary_view.setSizePolicy(sizePolicy)
        self.avb_summary_view.setProperty("url", QtCore.QUrl("about:blank"))
        self.avb_summary_view.setObjectName("avb_summary_view")
        self.gridLayout_5.addWidget(self.avb_summary_view, 3, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.compare_group)
        self.resultsViewStack.addWidget(self.page_5)
        self.horizontalLayout.addWidget(self.resultsViewStack)

        self.retranslateUi(ResultsExplorer)
        self.resultsNavigator.setCurrentIndex(0)
        self.resultsViewStack.setCurrentIndex(0)
        self.resultsNavigator.currentChanged['int'].connect(self.resultsViewStack.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(ResultsExplorer)

    def retranslateUi(self, ResultsExplorer):
        _translate = QtCore.QCoreApplication.translate
        ResultsExplorer.setWindowTitle(_translate("ResultsExplorer", "UrbanBEATS Results Explorer"))
        self.title.setText(_translate("ResultsExplorer", "Results Explorer"))
        self.subtitle.setText(_translate("ResultsExplorer", "Explore all available Project Results"))
        self.summary_scenario.setText(_translate("ResultsExplorer", "Select Scenario:"))
        self.summary_results.setText(_translate("ResultsExplorer", "Available Results:"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.summary), _translate("ResultsExplorer", "Summary"))
        self.map_scenario.setText(_translate("ResultsExplorer", "Select Scenario:"))
        self.map_resulttype.setText(_translate("ResultsExplorer", "Output Data Set:"))
        self.map_resulttype_combo.setItemText(0, _translate("ResultsExplorer", "Block Data"))
        self.map_resulttype_combo.setItemText(1, _translate("ResultsExplorer", "Temporal Water Demand"))
        self.map_resulttype_combo.setItemText(2, _translate("ResultsExplorer", "Urban Heat Island"))
        self.map_resulttype_combo.setItemText(3, _translate("ResultsExplorer", "Urban Model"))
        self.map_viewmode.setText(_translate("ResultsExplorer", "Select View Mode:"))
        self.map_viewmode_combo.setItemText(0, _translate("ResultsExplorer", "Basemap"))
        self.map_viewmode_combo.setItemText(1, _translate("ResultsExplorer", "Dashboard"))
        self.map_viewmode_combo.setItemText(2, _translate("ResultsExplorer", "Data Only View"))
        self.map_results.setText(_translate("ResultsExplorer", "Available Results:"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.map), _translate("ResultsExplorer", "Spatial"))
        self.networks_scenario.setText(_translate("ResultsExplorer", "Select Scenario:"))
        self.networks_results.setText(_translate("ResultsExplorer", "Available Networks:"))
        self.network_highlight.setText(_translate("ResultsExplorer", "Highlight Characteristics:"))
        self.network_highlightdegree.setText(_translate("ResultsExplorer", "Node Degrees"))
        self.network_highlightcentrality.setText(_translate("ResultsExplorer", "Centrality"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.network), _translate("ResultsExplorer", "Networks"))
        self.stats_scenario.setText(_translate("ResultsExplorer", "Select Scenario:"))
        self.stats_query.setText(_translate("ResultsExplorer", "Select Query Level:"))
        self.stats_region_combo.setText(_translate("ResultsExplorer", "Select Region:"))
        self.stats_results.setText(_translate("ResultsExplorer", "Available Results:"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.spatial), _translate("ResultsExplorer", "Statistics"))
        self.correl_scenario.setText(_translate("ResultsExplorer", "Select Scenario:"))
        self.correl_query.setText(_translate("ResultsExplorer", "Select Query Level:"))
        self.correl_x.setText(_translate("ResultsExplorer", "X-Axis"))
        self.correl_y.setText(_translate("ResultsExplorer", "Y-Axis"))
        self.correl_results.setText(_translate("ResultsExplorer", "Available Results:"))
        self.correl_pearson_check.setText(_translate("ResultsExplorer", "Pearson Correlation"))
        self.correl_spearman_check.setText(_translate("ResultsExplorer", "Spearman Rank"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.tab), _translate("ResultsExplorer", "Correlations"))
        self.compare_scenarioA.setText(_translate("ResultsExplorer", "Select Scenario A:"))
        self.compare_scenarioB.setText(_translate("ResultsExplorer", "Select Scenario B:"))
        self.compare_query.setText(_translate("ResultsExplorer", "Select Query Level:"))
        self.compare_results.setText(_translate("ResultsExplorer", "Available Results:"))
        self.resultsNavigator.setTabText(self.resultsNavigator.indexOf(self.compare), _translate("ResultsExplorer", "Comparison"))
        self.summary_group.setTitle(_translate("ResultsExplorer", "Summary"))
        self.correl_group.setTitle(_translate("ResultsExplorer", "Correlation Analysis"))
        self.x_label.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Block A (X-Axis Selection)</span></p></body></html>"))
        self.y_label.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Block B (Y-Axis Selection)</span></p></body></html>"))
        self.correl_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Correlation Plot</span></p></body></html>"))
        self.correl_summary_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Summary Statistics</span></p></body></html>"))
        self.compare_group.setTitle(_translate("ResultsExplorer", "Compare Scenario Results"))
        self.a_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">SCENARIO A</span></p></body></html>"))
        self.b_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">SCENARIO B</span></p></body></html>"))
        self.avb_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Scenario A vs. Scenario B</span></p></body></html>"))
        self.avb_summary_lbl.setText(_translate("ResultsExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Summary Statistics</span></p></body></html>"))
from PyQt5 import QtWebEngineWidgets
from . import ubeats_rc
